using System;using System.Linq;using System.IO;using System.Collections;using System.Collections.Generic;
using StudentAge.PlayingCards;using StudentAge.CampusPuzzles;using StudentAge.CampusUno;using UnityEngine;using UnityEngine.UI;
namespace StudentAge.CampusMinigames
{
    public sealed class LandlordView:PuzzleFrame
    {
        public LandlordGame Engine{get;private set;}public bool InputReady=>Started&&!busy&&!Ending&&Engine.Turn==0&&!handViews.Any(c=>c.IsMoving);CardArt art;RectTransform handRoot,bottomRoot,bidRoot,controls;readonly RectTransform[] piles=new RectTransform[3],backs=new RectTransform[3];readonly NativeSeatBadge[] seats=new NativeSeatBadge[3];readonly Text[] speech=new Text[3];readonly HashSet<int> selected=new HashSet<int>();readonly List<PlayingCardView> handViews=new List<PlayingCardView>();readonly Dictionary<int,Button> bidButtons=new Dictionary<int,Button>();Button play,pass,hint;bool busy;float aiAt;Text feedback;int lastDeals;Sprite desk;NativeCardTable physicalTable;
        protected override string Title=>"斗地主";
        protected override string[] Rules=>new[]{"三人各17张，留3张底牌。地主一人对两名农民。","每人叫一次分，可不叫或叫更高的1、2、3分。","最高叫分者拿底牌先出，叫3分立即定地主。","全部不叫则重发。任一农民出完，农民方获胜。","点击手牌选择，再点出牌；不出需等别人领出。","连续两家不出，最后出牌者重新领出。",
            "牌从小到大：3至K、A、2、小王、大王。","支持单张、对子、三张、三带一、三带一对。","顺子至少5张；连对至少3对；飞机至少2组三张。","连续牌不能有2和王。飞机可带等组数单牌或对子。","四带两张或两对；单翼可成对，不能带双王。","炸弹压普通牌，王炸最大；其余须同型同长度。"};
        protected override IEnumerator LoadAssets(){art=new CardArt(Path.Combine(Session.Root,"PlayingCards"));var back=art.Back;Engine=new LandlordGame(Level,Environment.TickCount);using(var stream=typeof(Plugin).Assembly.GetManifestResourceStream("CampusUno.Desk"))using(var bytes=new MemoryStream()){stream.CopyTo(bytes);var texture=new Texture2D(2,2);ImageConversion.LoadImage(texture,bytes.ToArray());Owned.Add(texture);desk=Sprite.Create(texture,new Rect(0,0,texture.width,texture.height),new Vector2(.5f,.5f));Owned.Add(desk);}yield break;}
        protected override void BuildPlay(){Root.Find("Classroom").GetComponent<Image>().sprite=desk;physicalTable=NativeCardTable.Create(PlayRoot);handRoot=R(PlayRoot,"YourHand",0,0,1600,900);bottomRoot=R(PlayRoot,"BottomCards",667,127,290,150);bidRoot=R(PlayRoot,"Bidding",0,0,1600,900);controls=R(PlayRoot,"PlayButtons",0,0,1600,900);
            seats[0]=NativeSeatBadge.Create(PlayRoot,CardSeatIdentity.Role(0),19,710,198);seats[1]=NativeSeatBadge.Create(PlayRoot,CardSeatIdentity.Role(Session.NpcId),54,174);seats[2]=NativeSeatBadge.Create(PlayRoot,CardSeatIdentity.Classmate(0),1308,174);
            speech[0]=Flash(PlayRoot,600,337,400,52);speech[1]=Flash(PlayRoot,300,188,310,54);speech[2]=Flash(PlayRoot,990,188,310,54);backs[1]=R(PlayRoot,"OtherHand1",20,365,230,340);backs[2]=R(PlayRoot,"OtherHand2",1360,365,230,340);piles[0]=R(PlayRoot,"YourPlay",494,370,650,155);piles[1]=R(PlayRoot,"LeftPlay",331,268,390,155);piles[2]=R(PlayRoot,"RightPlay",916,268,390,155);
            feedback=Flash(PlayRoot,455,580,690,42);for(int n=0;n<4;n++){int score=n;bidButtons[n]=B(bidRoot,n==0?"不叫":"叫"+n+"分",410+n*210,503,190,78,()=>HumanBid(score),n==0);}
            play=B(controls,"出牌",930,506,210,78,HumanPlay);pass=B(controls,"不出",460,506,210,78,HumanPass,true);hint=B(controls,"提示",695,506,210,78,Hint,true);
            foreach(var button in new[]{play,pass,hint}){var colors=button.colors;colors.normalColor=Color.white;colors.highlightedColor=Color.white;colors.pressedColor=new Color(.88f,.88f,.88f,1);colors.selectedColor=Color.white;colors.disabledColor=new Color(.7f,.7f,.7f,1);button.colors=colors;}
            // Every hand and played-card pile stays below the opaque action controls, including cards in flight.
            bidRoot.SetAsLastSibling();controls.SetAsLastSibling();
            foreach(var title in Root.GetComponentsInChildren<Text>().Where(t=>t.text==Title)){title.color=Cream;var line=title.gameObject.AddComponent<Outline>();line.effectColor=new Color(.22f,.12f,.06f,.9f);line.effectDistance=new Vector2(2,-2);}
        }
        Text Flash(Transform parent,float x,float y,float w,float h){var t=T(parent,"",x,y,w,h,31);t.color=Cream;var line=t.gameObject.AddComponent<Outline>();line.effectColor=new Color(.25f,.13f,.055f,.95f);line.effectDistance=new Vector2(2,-2);return t;}
        protected override void StartGame(){lastDeals=Engine.Deals;Refresh(true);StartCoroutine(DealDelay());}
        IEnumerator DealDelay(){TableSound("deal",.48f);busy=true;yield return new StudentAge.CampusUno.PlayDelay(2.08f);foreach(var card in handViews)card.Flip(false);yield return new StudentAge.CampusUno.PlayDelay(.4f);busy=false;aiAt=StudentAge.CampusUno.PlayClock.Now+.6f;RefreshControls();}
        string Name(int seat)=>seats[seat].Identity.Name;
        string Role(int seat)=>Engine.Bidding?"":seat==Engine.Landlord?" · 地主":" · 农民";
        void Refresh(bool deal=false){var old=handViews.Where(v=>v!=null).ToDictionary(v=>v.Card.Id,v=>v.Position);Clear(handRoot);handViews.Clear();int count=Engine.Hands[0].Count;float span=Math.Min(1030,(count-1)*72);
            for(int i=0;i<count;i++){float u=count<=1?0:i/(float)(count-1)-.5f;var card=PlayingCardView.Create(handRoot,art,Engine.Hands[0][i],800+u*span-70,738+Math.Abs(u)*30-98,140,deal);card.TablePose(-u*22,-10,u*4);card.transform.SetSiblingIndex(i);card.Clicked=Toggle;card.Select(selected.Contains(card.Card.Id));card.Interactable=Engine.Turn==0&&!Engine.Bidding;handViews.Add(card);
                if(deal)card.MoveFrom(new Vector2(800,-337),i*3*.040f,.038f,0);else if(old.ContainsKey(card.Card.Id))card.ReflowFrom(old[card.Card.Id]);else if(old.Count>0)card.FlyFrom(new Vector2(800,-210),i*.012f,.52f,0,.55f,-35);}
            for(int i=0;i<handViews.Count-1;i++)handViews[i].ShadeFrom(handViews[i+1]);
            Clear(bottomRoot);for(int i=0;i<3;i++){var bottom=PlayingCardView.Create(bottomRoot,art,Engine.Bottom[i],i*93,0,82,Engine.Bidding);bottom.TablePose((i-1)*4,-22,(i-1)*2);bottom.Interactable=false;}
            for(int n=0;n<3;n++){seats[n].UpdateInfo(Role(n),Engine.Hands[n].Count,Engine.Turn==n);if(n==0)continue;Clear(backs[n]);int backCount=Engine.Hands[n].Count;for(int j=0;j<backCount;j++){float u=backCount<=1?0:j/(float)(backCount-1)-.5f;var c=PlayingCardView.Create(backs[n],art,Engine.Hands[n][j],45+Math.Abs(u)*24,105+u*180,88,true);c.TablePose((n==1?-62:62)-u*20,-14,u*4);c.Interactable=false;if(deal)c.MoveFrom(new Vector2(800,-337)-backs[n].anchoredPosition,(j*3+n)*.040f,.038f,0);}}
            if(deal){foreach(var p in piles)Clear(p);foreach(var t in speech)t.text="";}RefreshControls();}
        void RefreshControls(){bool bid=Engine.Bidding;bidRoot.gameObject.SetActive(bid&&Engine.Turn==0);controls.gameObject.SetActive(!bid);foreach(var entry in bidButtons)entry.Value.interactable=InputReady&&(entry.Key==0||entry.Key>Engine.HighBid);play.interactable=hint.interactable=InputReady&&!bid;pass.interactable=InputReady&&Engine.CanPass;foreach(var card in handViews)card.Interactable=InputReady&&!bid;}
        void Toggle(PlayingCardView card){if(!InputReady||Engine.Bidding)return;if(!selected.Add(card.Card.Id))selected.Remove(card.Card.Id);card.Select(selected.Contains(card.Card.Id));TableSound("slide",.23f);feedback.text="";}
        public void HumanBid(int value){if(!InputReady||!Engine.Bidding)return;DoBid(0,value);}
        void DoBid(int actor,int value){if(!Engine.Bid(actor,value))return;TableSound("voice-bid"+value,.7f);bool redeal=Engine.Deals!=lastDeals;lastDeals=Engine.Deals;selected.Clear();Refresh(redeal);if(!redeal)speech[actor].text=value==0?"不叫":"叫"+value+"分";if(redeal)StartCoroutine(DealDelay());aiAt=StudentAge.CampusUno.PlayClock.Now+.8f;}
        public void HumanPlay(){if(!InputReady||Engine.Bidding)return;var cards=Engine.Hands[0].Where(c=>selected.Contains(c.Id)).ToArray();if(!DoPlay(0,cards))feedback.text=cards.Length==0?"先选要出的牌":"牌型不符，或压不过上家";}
        public void HumanPass(){if(!InputReady)return;if(Engine.Pass(0)){selected.Clear();speech[0].text="不出";TableSound("voice-pass",.6f);feedback.text="";Refresh();aiAt=StudentAge.CampusUno.PlayClock.Now+.8f;}}
        public void Hint(){if(!InputReady||Engine.Bidding)return;selected.Clear();var move=Engine.Choose(0,5);if(move!=null)foreach(var c in move)selected.Add(c.Id);feedback.text=move==null?"可以不出":"";foreach(var c in handViews)c.Select(selected.Contains(c.Card.Id));}
        bool DoPlay(int actor,PlayingCard[] cards){var origins=new Dictionary<int,Vector3>();if(actor==0)foreach(var v in handViews)origins[v.Card.Id]=v.transform.position;
            if(!Engine.Play(actor,cards))return false;selected.Clear();feedback.text="";Refresh();foreach(RectTransform previous in piles[actor]){previous.anchoredPosition+=new Vector2(-3,-5);previous.localEulerAngles+=new Vector3(0,0,1);}
            var played=R(piles[actor],"PlayedCards",0,0,650,155);speech[actor].text=LandlordRules.Name(Engine.Previous.Kind);float step=Math.Min(63,(actor==0?530f:290f)/Math.Max(1,cards.Length-1));var sorted=cards.OrderByDescending(LandlordRules.Rank).ToArray();PlayingCardView underneath=null;
            for(int i=0;i<cards.Length;i++){var card=PlayingCardView.Create(played,art,sorted[i],i*step,0,108,actor!=0);card.TablePose((i-(cards.Length-1)*.5f)*.9f,-22,actor==1?-3:actor==2?3:0);card.Interactable=false;Vector3 world;if(!origins.TryGetValue(card.Card.Id,out world))world=backs[actor].TransformPoint(new Vector3(90,-170,0));Vector2 origin=played.InverseTransformPoint(world);card.FlyFrom(origin,i*.022f,.54f,actor==1?-64:actor==2?64:0,actor==0?1.29f:.9f,-12);if(actor!=0)card.Flip(false);if(underneath!=null)underneath.ShadeFrom(card);underneath=card;}
            TableSound("slide",.35f);StartCoroutine(PlaySounds(Engine.Previous.Kind));busy=true;StartCoroutine(AfterPlay());return true;}
        IEnumerator PlaySounds(LandlordKind kind){yield return new PlayDelay(.45f);TableSound("slap",.55f);string name=null;switch(kind){case LandlordKind.Bomb:name="bomb";break;case LandlordKind.Rocket:name="rocket";break;case LandlordKind.TripleRun:case LandlordKind.PlaneSingles:case LandlordKind.PlanePairs:name="plane";break;case LandlordKind.Straight:name="straight";break;case LandlordKind.PairRun:name="pairstraight";break;case LandlordKind.TripleSingle:name="trio_single";break;case LandlordKind.TriplePair:name="trio_pair";break;case LandlordKind.FourSingles:name="four_two";break;case LandlordKind.FourPairs:name="four_twopair";break;}if(name!=null){TableSound("voice-"+name,.8f);if(name=="bomb"||name=="rocket")TableSound("bomb",.45f);else if(name=="plane")TableSound("plane",.4f);else if(name=="straight")TableSound("straight",.4f);}}
        IEnumerator AfterPlay(){yield return new StudentAge.CampusUno.PlayDelay(.65f+Engine.LastCards.Length*.022f);busy=false;if(Engine.Winner>=0){Finish(Engine.HumanWon);yield break;}aiAt=StudentAge.CampusUno.PlayClock.Now+.55f;RefreshControls();}
        protected override void Tick(){RefreshControls();if(busy||Engine.Turn==0||StudentAge.CampusUno.PlayClock.Now<aiAt)return;int actor=Engine.Turn;if(Engine.Bidding)DoBid(actor,Engine.AiBid(actor));else{var chosen=Engine.Choose(actor);if(chosen==null){if(Engine.Pass(actor)){speech[actor].text="不出";TableSound("voice-pass",.6f);Refresh();aiAt=StudentAge.CampusUno.PlayClock.Now+.75f;}}else DoPlay(actor,chosen);}}
        protected override void OnDestroy(){base.OnDestroy();art?.Dispose();}
    }
}
