using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using UnityEngine;using UnityEngine.UI;using UnityEngine.Networking;using UnityEngine.InputSystem;using StudentAge.CampusUno;using StudentAge.Sanguosha;using Sdk;
namespace StudentAge.CampusMinigames {
 public static class SanguoshaAssets {
  public static string Root=>Path.Combine(Path.GetDirectoryName(typeof(SanguoshaView).Assembly.Location),"Sanguosha");static readonly Dictionary<string,Texture2D> images=new Dictionary<string,Texture2D>();static readonly Dictionary<string,Sprite> sprites=new Dictionary<string,Sprite>();
  public static Texture2D Image(string path){if(images.TryGetValue(path,out var t)&&t!=null)return t;string f=Path.Combine(Root,path);if(!File.Exists(f))return null;t=new Texture2D(2,2,TextureFormat.RGBA32,false);ImageConversion.LoadImage(t,File.ReadAllBytes(f));t.filterMode=FilterMode.Bilinear;t.wrapMode=TextureWrapMode.Clamp;images[path]=t;return t;}
  public static Sprite Sprite(string id){if(sprites.TryGetValue(id,out var s)&&s!=null)return s;var t=Image(id=="box"?"back.png":"generals/"+id+".jpg");if(t==null)return null;s=UnityEngine.Sprite.Create(t,new Rect(0,0,t.width,t.height),new Vector2(.5f,.5f),100);sprites[id]=s;return s;}
 }
 public sealed class SanguoshaView:MonoBehaviour {
  public static SanguoshaView Current{get;private set;}public Match Engine{get;private set;}public SanguoshaSession Session{get;private set;}public bool Closed{get;private set;}public bool Paused{get;private set;}
  GameObject blocker;float oldScale,aiAt,eventAt,resultAt;int eventSeq,page,optionPage,selectedIndex;bool easy=true,started,collection,settled,help;string selected="zhaoyun",inspect,notice="";Prompt shownPrompt;MatchEvent shownEvent;NativeMinigameAudio scope;AudioSource music,effect;readonly Dictionary<string,AudioClip> clips=new Dictionary<string,AudioClip>();Queue<MatchEvent> events=new Queue<MatchEvent>();GUIStyle label,small,button,title;Vector2 logScroll,detailScroll;
  public static bool Open(int npc){if(Current!=null||Plugin.IsBusy||!SanguoshaIntegration.Owned||(npc>0&&!SanguoshaIntegration.CanFight(npc)))return false;var obj=new GameObject("SanguoshaHost");var v=obj.AddComponent<SanguoshaView>();if(!Plugin.AcquireExternal(Invalidate)){Destroy(obj);return false;}Current=v;DontDestroyOnLoad(obj);try{v.collection=npc==0;if(npc>0)v.Session=new SanguoshaSession(npc);v.Build();return true;}catch{v.Close();throw;}}
  void Build(){oldScale=Time.timeScale;Time.timeScale=0;Control.ToggleActionMap(false);blocker=new GameObject("SanguoshaInputBlocker",typeof(RectTransform),typeof(Canvas),typeof(GraphicRaycaster));var canvas=blocker.GetComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;canvas.sortingOrder=32760;var back=new GameObject("ModalShield",typeof(RectTransform),typeof(Image));back.transform.SetParent(blocker.transform,false);var r=(RectTransform)back.transform;r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=r.offsetMax=Vector2.zero;back.GetComponent<Image>().color=Color.clear;
   scope=NativeMinigameAudio.Open(gameObject,0,true);music=gameObject.AddComponent<AudioSource>();music.playOnAwake=false;music.loop=true;music.volume=.48f;scope.UseLocalMusic(music);scope.SetMusicPaused(false);effect=gameObject.AddComponent<AudioSource>();effect.playOnAwake=false;scope.Bind(effect);StartCoroutine(LoadSounds());}
  IEnumerator LoadSounds(){string dir=Path.Combine(SanguoshaAssets.Root,"audio");if(!Directory.Exists(dir))yield break;var files=Directory.GetFiles(dir,"*.ogg").OrderBy(f=>Path.GetFileNameWithoutExtension(f)=="background"?0:1);foreach(var f in files){using(var request=UnityWebRequestMultimedia.GetAudioClip(new Uri(f).AbsoluteUri,AudioFormat(f))){yield return request.SendWebRequest();if(Closed)yield break;if(request.result!=UnityWebRequest.Result.Success)continue;string key=Path.GetFileNameWithoutExtension(f);clips[key]=DownloadHandlerAudioClip.GetContent(request);if(key=="background"){music.clip=clips[key];if(!Paused)music.Play();}}}}
  static AudioType AudioFormat(string path){using(var f=File.OpenRead(path)){byte[] head=new byte[4];f.Read(head,0,4);return head[0]==82&&head[1]==73&&head[2]==70&&head[3]==70?AudioType.WAV:head[0]==79&&head[1]==103&&head[2]==103&&head[3]==83?AudioType.OGGVORBIS:AudioType.MPEG;}}
  public int DecodedAudioCount=>clips.Count;public bool MusicPlaying=>music!=null&&music.isPlaying;
  void Sound(string key,int actor=0){if(key==null)return;string sex=Engine!=null&&actor>=0&&Engine.Seats[actor].General.Female?"female-":"male-";AudioClip clip;if(clips.TryGetValue(sex+key,out clip)||clips.TryGetValue(key,out clip))effect.PlayOneShot(clip,.78f);}
  public bool StartBattle(string general,bool simple){if(started||Session==null||!SanguoshaIntegration.Has(general)||!Session.Begin())return false;selected=general;easy=simple;started=true;Engine=new Match(selected,Session.Opponent,easy,Environment.TickCount);aiAt=Time.unscaledTime+.6f;return true;}
  public void SelectOption(int index){if(Engine?.Pending==null||Engine.Pending.Actor!=0||Paused||inspect!=null)return;Engine.Choose(index);optionPage=0;aiAt=Time.unscaledTime+.55f;}
  void Update(){if(Closed)return;var k=Keyboard.current;if(k!=null&&k.escapeKey.wasPressedThisFrame){if(inspect!=null){inspect=null;return;}if(help){help=false;return;}if(!started){Close();return;}if(Engine.Winner==-2){Paused=!Paused;if(Paused){music.Pause();effect.Pause();}else{music.UnPause();effect.UnPause();aiAt=Time.unscaledTime+.5f;}return;}}
   if(Session!=null&&!settled&&!Session.Valid){Close();return;}if(Engine==null||Paused||help||inspect!=null)return;if(k!=null&&k.f6Key.wasPressedThisFrame&&Engine.Winner==-2)Engine.Surrender(1);
   foreach(var ev in Engine.Events.Where(e=>e.Sequence>eventSeq)){events.Enqueue(ev);eventSeq=ev.Sequence;}
   if(events.Count>0&&Time.unscaledTime-eventAt>.22f){shownEvent=events.Dequeue();eventAt=Time.unscaledTime;Sound(shownEvent.Sound,shownEvent.Actor);}
   if(Engine.Pending!=shownPrompt){shownPrompt=Engine.Pending;optionPage=0;selectedIndex=-1;}
   if(Engine.Pending?.Actor==1&&Time.unscaledTime>=aiAt&&events.Count<2){Engine.Choose(Engine.AiChoice());aiAt=Time.unscaledTime+.4f;}
   if(Engine.Winner!=-2&&!settled){settled=true;bool ok=Session.Finish(Engine.Winner==0);resultAt=Time.unscaledTime;scope.FadeMusicPaused(true,.5f);notice=ok?(Engine.Winner==0?"胜利":"下回合再战")+" · 好感 +"+Session.Favor.ToString("0.#"):"牌局已结束";StartCoroutine(ResultSound());}}
  IEnumerator ResultSound(){yield return new WaitForSecondsRealtime(.4f);events.Clear();Sound(Engine.Winner==0?"win":"lose");}
  void Styles(){if(label!=null)return;Font font=NativeSkin.TitleFont;label=new GUIStyle(GUI.skin.label){font=font,fontSize=23,wordWrap=true,alignment=TextAnchor.MiddleLeft,richText=false,normal={textColor=new Color(.92f,.87f,.75f)}};small=new GUIStyle(label){fontSize=18};title=new GUIStyle(label){fontSize=42,alignment=TextAnchor.MiddleCenter};button=new GUIStyle(GUI.skin.button){font=font,fontSize=21,wordWrap=true,normal={textColor=new Color(.96f,.9f,.7f)},hover={textColor=Color.white}};}
  static void Rect(Rect r,Color c){var old=GUI.color;GUI.color=c;GUI.DrawTexture(r,Texture2D.whiteTexture);GUI.color=old;}
  static void Frame(Rect r){Rect(r,new Color(.64f,.49f,.26f,.9f));Rect(new Rect(r.x+2,r.y+2,r.width-4,r.height-4),new Color(.055f,.075f,.075f,.97f));}
  void Text(string s,float x,float y,float w,float h,GUIStyle style=null)=>GUI.Label(new Rect(x,y,w,h),s,style??label);
  bool Btn(string text,float x,float y,float w,float h,bool enabled=true){bool before=GUI.enabled;GUI.enabled=before&&enabled;bool pressed=GUI.Button(new Rect(x,y,w,h),text,button);GUI.enabled=before;return pressed;}
  void Picture(string path,Rect r,bool dim=false){var t=SanguoshaAssets.Image(path);if(t==null)return;Color prev=GUI.color;if(dim)GUI.color=new Color(.32f,.32f,.32f,1);GUI.DrawTexture(r,t,ScaleMode.ScaleToFit);GUI.color=prev;}
  void OnGUI(){if(Closed)return;GUI.depth=-32000;Styles();var old=GUI.matrix;float scale=Math.Min(Screen.width/1600f,Screen.height/900f);GUI.matrix=Matrix4x4.TRS(new Vector3((Screen.width-1600*scale)/2,(Screen.height-900*scale)/2,0),Quaternion.identity,new Vector3(scale,scale,1));Rect(new Rect(-4000,-4000,10000,10000),Color.black);Picture("board.jpg",new Rect(0,0,1600,900));Rect(new Rect(0,0,1600,900),new Color(0,0,0,.38f));
   GUI.enabled=inspect==null&&!help&&!Paused;if(!started)Collection();else Board();GUI.enabled=true;if(inspect!=null)Detail();else if(help)Help();else if(Paused)PauseMenu();GUI.matrix=old;}
  void Collection(){Frame(new Rect(35,30,1530,840));Text(collection?"三国杀 · 武将卡册":"三国杀 · 择将应战",400,45,800,60,title);if(Btn("返回",65,55,140,45))Close();if(Btn("规则",1390,55,130,45))help=true;
   var owned=Catalog.Generals.Count(g=>SanguoshaIntegration.Has(g.Id));Text("已收藏 "+owned+" / 35",70,113,330,40);if(Session!=null)Text(Session.Name+" · 第"+(Session.Stage+1)+"关  · 对阵 "+Catalog.Get(Session.Opponent).Name,570,113,900,40);else Text("点击武将查看技能与获取方式",570,113,900,40);
   for(int i=0;i<14;i++){int idx=page*14+i;if(idx>=Catalog.Generals.Length)break;var g=Catalog.Generals[idx];float x=85+(i%7)*205,y=180+(i/7)*253;bool has=SanguoshaIntegration.Has(g.Id);if(selected==g.Id&&!collection)Rect(new Rect(x-5,y-5,160,231),new Color(.9f,.69f,.2f));Picture("generals/"+g.Id+".jpg",new Rect(x,y,150,218),!has);if(GUI.Button(new Rect(x,y,150,218),GUIContent.none,GUIStyle.none)){if(has&&!collection)selected=g.Id;else inspect=g.Id;}Text(g.Name+(has?"":" · 未收集"),x-5,y+217,180,30,small);if(!collection&&has&&Btn("技能",x+155,y+158,43,56))inspect=g.Id;}
   if(Btn("上一页",65,735,160,44,page>0))page--;Text((page+1)+" / 3",240,735,120,44);if(Btn("下一页",350,735,160,44,page<2))page++;
   if(!collection){if(Btn(easy?"● 简单":"○ 简单",580,731,175,47))easy=true;if(Btn(!easy?"● 复杂":"○ 复杂",767,731,175,47))easy=false;Text(easy?"双方：每回合两杀 · 摸三张 · 体力上限+1":"双方：每回合一杀 · 摸两张 · 原始体力",580,786,620,45,small);if(Btn("开始对战",1240,747,240,64))StartBattle(selected,easy);}else Text("赢得角色关卡可收集武将。其余卡牌在小卖铺购买。",580,755,900,50);}
  void GeneralAt(int a,float x,float y){var p=Engine.Seats[a];Frame(new Rect(x-8,y-8,194,270));Picture("generals/"+p.General.Id+".jpg",new Rect(x,y,178,258),p.FaceDown);if(GUI.Button(new Rect(x,y,178,258),GUIContent.none,GUIStyle.none))inspect=p.General.Id;Text(p.Hp+" / "+p.MaxHp+" 体力",x,y+268,200,36);Text("手牌 "+p.Hand.Count+(p.FaceDown?" · 翻面":""),x,y+305,220,34,small);if(p.Nightmare>0||p.Buqu.Count>0)Text("梦魇 "+p.Nightmare+" · 不屈 "+p.Buqu.Count,x,y+338,220,34,small);}
  void Board(){Frame(new Rect(20,20,1560,65));Text("三国杀",45,23,240,58,title);Text(Session.Name+" · 第"+(Session.Stage+1)+"关",330,33,360,40);Text((easy?"简单":"复杂")+" · "+Engine.Phase,760,33,550,40);if(Btn("规则",1445,32,110,42))help=true;
   GeneralAt(1,75,120);GeneralAt(0,75,532);Text("对手 · "+Session.Name,300,114,430,35);for(int i=0;i<Math.Min(12,Engine.Seats[1].Hand.Count);i++)Picture("back.png",new Rect(310+i*48,161,60,87));
   for(int a=0;a<2;a++){var p=Engine.Seats[a];float y=a==1?275:471;for(int i=0;i<4;i++){var c=p.Equipment[i];Frame(new Rect(310+i*175,y,165,51));Text(c?.Name??new[]{"武器","防具","防御马","进攻马"}[i],320+i*175,y+4,155,44,small);}Text("判定区："+string.Join(" · ",p.Judgments.Select(c=>c.Name).ToArray()),310,y+54,740,33,small);}
   if(shownEvent!=null){float age=Time.unscaledTime-eventAt;float t=Mathf.Clamp01(age/.42f);float ease=1-Mathf.Pow(1-t,3);if(shownEvent.Card!=null){float fromY=shownEvent.Actor==0?560:155;float fromX=shownEvent.Actor==0?560:410;var rect=new Rect(Mathf.Lerp(fromX,825,ease),Mathf.Lerp(fromY,155,ease),102,148);Picture("cards/"+shownEvent.Card.Kind+".png",rect);Text(shownEvent.Card.Face,rect.x+6,rect.y+4,90,30,small);}Text(shownEvent.Text,300,375,730,70);
    if(shownEvent.Sound=="injure1"&&shownEvent.Target>=0&&age<.72f){float y=shownEvent.Target==0?532:120;Picture("fx/slash-"+Math.Min(23,(int)(age/.72f*24))+".png",new Rect(25,y-25,280,280));Rect(new Rect(67,y-8,194,270),new Color(1,.05f,.02f,.2f*(1-age/.72f)));}}

   Frame(new Rect(1100,111,450,335));Text("战报",1120,120,400,35);logScroll=GUI.BeginScrollView(new Rect(1115,165,420,265),logScroll,new Rect(0,0,390,Math.Max(265,Engine.Log.Count*31)));for(int i=0;i<Engine.Log.Count;i++)Text(Engine.Log[i],5,i*31,380,31,small);GUI.EndScrollView();
   var hand=Engine.Seats[0].Hand;float width=Math.Min(104,930f/Math.Max(1,hand.Count));for(int i=0;i<hand.Count;i++){var card=hand[i];float x=300+i*width,y=562;bool active=Engine.Pending?.Actor==0&&Engine.Pending.Options.Any(o=>o.CardId==card.Id)==true;if(active)Rect(new Rect(x-2,y-2,104,151),new Color(.8f,.65f,.25f));Picture("cards/"+card.Kind+".png",new Rect(x,y,100,145));Rect(new Rect(x+4,y+4,43,52),new Color(.95f,.9f,.76f,.92f));var col=small.normal.textColor;small.normal.textColor=card.Red?new Color(.7f,.06f,.03f):Color.black;Text(card.Face,x+6,y+5,40,45,small);small.normal.textColor=col;if(GUI.Button(new Rect(x,y,width,145),GUIContent.none,GUIStyle.none)&&active){var opts=Engine.Pending.Options.Select((o,n)=>new{o,n}).Where(z=>z.o.CardId==card.Id).ToArray();if(opts.Length==1)SelectOption(opts[0].n);else{selectedIndex=card.Id;optionPage=0;}}}
   if(Engine.Winner!=-2){Result();return;}if(Engine.Pending?.Actor==0){var prompt=Engine.Pending;Frame(new Rect(280,730,1265,150));Text(prompt.Text,302,738,1200,34);var options=prompt.Options.Select((o,i)=>new{o,i}).Where(x=>selectedIndex<0||x.o.CardId==selectedIndex||x.o.CardId<0).ToArray();int pages=Math.Max(1,(options.Length+7)/8);optionPage=Math.Min(optionPage,pages-1);for(int i=0;i<8;i++){int index=optionPage*8+i;if(index>=options.Length)break;var choice=options[index];if(Btn(choice.o.Label,300+(i%4)*280,780+(i/4)*45,267,40))SelectOption(choice.i);}if(Btn("‹",1430,780,45,40,optionPage>0))optionPage--;if(Btn("›",1482,780,45,40,optionPage<pages-1))optionPage++;if(selectedIndex>=0&&Btn("全部",1430,825,98,40))selectedIndex=-1;
    if(prompt.Reveal!=null&&prompt.Reveal.Count>0){Frame(new Rect(400,330,680,190));int cnt=prompt.Reveal.Count;float gap=Math.Min(105,640f/cnt);for(int i=0;i<cnt;i++){var c=prompt.Reveal[i];Picture("cards/"+c.Kind+".png",new Rect(416+i*gap,348,95,138));Text(c.Face,422+i*gap,487,95,24,small);}}}
   else Text("对手正在思考……",550,782,700,60,title);
  }
  void Result(){Frame(new Rect(455,267,950,285));Text(Engine.Winner==0?"胜 利":Engine.Winner==1?"惜 败":"和 局",600,281,660,65,title);Text(notice,555,357,780,45);if(Session.Reward!=null)Text("获得武将卡："+Catalog.Get(Session.Reward).Name,555,410,780,43);else Text("本回合已对战，下回合可以再次挑战。",555,410,780,43);if(Btn("收起牌桌",785,472,255,58,Time.unscaledTime-resultAt>.8f))Close();}
  void Detail(){Rect(new Rect(0,0,1600,900),new Color(0,0,0,.82f));Frame(new Rect(275,65,1050,770));var g=Catalog.Get(inspect);Picture("generals/"+g.Id+".jpg",new Rect(320,115,400,580));Text(g.Name+" · "+g.Kingdom,775,125,490,75,title);Text("原始体力 "+g.Hp,800,213,450,45);detailScroll=GUI.BeginScrollView(new Rect(775,280,475,310),detailScroll,new Rect(0,0,440,Math.Max(300,label.CalcHeight(new GUIContent(g.Description),420))));Text(g.Description,10,0,420,Math.Max(300,label.CalcHeight(new GUIContent(g.Description),420)));GUI.EndScrollView();Text(SanguoshaIntegration.Has(g.Id)?"已收藏":g.Id=="zhaoyun"?"购买三国杀赠送":Encounters.Sold(g.Id)?"小卖铺 · "+Encounters.Price(g.Id)+"元":"角色对战胜利奖励",785,617,450,60);if(Btn("返回牌桌",800,735,340,60))inspect=null;}
  void Help(){Rect(new Rect(0,0,1600,900),new Color(0,0,0,.84f));Frame(new Rect(245,100,1110,710));Text("三国杀 · 单挑规则",450,115,700,70,title);Picture("cards/slash.png",new Rect(290,250,140,203));Picture("cards/jink.png",new Rect(450,250,140,203));Picture("cards/peach.png",new Rect(610,250,140,203));Text("杀 → 对手出闪抵消\n桃 → 回复一点体力\n锦囊 → 依牌面结算，可用无懈可击响应",810,255,480,220);Text("准备 → 判定 → 摸牌 → 出牌 → 弃牌 → 结束\n复杂模式：摸2张、通常限出1杀；简单模式：摸3张、限出2杀、双方体力上限+1。\n牌局使用旧标准与旧风包技能。单挑没有主公技和第三方目标；离间、流离因此不能发动。\n点击手牌或下方操作按钮出牌；有多个用法时选择转换技能。点击武将卡查看技能。Esc 暂停。",290,490,1000,240);if(Btn("继续",1080,735,215,50))help=false;}
  void PauseMenu(){Rect(new Rect(0,0,1600,900),new Color(0,0,0,.8f));Frame(new Rect(535,225,530,415));Text("三国杀 · 暂停",575,255,450,65,title);if(Btn("继续对战",625,365,350,65)){Paused=false;music.UnPause();effect.UnPause();}if(Btn("认输并收起牌桌",625,455,350,65)){Paused=false;music.UnPause();effect.UnPause();Engine.Surrender(0);}Text("认输仍获得10好感，下回合才能再战。",565,551,475,50,small);}
  public static void Invalidate(){if(Current!=null)Current.Close();}
  public void Close(){if(Closed)return;Closed=true;StopAllCoroutines();if(scope!=null)scope.Close();if(blocker!=null)Destroy(blocker);if(music!=null){music.Stop();Destroy(music);}if(effect!=null){effect.Stop();Destroy(effect);}foreach(var c in clips.Values)if(c!=null)Destroy(c);clips.Clear();Time.timeScale=oldScale;Control.ToggleActionMap(true);Plugin.ReleaseExternal();if(Current==this)Current=null;Destroy(gameObject);}
  void OnDestroy(){if(!Closed)Close();}
 }
}
