using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using UnityEngine;using UnityEngine.UI;using UnityEngine.Networking;using UnityEngine.InputSystem;using StudentAge.CampusUno;using StudentAge.Sanguosha;using Sdk;
namespace StudentAge.CampusMinigames {
 public static class SanguoshaAssets {
  public static string Root=>Path.Combine(CampusResources.ContentRoot,"Sanguosha");static readonly Dictionary<string,Texture2D> images=new Dictionary<string,Texture2D>();static readonly Dictionary<string,Sprite> sprites=new Dictionary<string,Sprite>();
  public static Texture2D Image(string path){if(images.TryGetValue(path,out var t)&&t!=null)return t;string f=Path.Combine(Root,path);if(!File.Exists(f))return null;t=new Texture2D(2,2,TextureFormat.RGBA32,false);ImageConversion.LoadImage(t,File.ReadAllBytes(f));if(path.StartsWith("official/font/",StringComparison.Ordinal))t.Apply(false,true);t.filterMode=FilterMode.Bilinear;t.wrapMode=TextureWrapMode.Clamp;images[path]=t;return t;}
  public static Sprite Sprite(string id){if(sprites.TryGetValue(id,out var s)&&s!=null)return s;var t=Image(id=="social"?"official/social-kill.png":id=="box"?"back.png":"generals/"+id+".jpg");if(t==null)return null;s=UnityEngine.Sprite.Create(t,new Rect(0,0,t.width,t.height),new Vector2(.5f,.5f),100);sprites[id]=s;return s;}
 }
 public sealed partial class SanguoshaView:MonoBehaviour {
  public static SanguoshaView Current{get;private set;}public Match Engine{get;private set;}public SanguoshaSession Session{get;private set;}public bool Closed{get;private set;}public bool Paused{get;private set;}
  GameObject blocker;float oldScale,aiAt,eventAt,resultAt;int eventSeq,page,optionPage;bool easy=true,started,collection,settled,help;string selected="zhaoyun",inspect,notice="";Prompt shownPrompt;MatchEvent shownEvent;NativeMinigameAudio scope;AudioSource music,effect;readonly Dictionary<string,AudioClip> clips=new Dictionary<string,AudioClip>();Queue<MatchEvent> events=new Queue<MatchEvent>();GUIStyle label,small,button,title;Vector2 logScroll,detailScroll;
  public static bool Open(int npc){if(Current!=null||Plugin.IsBusy||!SanguoshaIntegration.Owned||(npc>0&&!SanguoshaIntegration.CanFight(npc)))return false;var obj=new GameObject("SanguoshaHost");var v=obj.AddComponent<SanguoshaView>();if(!Plugin.AcquireExternal(Invalidate)){Destroy(obj);return false;}Current=v;DontDestroyOnLoad(obj);try{v.collection=npc==0;if(npc>0)v.Session=new SanguoshaSession(npc);v.Build();return true;}catch{v.Close();throw;}}
  void Build(){oldScale=Time.timeScale;Time.timeScale=0;Control.ToggleActionMap(false);blocker=new GameObject("SanguoshaInputBlocker",typeof(RectTransform),typeof(Canvas),typeof(GraphicRaycaster));var canvas=blocker.GetComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;canvas.sortingOrder=32760;var back=new GameObject("ModalShield",typeof(RectTransform),typeof(Image));back.transform.SetParent(blocker.transform,false);var r=(RectTransform)back.transform;r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=r.offsetMax=Vector2.zero;back.GetComponent<Image>().color=Color.clear;
   scope=NativeMinigameAudio.Open(gameObject,0,true);music=gameObject.AddComponent<AudioSource>();music.playOnAwake=false;music.loop=true;music.volume=.48f;scope.UseLocalMusic(music);scope.SetMusicPaused(false);effect=gameObject.AddComponent<AudioSource>();effect.playOnAwake=false;scope.Bind(effect);BuildVoices();StartCoroutine(LoadSounds());}
  IEnumerator LoadSounds(){string dir=Path.Combine(SanguoshaAssets.Root,"audio");if(!Directory.Exists(dir)){soundsReady=true;yield break;}var files=Directory.GetFiles(dir,"*.ogg").OrderBy(f=>Path.GetFileNameWithoutExtension(f)=="background"?0:1).ToArray();
   // Bounded local batches avoid a frame of delay per voice when opening a new duel.
   for(int start=0;start<files.Length;start+=8){var requests=new List<UnityWebRequest>();try{
    for(int i=start;i<Math.Min(files.Length,start+8);i++){var r=UnityWebRequestMultimedia.GetAudioClip(new Uri(files[i]).AbsoluteUri,AudioFormat(files[i]));requests.Add(r);r.SendWebRequest();}
    while(requests.Any(r=>!r.isDone))yield return null;if(Closed)yield break;
    for(int i=0;i<requests.Count;i++){var r=requests[i];string key=Path.GetFileNameWithoutExtension(files[start+i]);if(r.result!=UnityWebRequest.Result.Success){Debug.LogWarning("[Sanguosha] Audio load failed: "+key);continue;}var clip=DownloadHandlerAudioClip.GetContent(r);clip.name=key;clips[key]=clip;if(key=="background"){music.clip=clip;if(!Paused&&!settled)music.Play();}}
   }finally{foreach(var r in requests)r.Dispose();}}
   // Decode large result sheets in selection, before their first visible animation frame.
   foreach(string key in new[]{"judgment-success","judgment-failure","judgment-reveal","first-blood","victory-text","victory-base","defeat-text","defeat-base","cardSkillHongSha","cardSkillHeiSha","cardSkillShan","general-unlock-start","general-unlock-loop"}){SanguoshaAssets.Image("official/effects/"+key+".png");yield return null;}
   string faces=Path.Combine(SanguoshaAssets.Root,"hd/faces");if(Directory.Exists(faces)){int n=0;foreach(var f in Directory.GetFiles(faces,"*.png")){SanguoshaAssets.Image("hd/faces/"+Path.GetFileName(f));if(++n%8==0)yield return null;}}
   SanguoshaAssets.Image("official/font/fzkt.png");
   foreach(string key in new[]{"selection-bg.png","getGeneralTitle.png"})SanguoshaAssets.Image("official/dialogs/"+key);
   soundsReady=true;
  }
  static AudioType AudioFormat(string path){using(var f=File.OpenRead(path)){byte[] head=new byte[4];f.Read(head,0,4);return head[0]==82&&head[1]==73&&head[2]==70&&head[3]==70?AudioType.WAV:head[0]==79&&head[1]==103&&head[2]==103&&head[3]==83?AudioType.OGGVORBIS:AudioType.MPEG;}}
  public bool AudioReady=>soundsReady;public int DecodedAudioCount=>clips.Count;public bool MusicPlaying=>music!=null&&music.isPlaying;
  public bool StartBattle(string general,bool simple){if(!soundsReady||started||Session==null||!HasGeneral(general)||!Session.Begin())return false;selected=general;easy=simple;started=true;BuildParticipants();Engine=new Match(selected,Session.Opponent,easy,Environment.TickCount);aiAt=Time.unscaledTime+.6f;Sound("game-start");return true;}
  public void SelectOption(int index){if(!DecisionReady||Engine.Pending==null||Engine.Pending.Actor!=0)return;Engine.Choose(index);ResetTableSelection();optionPage=0;aiAt=Time.unscaledTime+.55f;}
  void Update(){if(Closed)return;TickVoices();var k=Keyboard.current;if(k!=null&&k.escapeKey.wasPressedThisFrame){if(inspectedCard!=null){inspectedCard=null;return;}if(inspect!=null){inspect=null;return;}if(help){help=false;return;}if(!started){Close();return;}if(Engine.Winner==-2){Paused=!Paused;if(Paused){music.Pause();effect.Pause();voice.Pause();}else{music.UnPause();effect.UnPause();voice.UnPause();aiAt=Time.unscaledTime+.5f;}return;}}
   if(Session!=null&&!settled&&!Session.Valid){Close();return;}if(Engine==null||Paused||help||inspect!=null||inspectedCard!=null)return;tableClock+=Time.unscaledDeltaTime;if(k!=null&&k.f6Key.wasPressedThisFrame&&Engine.Winner==-2)Engine.Surrender(1);
   foreach(var ev in Engine.Events.Where(e=>e.Sequence>eventSeq)){events.Enqueue(ev);eventSeq=ev.Sequence;}
   if(events.Count>0&&!JudgmentHolding&&!MovementHolding&&Time.unscaledTime-eventAt>.22f){shownEvent=events.Dequeue();eventAt=Time.unscaledTime;RecordTableEvent(shownEvent);Sound(shownEvent.Sound,shownEvent.Actor);}
   if(Engine.Pending!=shownPrompt){shownPrompt=Engine.Pending;ResetTableSelection();}
   if(Engine.Pending?.Actor==1&&Time.unscaledTime>=aiAt&&events.Count==0&&!JudgmentHolding&&!MovementHolding&&VoicesIdle&&Time.unscaledTime-eventAt>.4f){Engine.Choose(Engine.AiChoice());aiAt=Time.unscaledTime+.4f;}
   if(Engine.Winner!=-2&&!settled){settled=true;bool ok=Session.Finish(Engine.Winner==0,Engine.Winner==1);resultAt=float.PositiveInfinity;scope.FadeMusicPaused(true,.5f);notice=ok?(Engine.Winner==0?"胜利":"下回合再战")+" · 好感 +"+Session.Favor.ToString("0.#"):"牌局已结束";StartCoroutine(ResultSound());}}
  void Styles(){if(label!=null)return;Font font=NativeSkin.TitleFont;label=new GUIStyle(GUI.skin.label){font=font,fontSize=23,wordWrap=true,alignment=TextAnchor.MiddleLeft,richText=false,normal={textColor=new Color(.92f,.87f,.75f)}};small=new GUIStyle(label){fontSize=18};title=new GUIStyle(label){fontSize=42,alignment=TextAnchor.MiddleCenter};button=new GUIStyle(GUI.skin.button){font=font,fontSize=21,wordWrap=true,normal={textColor=new Color(.96f,.9f,.7f)},hover={textColor=Color.white}};}
  static void Rect(Rect r,Color c){var old=GUI.color;GUI.color=c;GUI.DrawTexture(r,Texture2D.whiteTexture);GUI.color=old;}
  void Frame(Rect r){Panel(r,1);}
  void Text(string s,float x,float y,float w,float h,GUIStyle style=null)=>GUI.Label(new Rect(x,y,w,h),s,style??label);
  bool Btn(string text,float x,float y,float w,float h,bool enabled=true){TableStyles();return TableButton(text,new Rect(x,y,w,h),enabled);}
  void Picture(string path,Rect r,bool dim=false){var t=SanguoshaAssets.Image(path);if(t==null)return;Color prev=GUI.color;if(dim)GUI.color=new Color(.32f,.32f,.32f,1);GUI.DrawTexture(r,t,ScaleMode.ScaleToFit);GUI.color=prev;}
  void OnGUI(){if(Closed)return;if(Event.current.type==EventType.Repaint)cardLayerIndex=0;if(!BoardInputAllowed)CancelDrag();GUI.depth=-32000;Styles();var old=GUI.matrix;float scale=Math.Min(Screen.width/1600f,Screen.height/900f);GUI.matrix=Matrix4x4.TRS(new Vector3((Screen.width-1600*scale)/2,(Screen.height-900*scale)/2,0),Quaternion.identity,new Vector3(scale,scale,1));Rect(new Rect(-4000,-4000,10000,10000),Color.black);TableBackdrop();
   GUI.enabled=inspect==null&&inspectedCard==null&&!help&&!Paused;if(testDirectory)TestPeople();else if(!started)Collection();else Board();GUI.enabled=true;if(inspectedCard!=null)CardDetail();else if(inspect!=null)Detail();else if(help)Help();else if(Paused)PauseMenu();GUI.matrix=old;}
  void Collection(){Frame(new Rect(35,30,1530,840));Text(collection?"三国杀 · 武将卡册":"三国杀 · 择将应战",400,45,800,60,title);if(Btn("返回",65,55,140,45))Close();if(Btn("规则",1390,55,130,45))help=true;
   var owned=Catalog.Generals.Count(g=>HasGeneral(g.Id));Text("已收藏 "+owned+" / 35",70,113,330,40);if(Session!=null)Text(Session.Name+" · 第"+(Session.Stage+1)+"关  · 对阵 "+Catalog.Get(Session.Opponent).Name,570,113,900,40);else Text("点击武将查看技能与获取方式",570,113,900,40);
   for(int i=0;i<14;i++){int idx=page*14+i;if(idx>=Catalog.Generals.Length)break;var g=Catalog.Generals[idx];float x=85+(i%7)*205,y=180+(i/7)*253;bool has=HasGeneral(g.Id);if(selected==g.Id&&!collection)Rect(new Rect(x-5,y-5,160,231),new Color(.9f,.69f,.2f));Picture("generals/"+g.Id+".jpg",new Rect(x,y,150,218),!has);if(GUI.Button(new Rect(x,y,150,218),GUIContent.none,GUIStyle.none)){if(has&&!collection)selected=g.Id;else inspect=g.Id;}Text(g.Name+(has?"":" · 未收集"),x-5,y+217,180,30,small);if(!collection&&has&&Btn("技能",x+155,y+158,43,56))inspect=g.Id;}
   if(Btn("上一页",65,735,160,44,page>0))page--;Text((page+1)+" / 3",240,735,120,44);if(Btn("下一页",350,735,160,44,page<2))page++;
   if(!collection){if(Btn(easy?"● 简单":"○ 简单",580,731,175,47))easy=true;if(Btn(!easy?"● 复杂":"○ 复杂",767,731,175,47))easy=false;Text(easy?"双方：每回合两杀 · 摸三张 · 体力上限+1":"双方：每回合一杀 · 摸两张 · 原始体力",580,786,620,45,small);if(Btn("开始对战",1240,747,240,64,soundsReady))StartBattle(selected,easy);}else Text("赢得角色关卡可收集武将。其余卡牌在小卖铺购买。",580,755,900,50);}
  void Result(){if(Session.NewReward){DrawGeneralReward();return;}DrawResultEmblem(1);if(Btn("返回",680,720,240,52,Time.unscaledTime-resultAt>.4f))CompleteResult();}
  void Detail(){Rect(new Rect(0,0,1600,900),new Color(0,0,0,.82f));Frame(new Rect(275,65,1050,770));var g=Catalog.Get(inspect);Picture("generals/"+g.Id+".jpg",new Rect(320,115,400,580));Text(g.Name+" · "+g.Kingdom,775,125,490,75,title);Text("原始体力 "+g.Hp,800,213,450,45);detailScroll=GUI.BeginScrollView(new Rect(775,280,475,310),detailScroll,new Rect(0,0,440,Math.Max(300,label.CalcHeight(new GUIContent(g.Description),420))));Text(g.Description,10,0,420,Math.Max(300,label.CalcHeight(new GUIContent(g.Description),420)));GUI.EndScrollView();Text(HasGeneral(g.Id)?"已收藏":g.Id=="zhaoyun"?"购买三国杀赠送":Encounters.Sold(g.Id)?"小卖铺 · "+Encounters.Price(g.Id)+"元":"角色对战胜利奖励",785,617,450,60);if(Btn("返回牌桌",800,735,340,60))inspect=null;}
  void Help(){Rect(new Rect(0,0,1600,900),new Color(0,0,0,.84f));Frame(new Rect(245,100,1110,710));Text("三国杀 · 单挑规则",450,115,700,70,title);Picture("cards/slash.png",new Rect(290,250,140,203));Picture("cards/jink.png",new Rect(450,250,140,203));Picture("cards/peach.png",new Rect(610,250,140,203));Text("杀 → 对手出闪抵消\n桃 → 回复一点体力\n锦囊 → 依牌面结算，可用无懈可击响应",810,255,480,220);Text("准备 → 判定 → 摸牌 → 出牌 → 弃牌 → 结束\n复杂模式：摸2张、通常限出1杀；简单模式：摸3张、限出2杀、双方体力上限+1。\n牌局使用旧标准与旧风包技能。单挑没有主公技和第三方目标；离间、流离因此不能发动。\n长按手牌拖出箭头：杀和单体锦囊拖向对手，桃、装备拖向自己，群体锦囊拖到场中。闪和无懈拖到正在结算的牌上；空处松手或拖回手牌取消。选牌环节直接点牌，右键查看，Esc 暂停。",290,490,1000,240);if(Btn("继续",1080,735,215,50))help=false;}
  void PauseMenu(){Rect(new Rect(0,0,1600,900),new Color(0,0,0,.8f));Frame(new Rect(535,225,530,415));Text("三国杀 · 暂停",575,255,450,65,title);if(Btn("继续对战",625,365,350,65)){Paused=false;music.UnPause();effect.UnPause();voice.UnPause();}if(Btn("认输并收起牌桌",625,455,350,65)){Paused=false;music.UnPause();effect.UnPause();voice.UnPause();Engine.Surrender(0);}Text("认输仍获得10好感，下回合才能再战。",565,551,475,50,small);}
  public static void Invalidate(){if(Current!=null)Current.Close();}
  public void Close(){if(Closed)return;Closed=true;DisposeParticipants();DisposeTableArt();StopAllCoroutines();if(scope!=null)scope.Close();if(blocker!=null)Destroy(blocker);if(music!=null){music.Stop();Destroy(music);}if(effect!=null){effect.Stop();Destroy(effect);}DisposeVoices();foreach(var c in clips.Values)if(c!=null)Destroy(c);clips.Clear();Time.timeScale=oldScale;Control.ToggleActionMap(true);Plugin.ReleaseExternal();if(Current==this)Current=null;Destroy(gameObject);}
  void OnDestroy(){if(!Closed)Close();}
 }
}
