using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using BepInEx;using Config;using HarmonyLib;using Newtonsoft.Json;using Sdk;using UnityEngine;using StudentAge.CampusUno;using StudentAge.Sanguosha;using GenUI.Main;using GenUI.Shop;
namespace StudentAge.CampusMinigames {
 public static class SanguoshaIntegration {
  public const int BoxId=920000,TabId=920090,OptionId=920091;const string Record="studio.studentage.sanguosha.progress.v1";
  public static bool Owned=>Singleton<BagMgr>.Ins.HasEnoughItem(BoxId);public static bool OnSale=>Singleton<RoundMgr>.Ins.GetYear()>=2003;
  public static int CardId(string id)=>BoxId+1+Array.FindIndex(Catalog.Generals,g=>g.Id==id);
  public static bool Has(string id)=>Singleton<BagMgr>.Ins.HasEnoughItem(CardId(id));
  public static bool IsItem(int id)=>id>=BoxId&&id<=BoxId+35;
  public static float Price(int id)=>id==BoxId?10:Encounters.Price(Catalog.Generals[id-BoxId-1].Id);
  public static Progress Read(){string json=Singleton<CommonEvtMgr>.Ins.GetRecordTag(Record);if(string.IsNullOrEmpty(json))return new Progress();var value=JsonConvert.DeserializeObject<Progress>(json);if(value==null||value.Schema!=1||value.Wins==null)throw new InvalidOperationException("三国杀存档记录格式不兼容");return value;}
  public static void Write(Progress data)=>Singleton<CommonEvtMgr>.Ins.AddRecordTag(Record,JsonConvert.SerializeObject(data));
  public static bool CanFight(int npc){if(!Owned||Plugin.IsBusy)return false;var role=Singleton<RoleMgr>.Ins.GetRole(npc);return role!=null&&!role.isLeave&&(role.Relation!=0||role.unFocusCnt>0)&&Read().CanBegin(npc,Singleton<RoundMgr>.Ins.GetRound());}
  public static bool CanBuy(int id){if(!IsItem(id)||!Register()||!OnSale)return false;if(id==BoxId)return !Owned;var g=Catalog.Generals[id-BoxId-1];return Owned&&IsShopGeneral(g.Id)&&!Has(g.Id);}
  public static bool IsShopGeneral(string id){if(id=="zhaoyun")return false;if(Encounters.Sold(id))return true;bool dlc=Sdk.PlatformAPI.Platform.Current.HasDLC(0);var reachable=Cfg.PersonCfgMap.Values.Where(p=>p.init!=null&&p.init.Count>0&&p.init[0]>1&&(dlc||(p.id!=103&&p.id!=204))).SelectMany(p=>Encounters.For(p.id));return !reachable.Contains(id);}
  public static bool Register(){if(Cfg.ItemCfgMap==null||Cfg.ShopCfgMap==null||Cfg.ItemTypeCfgMap==null||Cfg.ActionCfgMap==null||!Cfg.ItemCfgMap.ContainsKey(9032)||!Cfg.ItemTypeCfgMap.ContainsKey(4))return false;
   for(int i=-1;i<35;i++){int id=BoxId+i+1;var g=i<0?null:Catalog.Generals[i];if(!Cfg.ItemCfgMap.ContainsKey(id)){Cfg.ItemCfgMap[id]=new ItemCfg{id=id,name=g==null?"三国杀":g.Name+"·武将卡",desc=g==null?"课桌一角，也能摆开三国的千军万马。拆开盒子，先从一位常胜将军开始。":g.Description,icon="sanguosha/"+(g==null?"box":g.Id),type=4,maxcount=1,rarity=g?.Kingdom=="神"?3:1,itemTag=new List<int>{2},sell=-1,value=Price(id),effect=g==null?new List<List<float>>{new List<float>{1,11,0,3}}:new List<List<float>>(),usingEffect=new List<List<float>>(),precondition=new List<List<double>>()};}
    if(!Cfg.ShopCfgMap.ContainsKey(id))Cfg.ShopCfgMap[id]=new ShopCfg{id=id,group=id,price=Price(id),time=2003,type=4,maxcount=1,limcount=1,probability=1,precondition=new List<List<double>>(),buyTalk=g==null?"刚到的三国杀，找朋友一起玩吧！":"这张武将卡收好，牌桌上可有大用处。"};}
   if(!Cfg.ItemTypeCfgMap.ContainsKey(TabId)){var tab=JsonConvert.DeserializeObject<ItemTypeCfg>(JsonConvert.SerializeObject(Cfg.ItemTypeCfgMap[4]));tab.id=TabId;tab.name="三国杀";tab.shop=4;tab.bag=tab.book=tab.market=0;tab.icon="sanguosha/box";Cfg.ItemTypeCfgMap[TabId]=tab;}
   if(!Cfg.ActionCfgMap.ContainsKey(BoxId))Cfg.ActionCfgMap[BoxId]=new ActionCfg{id=BoxId,name="三国杀卡册",type=2,map=1,funcId=BoxId,icon="sanguosha/box",attrs=new List<string>(),expReward=new List<List<float>>(),beginTime=new List<float>(),endTime=new List<float>(),interactable=new List<List<double>>(),cost=new List<List<float>>(),unlock=new List<List<double>>(),effect=new List<List<float>>()};return true;
  }
  public static void Restore(){if(!Register()||!Owned)return;if(!Has("zhaoyun"))Singleton<BagMgr>.Ins.AddItem(CardId("zhaoyun"),1L,"三国杀初始武将");var item=Singleton<BagMgr>.Ins.GetBagData(4,BoxId) as ItemData;if(item!=null&&item.equipEffector==null){item.equipEffector=CommonEvtMgr.GenEffector(Cfg.ItemCfgMap[BoxId].effect);item.equipEffector.SetTag("三国杀");item.equipEffector.SetIsInc(true);item.equipEffector.Run();item.effectUids=item.equipEffector.GetBaseIncreaserUids();}}
  public static void SyncAction(ActionData data){if(!Register())return;var action=data.GetAction(BoxId);if(Owned&&action==null)data.AddAction(BoxId);else if(!Owned&&action!=null)data.DelAction(BoxId);}
 }
 public sealed class SanguoshaSession {
  public readonly int NpcId,Round,Stage;public readonly string Opponent;readonly TheEntity.Role player,npc;bool began,settled;
  public string Name=>npc.Name;public string Reward{get;private set;}public float Favor{get;private set;}
  public SanguoshaSession(int id){NpcId=id;player=Singleton<RoleMgr>.Ins.GetRole();npc=Singleton<RoleMgr>.Ins.GetRole(id);Round=Singleton<RoundMgr>.Ins.GetRound();Stage=SanguoshaIntegration.Read().Stage(id);Opponent=Encounters.For(id)[Math.Min(2,Stage)];}
  public bool Valid=>!settled&&ReferenceEquals(player,Singleton<RoleMgr>.Ins.GetRole())&&ReferenceEquals(npc,Singleton<RoleMgr>.Ins.GetRole(NpcId))&&Round==Singleton<RoundMgr>.Ins.GetRound()&&SanguoshaIntegration.Owned;
  public bool Begin(){if(began||!Valid)return false;var p=SanguoshaIntegration.Read();if(p.Stage(NpcId)!=Stage||!p.Reserve(NpcId,Round))return false;SanguoshaIntegration.Write(p);began=true;return true;}
  public bool Finish(bool win){if(!began||!Valid)return false;settled=true;var p=SanguoshaIntegration.Read();if(p.LastRound!=Round||p.Stage(NpcId)!=Stage)return false;if(win){Reward=Encounters.For(NpcId)[Stage];if(!SanguoshaIntegration.Has(Reward)&&!Singleton<BagMgr>.Ins.AddItem(SanguoshaIntegration.CardId(Reward),1L,"三国杀对战获胜"))throw new InvalidOperationException("武将卡未能收入背包");p.CompleteWin(NpcId);}SanguoshaIntegration.Write(p);Favor=npc.UpdateFavor(10f,1f-npc.GetFavorEfficiency(),"打三国杀");EventMgr.Send(1603);return true;}
 }
 [HarmonyPatch(typeof(BagMgr),"Load")]static class SgsBeforeLoad{static void Prefix(){SanguoshaIntegration.Register();}}
 [HarmonyPatch(typeof(BagMgr),"LoadEnd")]static class SgsAfterLoad{static void Postfix(){SanguoshaIntegration.Restore();}}
 [HarmonyPatch(typeof(BagMgr),"AddItem")]static class SgsBought{static void Postfix(int _id,bool __result){if(__result&&_id==SanguoshaIntegration.BoxId){SanguoshaIntegration.Restore();SanguoshaIntegration.SyncAction(Singleton<RoleMgr>.Ins.GetActionData());}}}
 [HarmonyPatch(typeof(ActionData),"GetActions")]static class SgsActions{static void Prefix(ActionData __instance){SanguoshaIntegration.SyncAction(__instance);}}
 [HarmonyPatch(typeof(FuncMgr),"OpenFuncView")]static class SgsCollection{static bool Prefix(int _funcId){if(_funcId!=SanguoshaIntegration.BoxId)return true;if(SanguoshaIntegration.Owned)SanguoshaView.Open(0);return false;}}
 [HarmonyPatch(typeof(ShopMgr),"GetShopDatas")]static class SgsShopList{static void Postfix(int _type,int _minCnt,ref List<ShopData> __result){if(!SanguoshaIntegration.Register())return;__result.RemoveAll(v=>SanguoshaIntegration.IsItem(v.id));if(_minCnt>1)return;foreach(int id in Enumerable.Range(SanguoshaIntegration.BoxId,36)){bool category=id==SanguoshaIntegration.BoxId?(_type==4||_type==100||_type==SanguoshaIntegration.TabId):_type==SanguoshaIntegration.TabId;if(!category||!SanguoshaIntegration.CanBuy(id))continue;var data=new ShopData{id=id,type=4,quality=1,cnt=1,showInThisYear=true,canBargin=false,isNew=true};data.RefreshPrize();__result.Add(data);}}}
 [HarmonyPatch(typeof(ShopData),"get_Prize")]static class SgsPrice{static void Postfix(ShopData __instance,ref float __result){if(SanguoshaIntegration.IsItem(__instance.id))__result=SanguoshaIntegration.Price(__instance.id);}}
 [HarmonyPatch(typeof(ShopData),"get_FinalPrize")]static class SgsFinalPrice{static void Postfix(ShopData __instance,ref float __result){if(SanguoshaIntegration.IsItem(__instance.id))__result=SanguoshaIntegration.Price(__instance.id);}}
 [HarmonyPatch(typeof(ShopMgr),"Buy",new Type[]{typeof(ShopData),typeof(float)})]static class SgsBuy{static bool Prefix(ShopData _shopData,ref float _discount,ref bool __result){if(!SanguoshaIntegration.IsItem(_shopData.id))return true;_discount=1;if(SanguoshaIntegration.CanBuy(_shopData.id))return true;__result=false;return false;}}
 [HarmonyPatch(typeof(ShopMgr),"Buy",new Type[]{typeof(int)})]static class SgsBuyId{static bool Prefix(int _shopId,ref bool __result){if(!SanguoshaIntegration.IsItem(_shopId)||SanguoshaIntegration.CanBuy(_shopId))return true;__result=false;return false;}}
 [HarmonyPatch(typeof(View.Shop.ShopView),"InitUI")]static class SgsShopTab{static void Postfix(View.Shop.ShopView __instance){SanguoshaIntegration.Register();if(__instance.togCells.Count>=4)return;var source=__instance.togCells.Last();var obj=UnityEngine.Object.Instantiate(source.gameObject,__instance.group_tog);obj.name="SanguoshaShopTab";var cell=new Cell_ActionTogUI(obj);__instance.togCells.Add(cell);AccessTools.Method(typeof(View.Shop.ShopView),"OnTogCreate").Invoke(__instance,new object[]{cell});var r=obj.transform as RectTransform;r.SetParent(__instance.group_shop,false);r.anchorMin=r.anchorMax=new Vector2(.5f,1);r.pivot=new Vector2(.5f,.5f);r.localScale=Vector3.one*.85f;r.anchoredPosition=new Vector2(100,64);}}
 // Rebuild the existing option group, reusing its original pooled cell prefab and render/create handlers.
 [HarmonyPatch(typeof(View.Main.MapRoleView),"RefreshData")]static class SgsSocialList{static void Postfix(View.Main.MapRoleView __instance,int ___npcId){if(!SanguoshaIntegration.Owned||SanguoshaIntegration.Read().Stage(___npcId)>=3)return;var cells=__instance.itemgroup_option.GetCells().Where(c=>c.gameObject.activeSelf).OrderBy(c=>c.transform.GetSiblingIndex()).ToArray();var ids=cells.Select(c=>(int)c.data).Where(id=>id!=SanguoshaIntegration.OptionId).ToList();if(!ids.Contains(301)&&!ids.Contains(304))return;int at=ids.IndexOf(-1);ids.Insert(at<0?ids.Count:at,SanguoshaIntegration.OptionId);__instance.itemgroup_option.SetUICellDatas(ids,id=>id==304?1:id==302?2:id==306?3:id==-1?4:0);}}
 [HarmonyPatch(typeof(View.Main.MapRoleView),"OnCellRender")]static class SgsSocialRender{static bool Prefix(UICell _cell,int ___npcId){if(!(_cell.data is int id)||id!=SanguoshaIntegration.OptionId)return true;var c=(Cell_RoleOptionItemUI)_cell;c.txt_name.text="打三国杀";c.txtex_cost.gameObject.SetActive(false);c.icon_item.gameObject.SetActive(false);c.btn_click.interactable=SanguoshaIntegration.CanFight(___npcId);return false;}}
 [HarmonyPatch(typeof(View.Main.MapRoleView),"OnCellCreate")]static class SgsSocialCreate{static void Postfix(View.Main.MapRoleView __instance,UICell _cell){if(!(_cell is Cell_RoleOptionItemUI c))return;c.btn_click.btn.onClick.AddListener(()=>{if(_cell.data is int id&&id==SanguoshaIntegration.OptionId){int npc=(int)AccessTools.Field(typeof(View.Main.MapRoleView),"npcId").GetValue(__instance);if(SanguoshaView.Open(npc))__instance.CloseView();}});}}
 [HarmonyPatch]static class SgsInvalidate{static IEnumerable<MethodBase> TargetMethods(){yield return AccessTools.Method(typeof(Game),"LoadGame");yield return AccessTools.Method(typeof(Game),"NewGame");yield return AccessTools.Method(typeof(Game),"BackToMain");}[HarmonyPriority(Priority.First)]static void Prefix(){SanguoshaView.Invalidate();}}
 [HarmonyPatch(typeof(UISprite),"SetAtlasUrl")]static class SgsAtlasArt{static bool Prefix(UISprite __instance,string _url){if(_url==null||!_url.StartsWith("sanguosha/",StringComparison.Ordinal))return true;string id=_url.Substring(10);if(id!="box"&&!Catalog.Generals.Any(g=>g.Id==id))return true;__instance.SetSprite(SanguoshaAssets.Sprite(id));return false;}}
 [HarmonyPatch(typeof(ResMgr),"LoadSpriteAsync")]static class SgsItemArt{static bool Prefix(string _path,Action<Sprite> _compCallback){if(_path==null)return true;string p=_path.Replace('\\','/');int at=p.IndexOf("sanguosha/",StringComparison.Ordinal);if(at<0)return true;string id=Path.GetFileNameWithoutExtension(p.Substring(at+10));if(id!="box"&&!Catalog.Generals.Any(g=>g.Id==id))return true;_compCallback?.Invoke(SanguoshaAssets.Sprite(id));return false;}}
}
