using System;using System.Collections;using System.Collections.Generic;using System.IO;using System.Linq;
using StudentAge.PlayingCards;using StudentAge.CampusPuzzles;using UnityEngine;using UnityEngine.UI;
namespace StudentAge.CampusMinigames
{
    public sealed class TwentyFourView:PuzzleFrame
    {
        public TwentyFourGame Engine{get;private set;}public bool ReadyForInput=>Started&&!busy&&!Ending;
        CardArt art;RectTransform numbers;Text expression,progress,feedback,timer;Button submit;readonly List<PlayingCardView> cards=new List<PlayingCardView>();int selected=-1;char operation='+';bool busy;readonly Dictionary<char,Button> operations=new Dictionary<char,Button>();
        protected override string Title=>"算24点";
        protected override string[] Rules=>new[]{"四张牌各用一次，算出24。A算1，使用A至10。","先选一个数，再选运算符，最后选另一个数。","两数会合成新数；减法、除法按点击顺序计算。","每次合并都相当于括号，可以使用分数和负数。","每题限时"+Engine.TimeLimit+"秒，答对"+Engine.RequiredAnswers+"题获胜。","可以无限撤销或重算；结果为24才能交卷。"};
        protected override IEnumerator LoadAssets(){art=new CardArt(Path.Combine(Session.Root,"PlayingCards"));var back=art.Back;Engine=new TwentyFourGame(Level,Environment.TickCount);yield break;}
        protected override void BuildPlay(){Paper(PlayRoot,255,155,1090,590);progress=T(PlayRoot,"",515,110,570,45,28);numbers=R(PlayRoot,"Numbers",355,235,890,310);for(int i=0;i<3;i++){var back=PlayingCardView.Create(PlayRoot,art,new PlayingCard(CardSuit.Spades,1),1355+i*3,267-i*3,140,true);back.Interactable=false;}expression=T(PlayRoot,"",355,542,890,61,32);feedback=T(PlayRoot,"",420,174,760,48,30);int n=0;foreach(char op in "+-*/"){char key=op;var b=B(PlayRoot,op=='*'?"×":op=='/'?"÷":op.ToString(),469+n++*158,636,128,77,()=>ChooseOperation(key),true);operations.Add(op,b);}B(PlayRoot,"撤销",280,780,210,73,()=>{if(!ReadyForInput)return;Engine.Undo();selected=-1;DrawNumbers(false);});B(PlayRoot,"重算",535,780,210,73,()=>{if(!ReadyForInput)return;Engine.Reset();selected=-1;DrawNumbers(false);});submit=B(PlayRoot,"交卷",1000,780,280,73,Submit);timer=T(PlayRoot,"02:00",1270,110,250,48,32);}
        protected override void StartGame(){DrawNumbers(true);}
        void ChooseOperation(char op){if(!ReadyForInput)return;operation=op;RefreshOperation();}
        void RefreshOperation(){foreach(var pair in operations)pair.Value.GetComponent<Image>().color=pair.Key==operation?new Color(1,.86f,.60f):Color.white;if(selected>=0&&selected<Engine.Tokens.Count)feedback.text=Engine.Tokens[selected].Value.ToString()+"  "+(operation=='*'?"×":operation=='/'?"÷":operation.ToString())+"  …";}
        void DrawNumbers(bool deal){Clear(numbers);cards.Clear();selected=-1;progress.text="答对 "+Engine.Solved+" / "+Engine.RequiredAnswers;submit.interactable=Engine.QuestionSolved;expression.text=Engine.Tokens.Count==1?Engine.Tokens[0].Expression+" = "+Engine.Tokens[0].Value:"";feedback.text="";float total=Engine.Tokens.Count*190+(Engine.Tokens.Count-1)*24,offset=(890-total)/2;
            for(int i=0;i<Engine.Tokens.Count;i++){int index=i;var token=Engine.Tokens[i];if((token.Mask&(token.Mask-1))==0){int id=0;while((1<<id)!=token.Mask)id++;var card=PlayingCardView.Create(numbers,art,Engine.Cards[id],offset+i*214,0,190,deal);card.Clicked=v=>Pick(index);cards.Add(card);if(deal)card.MoveFrom(new Vector2(1070,-130),i*.10f,.4f,-14);}else{var p=Paper(numbers,offset+i*214,30,190,230);var b=p.gameObject.AddComponent<Button>();p.raycastTarget=true;b.onClick.AddListener(()=>Pick(index));T(p.transform,token.Value.ToString(),5,65,180,70,42);T(p.transform,token.Expression,8,148,174,50,20,true);}}
            if(deal)StartCoroutine(Deal());RefreshOperation();
        }
        IEnumerator Deal(){busy=true;yield return new StudentAge.CampusUno.PlayDelay(.75f);foreach(var card in cards){card.Flip(false);Sfx("paper",.23f);yield return new StudentAge.CampusUno.PlayDelay(.08f);}yield return new StudentAge.CampusUno.PlayDelay(.4f);busy=false;}
        public void Pick(int index){if(!ReadyForInput||index<0||index>=Engine.Tokens.Count)return;if(selected<0){selected=index;feedback.text=Engine.Tokens[index].Value.ToString()+"  "+(operation=='*'?"×":operation=='/'?"÷":operation.ToString())+"  …";foreach(var card in cards)card.Select(Engine.Tokens[index].Mask==(1<<Array.FindIndex(Engine.Cards,c=>c.Equals(card.Card))));return;}if(index==selected){selected=-1;feedback.text="";foreach(var card in cards)card.Select(false);return;}if(!Engine.Combine(selected,index,operation)){feedback.text="不能除以0";selected=-1;return;}Sfx("place-1",.3f);DrawNumbers(false);}
        public void Submit(){if(!ReadyForInput||!Engine.QuestionSolved)return;bool correct=Engine.Submit();Sfx(correct?"pickup":"undo",.3f);if(Engine.Won||Engine.Lost){busy=true;feedback.text=correct?"答对了！":"下次再试";StartCoroutine(EndAfterPause(correct));return;}if(correct){busy=true;feedback.text="答对了！";StartCoroutine(Next());}else{DrawNumbers(false);feedback.text="还不是24，再试试";}}
        IEnumerator Next(){yield return new StudentAge.CampusUno.PlayDelay(.8f);Engine.NewQuestion();busy=false;DrawNumbers(true);}IEnumerator EndAfterPause(bool win){yield return new StudentAge.CampusUno.PlayDelay(.8f);Finish(win);}
        protected override void Tick(){if(ReadyForInput)Engine.Tick(StudentAge.CampusUno.PlayClock.Delta);int seconds=(int)Math.Ceiling(Engine.Remaining);timer.text=(seconds/60).ToString("00")+":"+(seconds%60).ToString("00");timer.color=seconds<=20?new Color(.75f,.18f,.1f):Ink;submit.interactable=ReadyForInput&&Engine.QuestionSolved;if(Engine.Lost){busy=true;Finish(false);}}
        protected override void OnDestroy(){base.OnDestroy();art?.Dispose();}
    }
}
