using System;using System.Linq;using System.Collections.Generic;using StudentAge.PlayingCards;using StudentAge.CampusPuzzles;
class Program
{
 static int checks;static void Check(bool ok,string name){if(!ok)throw new Exception(name);checks++;}
 static void Main(){
 var deck=new PlayingDeck(17);var hands=deck.Deal(3,17);Check(deck.Remaining==3,"landlord deal retains three bottom cards");var all=hands.SelectMany(h=>h).Concat(Enumerable.Range(0,3).Select(_=>deck.Draw())).ToArray();Check(all.Length==54&&all.Select(c=>c.Id).Distinct().Count()==54,"54 unique identities including jokers");deck.DiscardFrom(hands[0],0);Check(deck.Discarded.Count==1&&hands[0].Count==16,"shared hand and discard movement");var a=new PlayingDeck(20,false);var b=new PlayingDeck(20,false);Check(Enumerable.Range(0,52).All(_=>a.Draw().Equals(b.Draw())),"seeded Fisher Yates");bool empty=false;try{a.Draw();}catch(InvalidOperationException){empty=true;}Check(empty,"empty stock is explicit");
 Check(Fraction.Apply(new Fraction(1),new Fraction(3),'/').Equals(new Fraction(1,3)),"exact thirds");Check(Fraction.Apply(new Fraction(6),new Fraction(1,4),'/').Equals(new Fraction(24)),"fractional route to 24");Check(Fraction.Apply(new Fraction(1),new Fraction(5),'-').Equals(new Fraction(-4)),"negative intermediates");
 var bank=(int[][][])typeof(TwentyFourGame).GetField("Questions",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Static).GetValue(null);foreach(var tier in bank)foreach(var q in tier)Check(TwentyFourGame.Solve(q)!=null,"solvable question "+string.Join(",",q));
 Check(bank[0].All(q=>q.Sum()!=24),"first tier requires more than adding all cards");for(int level=1;level<=5;level++){var game=new TwentyFourGame(level,1);Check(game.Deck.Remaining==48,"24 draws four cards from shared stock");Check(game.Cards.Select(c=>c.Id).Distinct().Count()==4&&game.Cards.All(c=>c.Rank<=10),"real distinct A-10 cards");}
 var calc=new TwentyFourGame(1,3);calc.Combine(0,1,'+');Check(calc.Tokens.Count==3&&calc.Tokens.Select(x=>x.Mask).Aggregate(0,(x,y)=>x|y)==15,"combine retains all four source cards");calc.Undo();Check(calc.Tokens.Count==4,"undo restores exact tokens");calc.Tokens.Clear();calc.Tokens.Add(new CalcToken(new Fraction(24),"fixture",15));Check(calc.Submit()&&calc.Solved==1,"first solved question");Check(!calc.Submit()&&calc.Solved==1,"duplicate submission blocked");calc.NewQuestion();Check(calc.Tokens.Count==4,"next question resets expression");
 for(int n=0;n<3;n++)calc.Combine(0,1,'*');Check(!calc.Submit()&&calc.Mistakes==0&&calc.Tokens.Count==1,"wrong complete expression does not spend a chance or submit");
 for(int level=1;level<=5;level++){var boxes=new BoxGame(level,8);for(int round=0;round<3;round++){boxes.NextRound();Check(boxes.Swaps.Count==new[]{3,4,5,7,9}[level-1],"box difficulty swap count");foreach(var swap in boxes.Swaps)boxes.Swap(swap[0],swap[1]);Check(boxes.Items.OrderBy(x=>x).SequenceEqual(new[]{0,1,2,3}),"swaps preserve objects");boxes.Pick(Array.IndexOf(boxes.Items,boxes.Target));}Check(boxes.Won,"three correct boxes finish");}
 var loss=new BoxGame(1,2);for(int i=0;i<3;i++){loss.NextRound();loss.Pick(Array.FindIndex(loss.Items,x=>x!=loss.Target));}Check(loss.Finished&&!loss.Won,"box mistakes produce loss");
 calc.Reset();calc.Tick(119);Check(!calc.Lost&&calc.Remaining==1,"timer allows full two minutes");calc.Reset();Check(calc.Remaining==1,"reset cannot refill timer");calc.Tick(1);Check(calc.Lost&&!calc.Submit(),"two minute timeout fails and prevents submit");
 var blocks=new FallingBlocksGame(1,7);Check(blocks.Next.Length==3&&blocks.Target==4,"beginner target and preview");for(int n=0;n<20;n++)blocks.Move(-1);Check(!blocks.Move(-1)&&blocks.Fits(blocks.X,blocks.Y,blocks.Rotation),"wall collision");for(int i=0;i<4;i++)blocks.Rotate();Check(blocks.Fits(blocks.X,blocks.Y,blocks.Rotation),"wall rotation remains valid");Check(blocks.GhostY>=blocks.Y,"drop projection");blocks.HardDrop();Check(blocks.Locked==1&&blocks.Board.Count(x=>x!=0)==4,"hard drop places exactly four cells");
 // Set up one empty bottom-row cavity matching a horizontal I, then use the real drop/clear path.
 var clear=new FallingBlocksGame(1,12);typeof(FallingBlocksGame).GetProperty("Piece").SetValue(clear,0);typeof(FallingBlocksGame).GetProperty("Rotation").SetValue(clear,0);typeof(FallingBlocksGame).GetProperty("X").SetValue(clear,3);for(int x=0;x<10;x++)if(x<3||x>6)clear.Board[190+x]=1;clear.HardDrop();Check(clear.Lines==1&&clear.Board.All(x=>x==0),"line clears and compacts board");
 for(int seed=0;seed<20;seed++){var g=new FallingBlocksGame(2,seed);int step=0;while(!g.Lost&&!g.Won&&step++<100)g.HardDrop();Check(g.Lost||g.Won,"stacking reaches terminal state");}
 Console.WriteLine("PASS "+checks+" focused shared deck and three-game rule checks");
 }
}
