using System;using System.Collections;using System.Collections.Generic;using System.Linq;using System.Reflection;using StudentAge.Sanguosha;
static class Scenarios {
 static int count,id=500;static void Check(bool ok,string message){count++;if(!ok)throw new Exception(message);}
 static Match Blank(string p="zhaoyun",string n="liubei"){var m=new Match(p,n,false,5);m.DrawPile.Clear();m.Discard.Clear();foreach(var s in m.Seats){s.Hand.Clear();s.Judgments.Clear();s.Buqu.Clear();Array.Clear(s.Equipment,0,4);}return m;}
 static Card C(string k,Suit s=Suit.Club,int r=7)=>new Card(++id,k,s,r);
 static void Invoke(Match m,string method,params object[] args){var stack=(Stack<IEnumerator>)typeof(Match).GetField("stack",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(m);stack.Clear();typeof(Match).GetProperty("Pending").SetValue(m,null);stack.Push((IEnumerator)typeof(Match).GetMethod(method,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(m,args));typeof(Match).GetMethod("Pump",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(m,null);}
 static void Finish(Match m,Func<Prompt,int> choose=null){int cap=0;while(m.Pending!=null&&cap++<300){int c=choose==null?m.AiChoice():choose(m.Pending);m.Choose(c);}Check(cap<300,"scenario terminates");}
 public static int Run(){
  var m=Blank();var attack=C("slash");m.Seats[0].Hand.Add(attack);Invoke(m,"Use",0,attack,"slash",false);Finish(m);Check(m.Seats[1].Hp==3,"unanswered slash damages");
  m=Blank();attack=C("slash");m.Seats[0].Hand.Add(attack);m.Seats[1].Hand.Add(C("jink"));Invoke(m,"Use",0,attack,"slash",false);Finish(m);Check(m.Seats[1].Hp==4,"one jink cancels normal slash");
  m=Blank("lvbu");attack=C("slash");m.Seats[0].Hand.Add(attack);m.Seats[1].Hand.Add(C("jink"));Invoke(m,"Use",0,attack,"slash",false);Finish(m);Check(m.Seats[1].Hp==3,"wushuang requires two jinks");
  m=Blank("lvbu");attack=C("slash");m.Seats[0].Hand.Add(attack);m.Seats[1].Hand.AddRange(new[]{C("jink"),C("jink")});Invoke(m,"Use",0,attack,"slash",false);Finish(m);Check(m.Seats[1].Hp==4,"two jinks cancel wushuang");
  m=Blank();var draw=C("ex_nihilo",Suit.Heart);m.Seats[0].Hand.AddRange(new[]{draw,C("nullification")});m.DrawPile.AddRange(new[]{C("slash"),C("jink")});Invoke(m,"Use",0,draw,"ex_nihilo",false);Finish(m);Check(m.Seats[0].Hand.Count==3,"AI does not nullify own beneficial trick");
  m=Blank();attack=C("slash");m.Seats[0].Hand.AddRange(new[]{attack,C("peach",Suit.Heart)});m.Seats[1].Hp=1;Invoke(m,"Use",0,attack,"slash",false);Finish(m);Check(m.Winner==0,"AI does not rescue opposing dying seat");Check(m.DefeatedActor==1&&m.DefeatSource==0&&!m.Surrendered&&m.Events.Any(e=>e.Sound=="death-liubei"),"lethal damage has victim, source and exact death voice");
  m=Blank("daqiao");var virtualCard=C("peach",Suit.Diamond);m.Seats[0].Hand.Add(virtualCard);Invoke(m,"Use",0,virtualCard,"indulgence",false);Finish(m);Check(m.Seats[1].Judgments.Single().Kind=="indulgence","guose enters judgment as indulgence");var steal=C("snatch");m.Seats[0].Hand.Add(steal);Invoke(m,"Use",0,steal,"snatch",false);Finish(m);Check(m.Seats[0].Hand.Any(c=>c.Id==virtualCard.Id&&c.Kind=="peach"),"stolen virtual delay reverts to printed physical card");
  m=Blank("shenguanyu");m.Seats[0].Hp=0;m.Seats[1].Nightmare=1;m.DrawPile.Add(C("slash",Suit.Spade));Invoke(m,"Dying",0,1);Finish(m);Check(m.Winner==-1,"wuhun revenge makes simultaneous death a draw");
  m=Blank("shenguanyu");m.Seats[0].Hp=1;m.Seats[1].Nightmare=1;m.Seats[0].Hp=0;m.DrawPile.Add(C("peach",Suit.Heart));Invoke(m,"Dying",0,1);Finish(m);Check(m.Winner==1,"peach judgment survives wuhun");
  m=Blank("zhoutai");m.Seats[0].Hp=0;m.DrawPile.Add(C("slash",Suit.Club,3));Invoke(m,"Dying",0,1);Finish(m);Check(m.Winner==-2&&m.Seats[0].Buqu.Count==1&&m.Seats[0].Hp==0,"old buqu survives without artificially healing");
  m=Blank();var p=new Progress();Check(p.Reserve(101,1),"reserve global allowance");Check(!p.Reserve(202,1),"global allowance cannot target another NPC");Check(p.Stage(101)==0,"failed round leaves same general");Check(p.Reserve(101,2),"failure retry only next world round");
  m=Blank();attack=C("jink");m.Seats[0].Hand.Add(attack);int before=m.Events.Count;Invoke(m,"Use",0,attack,"slash",false);Finish(m);var sounds=m.Events.Skip(before).Where(e=>e.Sound!=null).Select(e=>e.Sound).ToList();Check(sounds.IndexOf("longdan")>=0&&sounds.IndexOf("longdan")<sounds.IndexOf("slash"),"conversion skill voice precedes converted card voice");
  m=Blank();m.Seats[0].Hp=0;m.Seats[0].Hand.Add(C("peach",Suit.Heart));Invoke(m,"Dying",0,1);Finish(m);Check(m.Winner==-2&&m.DefeatedActor==-1&&!m.Events.Any(e=>e.Sound!=null&&e.Sound.StartsWith("death-")),"rescued dying general has no death or kill announcement");
  m=Blank();m.Surrender(1);Check(m.Winner==0&&m.Surrendered&&m.DefeatedActor==-1&&!m.Events.Any(e=>e.Sound=="lose"||e.Sound!=null&&e.Sound.StartsWith("death-")),"opponent surrender is a win without death or kill announcement");
  m=Blank();attack=C("slash");m.Seats[1].Hp=1;m.Seats[0].Hand.Add(attack);Invoke(m,"Use",0,attack,"slash",false);Check(m.Pending==null&&m.Winner==0,"lethal attack without rescue settles immediately, no end-turn/pass prompt");
  foreach(int who in new[]{0,1}){m=Blank();m.Seats[who].Hp=0;var wine=C("wine",Suit.Spade);m.Seats[who].Hand.Add(wine);Invoke(m,"Dying",who,1-who);Check(m.Pending?.Kind==DecisionKind.Rescue&&m.Pending.Actor==who&&m.Pending.Options.Any(o=>o.CardId==wine.Id&&o.UseKind=="wine"&&o.Target==who),"wine rescue prompt belongs to dying actor");Finish(m);Check(m.Winner==-2&&m.Seats[who].Hp==1&&!m.Seats[who].Drunk&&m.Seats[who].Wines==0,"player and NPC wine rescue heals, no offensive buff/quota cost");}
  m=Blank();m.Seats[0].Hp=-1;m.Seats[0].Hand.Add(C("wine"));Invoke(m,"Dying",0,1);Finish(m);Check(m.Winner==1,"one wine does not save at minus one HP");
  m=Blank();m.Seats[0].Hp=-1;m.Seats[0].Hand.AddRange(new[]{C("wine"),C("peach")});Invoke(m,"Dying",0,1);Finish(m);Check(m.Winner==-2&&m.Seats[0].Hp==1,"multiple rescue cards must restore positive HP");
  m=Blank();var drink=C("wine");m.Seats[0].Hand.Add(drink);Invoke(m,"Use",0,drink,"wine",false);Check(m.Seats[0].Drunk&&m.Seats[0].Wines==1,"wine sets next slash bonus");attack=C("slash");m.Seats[0].Hand.Add(attack);Invoke(m,"Use",0,attack,"slash",false);Finish(m);Check(m.Seats[1].Hp==2&&!m.Seats[0].Drunk,"wine slash deals two and consumes bonus");
  attack=C("slash");m.Seats[0].Hand.Add(attack);Invoke(m,"Use",0,attack,"slash",false);Finish(m);Check(m.Seats[1].Hp==1,"wine bonus is not persistent");
  m=Blank();var trick=C("duel");var n1=C("nullification");var n2=C("nullification");var n3=C("nullification");m.Seats[0].Hand.AddRange(new[]{trick,n2});m.Seats[1].Hand.AddRange(new[]{n1,n3});Invoke(m,"Use",0,trick,"duel",false);Check(m.Pending.Kind==DecisionKind.Nullification&&m.Pending.Subject==trick,"nullification explicitly targets original trick");m.Choose(m.Pending.Options.FindIndex(o=>o.CardId==n1.Id));Check(m.Pending.Subject==n1&&m.Pending.SubjectKind=="nullification","counter-nullification targets previous counter");m.Choose(m.Pending.Options.FindIndex(o=>o.CardId==n2.Id));Check(m.Pending.Subject==n2,"third nullification targets second");m.Choose(m.Pending.Options.FindIndex(o=>o.CardId==n3.Id));Check(m.Pending==null&&m.Seats[1].Hp==4,"odd counter chain cancels trick automatically");
  m=Blank();attack=C("slash");m.Seats[0].Hand.Add(attack);m.Seats[1].Hand.Add(C("jink"));Invoke(m,"Use",0,attack,"slash",false);Check(m.Pending.Kind==DecisionKind.Response&&m.Pending.Subject==attack,"jink response has the exact attacking card");
  m=Blank();var ownDelay=C("indulgence");m.Seats[0].Judgments.Add(ownDelay);var dismantle=C("dismantlement");m.Seats[0].Hand.Add(dismantle);var opts=(System.Collections.Generic.List<Option>)typeof(Match).GetMethod("PlayOptions",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(m,new object[]{0});Check(!opts.Any(o=>o.CardId==dismantle.Id),"cannot dismantle own judgment with empty enemy zones");
  m=Blank();trick=C("snatch");var victim=C("peach");m.Seats[0].Hand.Add(trick);m.Seats[1].Hand.Add(victim);Invoke(m,"Use",0,trick,"snatch",false);Check(m.Pending==null&&m.Seats[0].Hand.Contains(victim)&&!m.Seats[1].Hand.Contains(victim),"snatch automatic transfer has no card-picker");
  m=Blank();trick=C("dismantlement");victim=C("peach");m.Seats[0].Hand.Add(trick);m.Seats[1].Hand.Add(victim);Invoke(m,"Use",0,trick,"dismantlement",false);Check(m.Pending==null&&m.Discard.Contains(victim)&&!m.Seats[0].Hand.Contains(victim),"dismantlement discards rather than stealing");
  foreach(var suit in new[]{Suit.Club,Suit.Heart}){m=Blank();var delay=C("indulgence");m.Seats[0].Judgments.Add(delay);m.DrawPile.AddRange(new[]{C("jink",suit),C("slash"),C("jink")});Invoke(m,"Round",0);Check(m.Seats[0].Hand.Count==2,"indulgence never skips drawing phase");Check(suit==Suit.Heart?m.Pending?.Kind==DecisionKind.Play:m.Pending==null,"heart judgment plays, non-heart skips play");Check(m.Seats[0].Judgments.Count==0&&m.Discard.Contains(delay),"delayed trick leaves judgment area after resolution");}
  m=Blank();m.Seats[0].Hand.AddRange(new[]{C("nullification"),C("jink")});opts=(System.Collections.Generic.List<Option>)typeof(Match).GetMethod("PlayOptions",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(m,new object[]{0});Check(!opts.Any(o=>o.UseKind=="nullification"||o.UseKind=="jink"),"response-only cards cannot be used proactively");
  var gesture=new CardDrag();var pp=new Prompt(0,"play",new[]{new Option("杀",0,1){UseKind="slash",Target=1}}){Kind=DecisionKind.Play};gesture.Begin(pp,0,1);Check(gesture.Release(pp,DropZone.Opponent,1.1f)<0,"tap cannot play a card");foreach(var zone in new[]{DropZone.None,DropZone.Hand,DropZone.Table,DropZone.Self}){gesture.Begin(pp,0,1);Check(gesture.Release(pp,zone,2)<0,"wrong/drop-back target cancels "+zone);}gesture.Begin(pp,0,1);Check(gesture.Release(pp,DropZone.Opponent,2)==0,"held attack can target enemy");gesture.Begin(pp,0,1);Check(gesture.Release(new Prompt(0,"next",pp.Options){Kind=DecisionKind.Play},DropZone.Opponent,2)<0,"stale drag never commits on new prompt");
  pp.Options[0].Target=0;gesture.Begin(pp,0,1);Check(gesture.Target==DropZone.Self&&gesture.Release(pp,DropZone.Self,2)==0,"self card targets self");pp.Options[0].Target=-1;gesture.Begin(pp,0,1);Check(gesture.Release(pp,DropZone.Table,2)==0,"global trick targets center");pp.Kind=DecisionKind.Response;gesture.Begin(pp,0,1);Check(gesture.Release(pp,DropZone.Opponent,2)<0,"jink cannot target portrait");gesture.Begin(pp,0,1);Check(gesture.Release(pp,DropZone.ResponseCard,2)==0,"jink targets active card");pp.Kind=DecisionKind.Nullification;gesture.Begin(pp,0,1);Check(gesture.Release(pp,DropZone.ResponseCard,2)==0,"counter-nullification targets active card");
  Check(Deck.CreateDuel().Count==52&&!Deck.CreateDuel().Any(c=>c.Kind=="wine"),"strict official duel distribution without wine");Check(!C("wine").Trick,"wine is a basic card");
  Check(!Deck.CreateDuel().Any(c=>c.Slot>=2||new[]{"lightning","collateral","god_salvation","amazing_grace","halberd","kylin_bow","double_sword","blade"}.Contains(c.Kind)),"official duel exclusions");
  foreach(var suit in new[]{Suit.Club,Suit.Heart}){m=Blank();m.Seats[0].Judgments.Add(C("supply_shortage"));m.DrawPile.AddRange(new[]{C("jink",suit),C("slash"),C("jink")});Invoke(m,"Round",0);Check(m.Pending?.Kind==DecisionKind.Play&&m.Seats[0].Hand.Count==(suit==Suit.Club?2:0),"supply shortage only skips draw on non-club");}
  m=Blank();var flood=C("drowning");m.Seats[0].Hand.Add(flood);Invoke(m,"Use",0,flood,"drowning",false);Check(m.Pending==null&&m.Seats[1].Hp==3,"drowning without equipment damages automatically");
  m=Blank();flood=C("drowning");m.Seats[0].Hand.Add(flood);m.Seats[1].Hp=1;m.Seats[1].Equipment[0]=C("spear");m.Seats[1].Equipment[1]=C("eight_diagram");Invoke(m,"Use",0,flood,"drowning",false);Finish(m);Check(m.Seats[1].Equipment.All(c=>c==null)&&m.Seats[1].Hp==1,"drowning can discard all equipment instead of lethal damage");
  m=Blank();var invasion=C("savage_assault");m.Seats[0].Hand.AddRange(new[]{invasion,C("nullification")});Invoke(m,"Use",0,invasion,"savage_assault",false);Check(m.Pending==null&&m.Seats[1].Hp==3,"player is not prompted to nullify their own trick");
  return count;
 }
}
