using System;using System.Runtime.InteropServices;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;
using BepInEx;using Config;using Sdk;using HarmonyLib;using UnityEngine;using UnityEngine.InputSystem;using StudentAge.CampusMinigames;using StudentAge.Sanguosha;
[BepInPlugin("studentage.sanguosha.judgmentqa","Sanguosha judgment QA","1.0.0")][BepInDependency("studio.studentage.nds")]
public sealed class SanguoshaJudgmentQAPlugin:BaseUnityPlugin {void Awake(){var go=new GameObject("Sanguosha_Drag_QA"){hideFlags=HideFlags.HideAndDontSave};DontDestroyOnLoad(go);go.AddComponent<SanguoshaJudgmentQA>();}}
public sealed class SanguoshaJudgmentQA:MonoBehaviour {
 string dir;readonly List<string> checks=new List<string>();bool failed;SanguoshaView table;static Vector2 pointer=new Vector2(1150,300);float start;
 static object Field(object o,string key)=>AccessTools.Field(o.GetType(),key).GetValue(o);
 static void Set(object o,string key,object v)=>AccessTools.Field(o.GetType(),key).SetValue(o,v);
 void Awake(){dir=Path.Combine(Paths.GameRootPath,"SanguoshaJudgmentQA");Directory.CreateDirectory(dir);PathDefine.SAVE_PATH=Path.Combine(dir,"Saves");PathDefine.TEST_SAVE_PATH=PathDefine.SAVE_PATH;PathDefine.IMG_PATH=Path.Combine(dir,"Images");PathDefine.MUSIC_PATH=Path.Combine(dir,"Music");Application.runInBackground=true;Application.targetFrameRate=60;QualitySettings.vSyncCount=0;InputSystem.settings.backgroundBehavior=InputSettings.BackgroundBehavior.IgnoreFocus;

  Application.logMessageReceived+=(m,s,t)=>{if(t==LogType.Exception){failed=true;File.WriteAllText(Path.Combine(dir,"failed.txt"),m+"\n"+s);}};start=Time.realtimeSinceStartup;
 }
 void Update(){if(failed||Time.realtimeSinceStartup-start>360){if(!failed)File.WriteAllText(Path.Combine(dir,"failed.txt"),"QA timeout");File.WriteAllLines(Path.Combine(dir,"checks.txt"),checks);Application.Quit();}}
 void Check(bool b,string message){if(!b)throw new Exception(message);checks.Add(message);File.WriteAllLines(Path.Combine(dir,"checks.txt"),checks);Debug.Log("JUDGMENT QA PASS "+message);}
 IEnumerator Shot(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(dir,name+".png"));yield return null;}
 [StructLayout(LayoutKind.Sequential)]struct POINT{public int x,y;}
 [StructLayout(LayoutKind.Sequential)]struct RECT{public int left,top,right,bottom;}
 delegate bool EnumProc(IntPtr hwnd,IntPtr param);
 [DllImport("user32.dll")]static extern bool EnumWindows(EnumProc callback,IntPtr param);
 [DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr hwnd,out uint pid);
 [DllImport("user32.dll")]static extern bool IsWindowVisible(IntPtr hwnd);
 [DllImport("user32.dll")]static extern bool GetClientRect(IntPtr hwnd,out RECT rect);
 [DllImport("user32.dll")]static extern bool ClientToScreen(IntPtr hwnd,ref POINT point);
 [DllImport("user32.dll")]static extern bool SetForegroundWindow(IntPtr hwnd);
 [DllImport("user32.dll")]static extern bool SetCursorPos(int x,int y);
 [DllImport("user32.dll")]static extern void mouse_event(uint flags,uint dx,uint dy,uint data,UIntPtr extra);
 IntPtr window;
 void Move(Vector2 p){if(window==IntPtr.Zero){uint id=(uint)System.Diagnostics.Process.GetCurrentProcess().Id;EnumWindows((h,t)=>{uint pid;GetWindowThreadProcessId(h,out pid);if(pid==id&&IsWindowVisible(h)){window=h;return false;}return true;},IntPtr.Zero);}Check(window!=IntPtr.Zero,"QA process has its own window");RECT r;GetClientRect(window,out r);float scale=Mathf.Min(Screen.width/1600f,Screen.height/900f);var pt=new POINT{x=Mathf.RoundToInt(((Screen.width-1600*scale)/2+p.x*scale)*(r.right-r.left)/Screen.width),y=Mathf.RoundToInt(((Screen.height-900*scale)/2+p.y*scale)*(r.bottom-r.top)/Screen.height)};ClientToScreen(window,ref pt);SetForegroundWindow(window);SetCursorPos(pt.x,pt.y);}
 IEnumerator Input(EventType type,Vector2 p,int button=0){pointer=p;Move(p);yield return new WaitForSecondsRealtime(.08f);if(type==EventType.MouseDown)mouse_event(button==0?2u:8u,0,0,0,UIntPtr.Zero);if(type==EventType.MouseUp)mouse_event(button==0?4u:16u,0,0,0,UIntPtr.Zero);yield return new WaitForSecondsRealtime(.07f);}
 IEnumerator Click(Vector2 p){yield return Input(EventType.MouseDown,p);yield return Input(EventType.MouseUp,p);}
 Vector2 Hand(int id)=>(Vector2)((IDictionary)Field(table,"handPositions"))[id];
 IEnumerator Drag(int id,Vector2 target,bool screenshot=false){var from=Hand(id);pointer=from;Move(from);yield return new WaitForSecondsRealtime(.25f);from=Hand(id);yield return Input(EventType.MouseDown,from);Check(table.DragActive,"long press begins on actual hand card");yield return new WaitForSecondsRealtime(.24f);yield return Input(EventType.MouseDrag,target);if(screenshot)yield return Shot("target-arrow");yield return Input(EventType.MouseUp,target);Check(!table.DragActive,"release clears pointer capture");}
 Match Blank(string general="zhangfei"){var m=new Match(general,"liubei",false,18);m.DrawPile.Clear();m.Discard.Clear();m.Events.Clear();foreach(var s in m.Seats){s.Hand.Clear();s.Judgments.Clear();Array.Clear(s.Equipment,0,4);}return m;}
 Card Card(string kind,int ordinal=0)=>Deck.Create().Where(c=>c.Kind==kind).Skip(ordinal).First();
 void RunRule(Match m,string method,params object[] args){var stack=(Stack<IEnumerator>)Field(m,"stack");stack.Clear();AccessTools.Property(typeof(Match),"Pending").SetValue(m,null,null);stack.Push((IEnumerator)AccessTools.Method(typeof(Match),method).Invoke(m,args));AccessTools.Method(typeof(Match),"Pump").Invoke(m,null);}
 IEnumerator Fixture(Match m){Set(table,"judgmentVisual",null);Set(table,"judgmentHoldUntil",0f);AccessTools.Property(typeof(SanguoshaView),"Engine").SetValue(table,m,null);((IList)Field(table,"visualHand")).Clear();((IDictionary)Field(table,"handPoses")).Clear();((IList)Field(table,"tableCards")).Clear();((Queue<MatchEvent>)Field(table,"events")).Clear();Set(table,"eventSeq",0);Set(table,"presentedEventSeq",0);Set(table,"aiAt",Time.unscaledTime+999);table.ResetTableSelection();pointer=new Vector2(1150,300);yield return new WaitForSecondsRealtime(2.5f);}
 IEnumerator Ready(){float end=Time.realtimeSinceStartup+20;while(!(bool)AccessTools.Property(typeof(SanguoshaView),"DecisionReady").GetValue(table,null)&&Time.realtimeSinceStartup<end)yield return null;Check((bool)AccessTools.Property(typeof(SanguoshaView),"DecisionReady").GetValue(table,null),"decision waits for public card presentation");}
 IEnumerator JudgmentResult(string shot){float end=Time.realtimeSinceStartup+12;while(table.JudgmentStage!="result"&&Time.realtimeSinceStartup<end)yield return null;Check(table.JudgmentStage=="result","final judgment result is presented");yield return new WaitForSecondsRealtime(.5f);yield return Shot(shot);}
 IEnumerator Start(){
  float end=Time.realtimeSinceStartup+120;while(Time.realtimeSinceStartup<end){bool ready=false;try{ready=NdsIntegration.IsTitleScreen;}catch{}if(ready)break;yield return null;}yield return new WaitForSecondsRealtime(3);Check(NdsIntegration.IsTitleScreen,"official 1.94 title ready");SanguoshaView.OpenTestDirectory();table=SanguoshaView.Current;Check(table!=null,"title test table opens");end=Time.realtimeSinceStartup+45;while(!table.AudioReady&&Time.realtimeSinceStartup<end)yield return null;Check(table.AudioReady,"all art and audio preloaded");Set(table,"testDirectory",false);AccessTools.Property(typeof(SanguoshaView),"Session").SetValue(table,new SanguoshaSession(101,0,"拖动检查"),null);Check(table.StartBattle("zhangfei",false),"test session starts without a save");
  Check(Deck.CreateDuel().Count==52&&!Deck.CreateDuel().Any(c=>c.Kind=="wine"),"loaded runtime uses strict 52-card duel deck");Check(table.Engine.DrawPile.Count+table.Engine.Seats.Sum(s=>s.Hand.Count)==52,"fresh game conserves all 52 cards");
  var m=Blank();StudentAge.Sanguosha.Card slash=Card("slash"),peach=Card("peach"),weapon=Card("crossbow"),aoe=Card("savage_assault"),wine=Card("ex_nihilo");m.Seats[0].Hp=3;m.Seats[0].Hand.AddRange(new[]{slash,peach,weapon,aoe,wine,Card("jink"),Card("nullification")});RunRule(m,"Round",0);yield return Fixture(m);yield return Ready();yield return Shot("hand-hd");
  foreach(var portrait in new[]{new Rect(697,61,196,253),new Rect(1380,632,196,242)})foreach(bool yellow in new[]{false,true}){var glow=(Rect)AccessTools.Method(typeof(SanguoshaView),"PortraitGlowStage").Invoke(null,new object[]{portrait,yellow});var core=yellow?new Rect(164,131,188,253):new Rect(166,133,184,249);var mapped=new Rect(glow.x+core.x*glow.width/512,glow.y+core.y*glow.height/512,core.width*glow.width/512,core.height*glow.height/512);var art=(Rect)AccessTools.Method(typeof(SanguoshaView),"PortraitArtRect").Invoke(null,new object[]{portrait});Check(Vector2.Distance(mapped.position,art.position)<.01f&&Vector2.Distance(mapped.size,art.size)<.01f,"red/yellow luminous frame aligns to portrait edges");}
  var texture=SanguoshaAssets.Image("hd/faces/slash-spade-7.png");Check(texture!=null&&texture.width>=400&&texture.height>=555,"chosen caise card uses native 400x555 art");
  var before=m.Pending;yield return Click(Hand(slash.Id));Check(ReferenceEquals(m.Pending,before)&&m.Seats[0].Hand.Contains(slash),"quick tap never selects or plays card");
  yield return Drag(slash.Id,new Vector2(1120,230));Check(m.Seats[0].Hand.Contains(slash),"blank-space drop cancels");yield return Drag(slash.Id,new Vector2(800,817));Check(m.Seats[0].Hand.Contains(slash),"drag back to hand cancels");
  yield return Drag(slash.Id,new Vector2(1470,710));Check(m.Seats[0].Hand.Contains(slash),"attack cannot target self");
  yield return Drag(slash.Id,new Vector2(795,170),true);Check(m.Seats[1].Hp==3&&!m.Seats[0].Hand.Contains(slash),"attack drag damages enemy without extra confirm");yield return Ready();
  yield return Drag(peach.Id,new Vector2(1470,710));Check(m.Seats[0].Hp==4,"peach drag heals self");yield return Ready();yield return Drag(weapon.Id,new Vector2(1470,710));Check(m.Seats[0].Equipment[0]?.Id==weapon.Id,"equipment drag equips self");yield return Ready();
  yield return Drag(aoe.Id,new Vector2(920,460));Check(m.Seats[1].Hp==2,"global trick drag resolves in table center");yield return Ready();yield return Drag(wine.Id,new Vector2(1470,710));Check(!m.Seats[0].Hand.Contains(wine)&&m.Seats[0].Hand.Count==4,"ex nihilo drag draws two existing cards");yield return Ready();yield return Shot("equipped-and-draw");
  m=Blank();slash=Card("slash");var jink=Card("jink");m.Seats[1].Hand.Add(slash);m.Seats[0].Hand.Add(jink);RunRule(m,"Use",1,slash,"slash",false);yield return Fixture(m);yield return Ready();Check(m.Pending.Kind==DecisionKind.Response,"incoming slash opens real response");yield return Drag(jink.Id,new Vector2(795,170));Check(m.Seats[0].Hand.Contains(jink),"jink cannot be dropped on attacker portrait");yield return Drag(jink.Id,new Vector2(800,455));Check(m.Seats[0].Hp==4&&!m.Seats[0].Hand.Contains(jink),"jink dragged onto slash prevents damage");yield return Shot("jink-response");
  m=Blank();StudentAge.Sanguosha.Card trick=Card("duel"),n1=Card("nullification"),n2=Card("nullification",1),n3=Card("nullification",2);m.Seats[1].Hand.AddRange(new[]{trick,n2});m.Seats[0].Hand.AddRange(new[]{n1,n3});RunRule(m,"Use",1,trick,"duel",false);yield return Fixture(m);yield return Ready();yield return Drag(n1.Id,new Vector2(800,455));Check(m.Pending.Actor==1&&m.Pending.Subject.Id==n1.Id,"first nullification points to response card");m.Choose(m.Pending.Options.FindIndex(o=>o.CardId==n2.Id));Set(table,"aiAt",Time.unscaledTime+999);yield return Ready();yield return new WaitForSecondsRealtime(.6f);var rr=(Rect)AccessTools.Method(typeof(SanguoshaView),"ResponseRect").Invoke(table,null);yield return Drag(n3.Id,rr.center);Check(m.Pending==null&&m.Seats[0].Hp==4,"dragging counter-nullification onto latest counter cancels duel");
  m=Blank();m.Seats[0].Hp=0;wine=Card("peach");m.Seats[0].Hand.Add(wine);RunRule(m,"Dying",0,1);yield return Fixture(m);yield return Ready();yield return Shot("peach-rescue");yield return Drag(wine.Id,new Vector2(1470,710));Check(m.Winner==-2&&m.Seats[0].Hp==1,"dying self peach drag rescues before defeat");
  m=Blank();trick=Card("indulgence");m.Seats[0].Hand.Add(trick);RunRule(m,"Round",0);yield return Fixture(m);yield return Ready();yield return Drag(trick.Id,new Vector2(795,170));yield return Ready();yield return Shot("indulgence-mark");Check(m.Seats[1].Judgments.Any(c=>c.Id==trick.Id),"indulgence remains on enemy portrait");
  m=Blank();m.Seats[0].Hand.AddRange(new[]{Card("slash"),Card("peach")});RunRule(m,"Pick",0,"选择一张手牌",m.Seats[0].Hand,false,true,false);yield return Fixture(m);yield return Ready();int selectedId=m.Seats[0].Hand[0].Id;yield return Click(Hand(selectedId));Check(m.Pending==null&&((StudentAge.Sanguosha.Card)Field(m,"selected")).Id==selectedId,"actual hand selection commits with one click, no confirm bar");
  m=Blank();var offered=new[]{Card("slash"),Card("peach")};RunRule(m,"Pick",0,"选择一张明置牌",offered,false,true,false);yield return Fixture(m);yield return Ready();yield return Shot("public-choice");yield return Click(new Vector2(665,415));Check(m.Pending==null&&((StudentAge.Sanguosha.Card)Field(m,"selected")).Id==offered[0].Id,"public-card choice remains clickable over board");

  // Physical Jink remains directly draggable even while armor can optionally judge.
  m=Blank();slash=Card("slash");jink=Card("jink");m.Seats[1].Hand.Add(slash);m.Seats[0].Hand.Add(jink);m.Seats[0].Equipment[1]=Card("eight_diagram");m.DrawPile.Add(Card("peach"));RunRule(m,"Use",1,slash,"slash",false);yield return Fixture(m);yield return Ready();Check(m.Pending.Kind==DecisionKind.Response&&m.Pending.Options.Any(o=>o.CardId==-4),"armor option shares direct response prompt");yield return Shot("jink-with-armor");yield return Drag(jink.Id,new Vector2(800,455));Check(m.Pending==null&&m.Seats[0].Hp==4&&m.DrawPile.Count==1,"jink with armor resolves by one drag without activation");
  foreach(string general in new[]{"zhangjiao","simayi"}){
   m=Blank(general);var original=Card("peach");var replacement=general=="simayi"?Card("jink"):Card("slash");m.Seats[0].Hand.Add(replacement);m.DrawPile.Add(original);RunRule(m,"Judge",0,"乐不思蜀",new Func<StudentAge.Sanguosha.Card,bool>(c=>c.Suit==Suit.Heart));yield return Fixture(m);yield return Ready();
   Check(m.Pending.Kind==DecisionKind.Judgment&&table.VisibleJudgmentCard.Id==original.Id,"initial judgment card shown before "+general+" replacement");Check(!(bool)AccessTools.Property(typeof(SanguoshaView),"ChoicePanelOpen").GetValue(table,null),"judgment area does not block hand dragging");yield return Shot(general+"-judgment-before");
   yield return Drag(replacement.Id,new Vector2(795,170));Check(m.Seats[0].Hand.Contains(replacement),"wrong judgment drop cancels");yield return Drag(replacement.Id,new Vector2(800,430));Check(!m.Seats[0].Hand.Contains(replacement),general+" hand card replaces judgment by drag");
   yield return JudgmentResult(general+"-judgment-result");Check(table.VisibleJudgmentCard.Id==replacement.Id,"replacement is the visible final card");
  }
  m=Blank("zhangjiao");var equipped=Card("qinggang_sword");m.Seats[0].Equipment[0]=equipped;m.DrawPile.Add(Card("peach"));RunRule(m,"Judge",0,"兵粮寸断",new Func<StudentAge.Sanguosha.Card,bool>(c=>c.Suit==Suit.Club));yield return Fixture(m);yield return Ready();yield return Input(EventType.MouseDown,new Vector2(1275,724));Check(table.DragActive,"guidao can begin from equipment slot");yield return new WaitForSecondsRealtime(.24f);yield return Input(EventType.MouseDrag,new Vector2(800,430));yield return Input(EventType.MouseUp,new Vector2(800,430));Check(m.Seats[0].Equipment[0]==null&&m.Seats[0].Hand.Any(c=>c.Kind=="peach"),"black equipment replaces judgment and old card is obtained");yield return JudgmentResult("guidao-equipment-result");
  foreach(bool success in new[]{false,true}){m=Blank();m.DrawPile.Add(success?Card("slash"):Card("peach"));RunRule(m,"Judge",0,"乐不思蜀",new Func<StudentAge.Sanguosha.Card,bool>(c=>c.Suit==Suit.Heart));yield return Fixture(m);yield return JudgmentResult(success?"judgment-success":"judgment-failure");var visual=(MatchEvent)Field(table,"judgmentVisual");Check(visual.JudgmentSuccess==success,"original result animation follows trick effectiveness");Check((bool)AccessTools.Property(typeof(SanguoshaView),"JudgmentHolding").GetValue(table,null),"result has protected readable presentation time");}
  foreach(string delayKind in new[]{"indulgence","supply_shortage"})foreach(bool effective in new[]{false,true}){
   m=Blank();m.Seats[0].Judgments.Add(Deck.CreateDuel().First(c=>c.Kind==delayKind));var suit=effective?Suit.Spade:delayKind=="indulgence"?Suit.Heart:Suit.Club;m.DrawPile.Add(new StudentAge.Sanguosha.Card(801,"jink",suit,8));m.DrawPile.AddRange(new[]{Card("slash"),Card("peach")});RunRule(m,"Round",0);yield return Fixture(m);yield return JudgmentResult(delayKind+(effective?"-effective":"-ineffective"));Check(table.VisibleJudgmentCard.Id==801,"real delayed trick displays drawn judgment card");Check(m.Events.Last(e=>e.JudgmentStage=="result").JudgmentSuccess==effective,"delayed trick final effect agrees with visible outcome");Check(!(bool)AccessTools.Property(typeof(SanguoshaView),"DecisionReady").GetValue(table,null),"next phase cannot act over judgment result");
  }
  m=Blank("liubei");peach=Card("peach");m.Seats[0].Hand.Add(peach);RunRule(m,"Active",0,"rende");yield return Fixture(m);yield return Ready();yield return Drag(peach.Id,new Vector2(795,170));Check(m.Seats[1].Hand.Contains(peach)&&!m.Seats[0].Hand.Contains(peach),"rende skill card dragged to opponent transfers without confirm");
  m=Blank();m.Seats[0].Hand.AddRange(new[]{Card("peach"),Card("jink")});m.Seats[0].Equipment[0]=Card("spear");RunRule(m,"Round",0);yield return Fixture(m);yield return Ready();yield return Click(new Vector2(1280,498));Check(m.Pending.Kind==DecisionKind.SkillCard,"spear weapon ability is accessible from actual play UI");yield return Ready();yield return Drag(Card("peach").Id,new Vector2(930,420));yield return Ready();yield return Drag(Card("jink").Id,new Vector2(930,420));Check(m.Pending?.Kind==DecisionKind.Play&&m.Seats[1].Hp==3,"two spear cost cards drag into play area and resolve slash");

  m=Blank();slash=Card("slash");m.Seats[1].Hp=1;m.Seats[0].Hand.AddRange(new[]{slash,Card("ex_nihilo"),Card("peach"),Card("jink"),Card("nullification")});RunRule(m,"Round",0);yield return Fixture(m);yield return Ready();yield return Drag(slash.Id,new Vector2(795,170));Check(m.Winner==0&&m.Pending==null,"lethal drag ends game before end-turn click");end=Time.realtimeSinceStartup+40;bool firstShot=false,victoryShot=false;while(table.OutcomeStage!="Ready"&&Time.realtimeSinceStartup<end){if(table.OutcomeStage=="FirstBlood"&&!firstShot){yield return new WaitForSecondsRealtime(1.7f);yield return Shot("first-blood-clean");firstShot=true;}if(table.OutcomeStage=="Victory"&&!victoryShot){yield return new WaitForSecondsRealtime(.7f);yield return Shot("victory-layer");victoryShot=true;}yield return null;}Check(table.OutcomeStage=="Ready"&&table.Session.NewReward,"general unlock waits for first blood and victory");yield return Shot("reward-layer");
  Check(!(bool)AccessTools.Property(typeof(SanguoshaView),"BoardInputAllowed").GetValue(table,null),"outcome blocks every underlying board interaction");int remain=m.Seats[0].Hand.Count;yield return Click(new Vector2(800,770));Check(table.Closed&&m.Seats[0].Hand.Count==remain,"unlock confirm closes without clicking cards beneath");
  Check(!table.MissingAudio.Any(),"no missing audio in exercised flows");Check(!failed,"no Unity exceptions");File.WriteAllText(Path.Combine(dir,"success.txt"),"SANGUOSHA_JUDGMENT_RUNTIME_OK");yield return new WaitForSecondsRealtime(.3f);Application.Quit();
 }
}
