using System;using System.Runtime.InteropServices;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;
using BepInEx;using Config;using Sdk;using HarmonyLib;using UnityEngine;using UnityEngine.InputSystem;using StudentAge.CampusMinigames;using StudentAge.Sanguosha;
[BepInPlugin("studentage.sanguosha.equipmentqa","Sanguosha judgment QA","1.0.0")][BepInDependency("studio.studentage.nds")]
public sealed class SanguoshaEquipmentQAPlugin:BaseUnityPlugin {void Awake(){var go=new GameObject("Sanguosha_Drag_QA"){hideFlags=HideFlags.HideAndDontSave};DontDestroyOnLoad(go);go.AddComponent<SanguoshaEquipmentQA>();}}
public sealed class SanguoshaEquipmentQA:MonoBehaviour {
 string dir;readonly List<string> checks=new List<string>();bool failed;SanguoshaView table;static Vector2 pointer=new Vector2(1150,300);float start;
 static object Field(object o,string key)=>AccessTools.Field(o.GetType(),key).GetValue(o);
 static void Set(object o,string key,object v)=>AccessTools.Field(o.GetType(),key).SetValue(o,v);
 void Awake(){dir=Path.Combine(Paths.GameRootPath,"SanguoshaEquipmentQA");Directory.CreateDirectory(dir);PathDefine.SAVE_PATH=Path.Combine(dir,"Saves");PathDefine.TEST_SAVE_PATH=PathDefine.SAVE_PATH;PathDefine.IMG_PATH=Path.Combine(dir,"Images");PathDefine.MUSIC_PATH=Path.Combine(dir,"Music");Application.runInBackground=true;Application.targetFrameRate=60;QualitySettings.vSyncCount=0;InputSystem.settings.backgroundBehavior=InputSettings.BackgroundBehavior.IgnoreFocus;

  Application.logMessageReceived+=(m,s,t)=>{if(t==LogType.Exception){failed=true;File.WriteAllText(Path.Combine(dir,"failed.txt"),m+"\n"+s);}};start=Time.realtimeSinceStartup;
 }
 void Update(){if(failed||Time.realtimeSinceStartup-start>360){if(!failed)File.WriteAllText(Path.Combine(dir,"failed.txt"),"QA timeout");File.WriteAllLines(Path.Combine(dir,"checks.txt"),checks);Application.Quit();}}
 void Check(bool b,string message){if(!b)throw new Exception(message);checks.Add(message);File.WriteAllLines(Path.Combine(dir,"checks.txt"),checks);Debug.Log("EQUIPMENT QA PASS "+message);}
 IEnumerator Shot(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(dir,name+".png"));yield return null;}
 [StructLayout(LayoutKind.Sequential)]struct POINT{public int x,y;}
 [StructLayout(LayoutKind.Sequential)]struct RECT{public int left,top,right,bottom;}
 delegate bool EnumProc(IntPtr hwnd,IntPtr param);
 [DllImport("user32.dll")]static extern bool EnumWindows(EnumProc callback,IntPtr param);
 [DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr hwnd,out uint pid);
 [DllImport("user32.dll")]static extern bool IsWindowVisible(IntPtr hwnd);
 [DllImport("user32.dll")]static extern bool GetClientRect(IntPtr hwnd,out RECT rect);
 [DllImport("user32.dll")]static extern bool ClientToScreen(IntPtr hwnd,ref POINT point);
 [DllImport("user32.dll")]static extern bool SetForegroundWindow(IntPtr hwnd);
 [DllImport("user32.dll")]static extern bool SetCursorPos(int x,int y);
 [DllImport("user32.dll")]static extern void mouse_event(uint flags,uint dx,uint dy,uint data,UIntPtr extra);
 IntPtr window;
 void Move(Vector2 p){if(window==IntPtr.Zero){uint id=(uint)System.Diagnostics.Process.GetCurrentProcess().Id;EnumWindows((h,t)=>{uint pid;GetWindowThreadProcessId(h,out pid);if(pid==id&&IsWindowVisible(h)){window=h;return false;}return true;},IntPtr.Zero);}Check(window!=IntPtr.Zero,"QA process has its own window");RECT r;GetClientRect(window,out r);float scale=Mathf.Min(Screen.width/1600f,Screen.height/900f);var pt=new POINT{x=Mathf.RoundToInt(((Screen.width-1600*scale)/2+p.x*scale)*(r.right-r.left)/Screen.width),y=Mathf.RoundToInt(((Screen.height-900*scale)/2+p.y*scale)*(r.bottom-r.top)/Screen.height)};ClientToScreen(window,ref pt);SetForegroundWindow(window);SetCursorPos(pt.x,pt.y);}
 IEnumerator Input(EventType type,Vector2 p,int button=0){pointer=p;Move(p);yield return new WaitForSecondsRealtime(.08f);if(type==EventType.MouseDown)mouse_event(button==0?2u:8u,0,0,0,UIntPtr.Zero);if(type==EventType.MouseUp)mouse_event(button==0?4u:16u,0,0,0,UIntPtr.Zero);yield return new WaitForSecondsRealtime(.07f);}
 IEnumerator Click(Vector2 p){yield return Input(EventType.MouseDown,p);yield return Input(EventType.MouseUp,p);}
 Vector2 Hand(int id)=>(Vector2)((IDictionary)Field(table,"handPositions"))[id];
 IEnumerator Drag(int id,Vector2 target,bool screenshot=false){var from=Hand(id);pointer=from;Move(from);yield return new WaitForSecondsRealtime(.25f);from=Hand(id);yield return Input(EventType.MouseDown,from);Check(table.DragActive,"long press begins on actual hand card");yield return new WaitForSecondsRealtime(.24f);yield return Input(EventType.MouseDrag,target);if(screenshot)yield return Shot("target-arrow");yield return Input(EventType.MouseUp,target);Check(!table.DragActive,"release clears pointer capture");}
 Match Blank(string general="zhangfei"){var m=new Match(general,"liubei",false,18);m.DrawPile.Clear();m.Discard.Clear();m.Events.Clear();foreach(var s in m.Seats){s.Hand.Clear();s.Judgments.Clear();Array.Clear(s.Equipment,0,4);}return m;}
 Card Card(string kind,int ordinal=0)=>Deck.CreateDuel().Where(c=>c.Kind==kind).Skip(ordinal).First();
 void RunRule(Match m,string method,params object[] args){var stack=(Stack<IEnumerator>)Field(m,"stack");stack.Clear();AccessTools.Property(typeof(Match),"Pending").SetValue(m,null,null);stack.Push((IEnumerator)AccessTools.Method(typeof(Match),method).Invoke(m,args));AccessTools.Method(typeof(Match),"Pump").Invoke(m,null);}
 IEnumerator Fixture(Match m){Set(table,"movementHoldUntil",0f);Set(table,"judgmentVisual",null);Set(table,"judgmentHoldUntil",0f);AccessTools.Property(typeof(SanguoshaView),"Engine").SetValue(table,m,null);((IList)Field(table,"visualHand")).Clear();((IDictionary)Field(table,"handPoses")).Clear();((IList)Field(table,"tableCards")).Clear();((Queue<MatchEvent>)Field(table,"events")).Clear();Set(table,"eventSeq",0);Set(table,"presentedEventSeq",0);Set(table,"aiAt",Time.unscaledTime+999);table.ResetTableSelection();pointer=new Vector2(1150,300);yield return new WaitForSecondsRealtime(2.5f);}
 IEnumerator Ready(){float end=Time.realtimeSinceStartup+20;while(!(bool)AccessTools.Property(typeof(SanguoshaView),"DecisionReady").GetValue(table,null)&&Time.realtimeSinceStartup<end)yield return null;Check((bool)AccessTools.Property(typeof(SanguoshaView),"DecisionReady").GetValue(table,null),"decision waits for public card presentation");}
 IEnumerator JudgmentResult(string shot){float end=Time.realtimeSinceStartup+12;while(table.JudgmentStage!="result"&&Time.realtimeSinceStartup<end)yield return null;Check(table.JudgmentStage=="result","final judgment result is presented");yield return new WaitForSecondsRealtime(.5f);yield return Shot(shot);}

 IEnumerator Movement(int id){float end=Time.realtimeSinceStartup+12;while(Time.realtimeSinceStartup<end){var e=(MatchEvent)Field(table,"feedback");if(e?.Movement!=null&&e.Card.Id==id)break;yield return null;}var ev=(MatchEvent)Field(table,"feedback");Check(ev?.Movement!=null&&ev.Card.Id==id,"exact moved card is presented");yield return new WaitForSecondsRealtime(.65f);}
 IEnumerator Start(){
  float end=Time.realtimeSinceStartup+120;while(Time.realtimeSinceStartup<end){bool ready=false;try{ready=NdsIntegration.IsTitleScreen;}catch{}if(ready)break;yield return null;}yield return new WaitForSecondsRealtime(2);Check(NdsIntegration.IsTitleScreen,"official title ready");SanguoshaView.OpenTestDirectory();table=SanguoshaView.Current;end=Time.realtimeSinceStartup+45;while(!table.AudioReady&&Time.realtimeSinceStartup<end)yield return null;Check(table.AudioReady,"art and audio loaded");Set(table,"testDirectory",false);AccessTools.Property(typeof(SanguoshaView),"Session").SetValue(table,new SanguoshaSession(101,0,"装备检查"),null);Check(table.StartBattle("zhangfei",false),"isolated title duel begins");
  var m=Blank();var dismantle=Card("dismantlement");var snatch=Card("snatch");var weapon=Card("crossbow");var armor=Card("eight_diagram");m.Seats[0].Hand.AddRange(new[]{dismantle,snatch});m.Seats[1].Equipment[0]=weapon;m.Seats[1].Equipment[1]=armor;m.Seats[1].Hand.Add(Card("jink"));RunRule(m,"Round",0);yield return Fixture(m);yield return Ready();yield return Shot("enemy-equipment");
  yield return Drag(dismantle.Id,new Vector2(795,180));yield return Ready();Check(m.Pending.Reveal.Count==2&&m.Pending.Options.Any(o=>o.CardId==-5),"equipment face-up and enemy hand hidden in picker");yield return Shot("choose-equipment");yield return Click(new Vector2(498,165));Check(m.Seats[1].Equipment[0]==null&&m.Discard.Contains(weapon),"click enemy weapon directly dismantles it");yield return Movement(weapon.Id);yield return Shot("dismantled-weapon");yield return Ready();
  yield return Drag(snatch.Id,new Vector2(795,180));yield return Ready();yield return Click(new Vector2(606,165));Check(m.Seats[1].Equipment[1]==null&&m.Seats[0].Hand.Contains(armor)&&m.Seats[0].Equipment[1]==null,"snatched armor enters hand without auto-equipping");yield return Movement(armor.Id);yield return Shot("snatched-armor");
  m=Blank();m.Seats[1].Equipment[0]=weapon;m.Seats[1].Equipment[1]=armor;m.Seats[0].Hand.Add(Card("drowning"));RunRule(m,"Use",0,m.Seats[0].Hand[0],"drowning",false);yield return Fixture(m);m.Choose(0);yield return Movement(weapon.Id);yield return Shot("drowning-first-equipment");yield return Movement(armor.Id);yield return Shot("drowning-second-equipment");Check(m.Seats[1].Equipment.All(c=>c==null)&&m.Events.Count(e=>e.Movement=="discard")==2,"drowning animates both equipment removals");
  foreach(int actor in new[]{0,1})foreach(bool red in new[]{false,true}){
   m=Blank();m.Seats[actor].Equipment[1]=armor;var judge=Card(red?"peach":"slash");Check(judge.Red==red,"judgment fixture suit");m.DrawPile.Add(judge);RunRule(m,"Respond",actor,"jink",1-actor,true,Card("slash",1));yield return Fixture(m);m.Choose(m.Pending.Options.FindIndex(o=>o.CardId==-4));end=Time.realtimeSinceStartup+12;while(table.JudgmentStage!="reveal"&&Time.realtimeSinceStartup<end)yield return null;Check(table.JudgmentStage=="reveal"&&table.VisibleJudgmentCard.Id==judge.Id,"armor publicly reveals actual rank and suit for actor "+actor);yield return new WaitForSecondsRealtime(.6f);yield return Shot("armor-"+actor+"-"+red+"-reveal");yield return JudgmentResult("armor-"+actor+"-"+red+"-result");var ev=(MatchEvent)Field(table,"judgmentVisual");Check(ev.JudgmentReason=="八卦阵"&&ev.JudgmentSuccess==red,"armor result matches red/black judgment");
  }
  m=Blank();m.DrawPile.AddRange(Deck.CreateDuel().Take(6));yield return Fixture(m);AccessTools.Method(typeof(Match),"Draw").Invoke(m,new object[]{1,3});end=Time.realtimeSinceStartup+5;while((int)Field(table,"drawCount")!=3&&Time.realtimeSinceStartup<end)yield return null;Check((int)Field(table,"drawCount")==3&&m.Seats[1].Hand.Count==3,"opponent animation uses all three actual cards");yield return new WaitForSecondsRealtime(.2f);yield return Shot("opponent-draw-three");
  Check(!failed,"no Unity exceptions");table.Close();File.WriteAllText(Path.Combine(dir,"success.txt"),"SANGUOSHA_EQUIPMENT_RUNTIME_OK");Application.Quit();
 }
}
