using System.Runtime.InteropServices;using Config;using Sdk;using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;
using UnityEngine.InputSystem;using UnityEngine.InputSystem.LowLevel;using HarmonyLib;using StudentAge.CampusUno;using StudentAge.CampusMinigames;using StudentAge.Retro;using BepInEx;using UnityEngine;using UnityEngine.UI;
[BepInPlugin("studentage.campus.upqa","Campus Mario Fix QA","0.1.0")]
[BepInDependency("sa.EC2B.UnofficialPatch")][BepInDependency("studio.studentage.campusuno")]
public sealed class CampusUpQA:BaseUnityPlugin {
 SanguoshaView probeTable;readonly Dictionary<string,Vector2> lastMotion=new Dictionary<string,Vector2>();readonly Dictionary<string,float> lastExit=new Dictionary<string,float>();readonly List<string> motionRows=new List<string>();float lastSample,maxHandSpeed,maxTableSpeed,maxExitJump;int sampleCount;
 IEnumerator MotionSamples(){while(true){yield return new WaitForEndOfFrame();SampleMotion();}}
 void SampleMotion(){if(probeTable==null||probeTable.Closed)return;float now=Time.unscaledTime,dt=now-lastSample;lastSample=now;if(dt<=0)return;
  var poses=(IDictionary)Field(probeTable,"handPoses");foreach(DictionaryEntry e in poses){string key="hand-"+e.Key+"-"+System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(e.Value);Vector2 pos=(Vector2)Field(e.Value,"Center")-Vector2.up*(float)Field(e.Value,"Lift");Sample(key,pos,dt,now,true);}
  foreach(var c in (IEnumerable)Field(probeTable,"tableCards")){string key="table-"+System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(c);Vector2 pos=(Vector2)Field(c,"Position");float exit=(float)Field(c,"Exit");if(lastExit.TryGetValue(key,out float old)&&old<0&&exit>=0&&lastMotion.TryGetValue(key,out var prev))maxExitJump=Mathf.Max(maxExitJump,Vector2.Distance(prev,pos));lastExit[key]=exit;Sample(key,pos,dt,now,false);}sampleCount++;
 }
 void Sample(string key,Vector2 pos,float dt,float now,bool hand){if(lastMotion.TryGetValue(key,out var previous)&&dt<.12f){float speed=Vector2.Distance(previous,pos)/dt;if(hand)maxHandSpeed=Mathf.Max(maxHandSpeed,speed);else maxTableSpeed=Mathf.Max(maxTableSpeed,speed);}lastMotion[key]=pos;motionRows.Add(now.ToString("0.000")+","+key+","+pos.x.ToString("0.00")+","+pos.y.ToString("0.00"));}
 void Probe(SanguoshaView table){probeTable=table;lastMotion.Clear();lastExit.Clear();lastSample=Time.unscaledTime;}
 static Vector2? qaPointer;static void HandPointer(){if(qaPointer.HasValue)Event.current.mousePosition=qaPointer.Value;}
 string dir;readonly List<string> checks=new List<string>();readonly List<string> errors=new List<string>();
 void Awake(){StartCoroutine(MotionSamples());new Harmony("studentage.sanguosha.motion.pointerqa").Patch(AccessTools.Method(typeof(SanguoshaView),"DrawHand"),prefix:new HarmonyMethod(AccessTools.Method(typeof(CampusUpQA),"HandPointer")));dir=Path.Combine(Paths.GameRootPath,"CampusUpQA");Directory.CreateDirectory(dir);PathDefine.SAVE_PATH=Path.Combine(dir,"Saves");PathDefine.TEST_SAVE_PATH=PathDefine.SAVE_PATH;PathDefine.IMG_PATH=Path.Combine(dir,"Images");PathDefine.MUSIC_PATH=Path.Combine(dir,"Music");Application.runInBackground=true;InputSystem.settings.backgroundBehavior=InputSettings.BackgroundBehavior.IgnoreFocus;Application.targetFrameRate=60;QualitySettings.vSyncCount=0;DontDestroyOnLoad(gameObject);Application.logMessageReceived+=(m,s,t)=>{if(t==LogType.Exception){errors.Add(m+"\n"+s);File.WriteAllText(Path.Combine(dir,"failed.txt"),m+"\n"+s);File.WriteAllLines(Path.Combine(dir,"motion.csv"),motionRows);}};}
 void Check(bool ok,string text){if(!ok)throw new Exception(text);checks.Add(text);Logger.LogInfo("PASS "+text);}
 IEnumerator Start(){float end=Time.realtimeSinceStartup+30;while(Time.realtimeSinceStartup<end){bool ready=false;try{ready=UIMgr.GetOpeningView<View.Main.EntryView>()!=null;}catch{}if(ready)break;yield return null;}Logger.LogInfo("QA title warmup complete");yield return new WaitForSecondsRealtime(2);var run=Run();bool fail=false;while(true){bool more=false;object next=null;try{more=run.MoveNext();if(more)next=run.Current;}catch(Exception e){fail=true;File.WriteAllText(Path.Combine(dir,"failed.txt"),e.ToString());Logger.LogError(e);}if(fail||!more)break;yield return next;}File.WriteAllLines(Path.Combine(dir,"checks.txt"),checks);if(!fail)File.WriteAllText(Path.Combine(dir,"success.txt"),"SANGUOSHA_TABLE_RUNTIME_OK");yield return new WaitForSecondsRealtime(.5f);Application.Quit();}
 static T Find<T>() where T:Component=>Resources.FindObjectsOfTypeAll<T>().FirstOrDefault(v=>v.gameObject.activeInHierarchy);
 static object Field(object o,string n)=>AccessTools.Field(o.GetType(),n).GetValue(o);
 static void Set(object o,string n,object v)=>AccessTools.Field(o.GetType(),n).SetValue(o,v);
 IEnumerator Keys(float seconds,params Key[] keys){InputSystem.QueueStateEvent(Keyboard.current,new KeyboardState(keys));yield return new WaitForSecondsRealtime(seconds);InputSystem.QueueStateEvent(Keyboard.current,new KeyboardState());yield return null;}
 IEnumerator Launch(int index){Logger.LogInfo("Launching QA game "+index);NdsConsole.OpenFromTitle();yield return new WaitForSecondsRealtime(2.5f);var c=NdsConsole.Current;Check(c!=null,"title console ready "+index);c.Select(index);c.SelectLevel(1);c.StartSelected();float end=Time.realtimeSinceStartup+30;while((Find<PuzzleFrame>()==null||!Find<PuzzleFrame>().Prepared)&&Time.realtimeSinceStartup<end)yield return null;Check(Find<PuzzleFrame>()?.Prepared==true,"game prepared "+index);}
 void Pointer(Vector2 point){qaPointer=point;float scale=Mathf.Min(Screen.width/1600f,Screen.height/900f);Vector2 offset=new Vector2((Screen.width-1600*scale)/2,(Screen.height-900*scale)/2);Mouse.current.WarpCursorPosition(new Vector2(offset.x+point.x*scale,Screen.height-offset.y-point.y*scale));}
 Vector2 HandPoint(SanguoshaView table,int id)=>(Vector2)((IDictionary)Field(table,"handPositions"))[id];
 IEnumerator MovePointer(SanguoshaView table,int id){var c=HandPoint(table,id);Pointer(c+new Vector2(-20,-10));float end=Time.unscaledTime+2;object pose=((IDictionary)Field(table,"handPoses"))[id];while(Time.unscaledTime<end&&((int)Field(table,"hoverCard")!=id||(float)Field(pose,"Lift")<21))yield return null;Check((int)Field(table,"hoverCard")==id,"hover hit follows projected card "+id);Check((float)Field(pose,"Lift")>17,"hover lifts visible card "+id+" lift="+Field(pose,"Lift"));}
 IEnumerator Record(SanguoshaView table,string folder,int count,Action<int> action=null){string path=Path.Combine(dir,folder);Directory.CreateDirectory(path);var times=new List<float>();float start=Time.realtimeSinceStartup;for(int f=0;f<count;f++){action?.Invoke(f);yield return new WaitForEndOfFrame();times.Add(Time.realtimeSinceStartup-start);ScreenCapture.CaptureScreenshot(Path.Combine(path,f.ToString("D4")+".png"));yield return new WaitForSecondsRealtime(1f/30);}File.WriteAllText(Path.Combine(path,"timing.json"),Newtonsoft.Json.JsonConvert.SerializeObject(times));}
 IEnumerator Run(){
 bool done=false,loaded=false;SaveMgrEx.LoadAynsc(PathDefine.SAVE_PATH,"fixture.save",16,ok=>{loaded=ok;done=true;});float end=Time.realtimeSinceStartup+30;while(!done&&Time.realtimeSinceStartup<end)yield return null;Check(loaded,"isolated fixture loaded");yield return new WaitForSecondsRealtime(3);
 for(int n=0;n<3;n++){var warning=Resources.FindObjectsOfTypeAll<Button>().FirstOrDefault(b=>b.gameObject.activeInHierarchy&&b.GetComponentsInChildren<Text>().Any(t=>t.text=="好的"));if(warning==null)break;warning.onClick.Invoke();yield return new WaitForSecondsRealtime(1);}
 var round=Singleton<RoundMgr>.Ins;var bag=Singleton<BagMgr>.Ins;var shop=Singleton<ShopMgr>.Ins;var player=Singleton<RoleMgr>.Ins.GetRole();SanguoshaIntegration.Register();Check(SaveMgrEx.Save(false,PathDefine.SAVE_PATH,"sanguosha-empty.save"),"independent empty save written");round.SetTime(2002,6);Check(!shop.GetShopDatas(4).Any(d=>d.id==SanguoshaIntegration.BoxId),"not sold before 2003");round.SetTime(2003,1);player.SetAttr(30,300);float passive=player.GetAttrEachRoundInc(0);shop.shopTog=SanguoshaIntegration.TabId;UIMgr.OpenView<View.Shop.ShopView>(UILayerType.None,null,Array.Empty<object>());yield return new WaitForSecondsRealtime(3);var view=UIMgr.GetOpeningView<View.Shop.ShopView>();Check(view!=null&&view.togCells.Count==4,"four native shop tabs");var offer=shop.GetShopDatas(SanguoshaIntegration.TabId).Single();Check(offer.id==SanguoshaIntegration.BoxId&&offer.FinalPrize==10,"only initial box offered before ownership");
 ScreenCapture.CaptureScreenshot(Path.Combine(dir,"sanguosha-shop-before.png"));yield return new WaitForSecondsRealtime(.2f);var cell=view.itemgroup_item.GetCells().OfType<GenUI.Shop.Cell_ShopItemUI>().First(c=>((ShopData)c.data).id==SanguoshaIntegration.BoxId);Check(cell.icon_item.image.sprite==SanguoshaAssets.Sprite("box"),"native box icon is the card art");cell.btn_buy.btn.onClick.Invoke();yield return null;Check(SanguoshaIntegration.Owned&&player.GetAttr(30)==290,"native shop button buys for exactly 10");Check(StudentAge.Sanguosha.Catalog.Generals.Count(g=>SanguoshaIntegration.Has(g.Id))==1&&SanguoshaIntegration.Has("zhaoyun"),"starter gives exactly Zhao Yun");Check(Math.Abs(player.GetAttrEachRoundInc(0)-passive-3)<.01f,"held box adds mood +3 per round");Check(shop.GetShopDatas(SanguoshaIntegration.TabId).Count==StudentAge.Sanguosha.Catalog.Generals.Count(g=>SanguoshaIntegration.IsShopGeneral(g.Id)),"shop includes remaining generals and two gods");foreach(var god in new[]{"shenguanyu","shenlvmeng"}){var data=shop.GetShopDatas(SanguoshaIntegration.TabId).Single(d=>d.id==SanguoshaIntegration.CardId(god));Check(data.FinalPrize==100,"god costs exactly 100: "+god);Check(shop.Buy(data),"god bought: "+god);}Check(player.GetAttr(30)==90,"two gods deduct 200");Check(!shop.Buy(SanguoshaIntegration.CardId("zhaoyun")),"cannot buy duplicate starter");ScreenCapture.CaptureScreenshot(Path.Combine(dir,"sanguosha-shop-cards.png"));yield return new WaitForSecondsRealtime(.2f);UIMgr.CloseView<View.Shop.ShopView>();yield return new WaitForSecondsRealtime(.5f);
 int npc=101;Singleton<RoleMgr>.Ins.GetRelationData().ChangeRelation(npc,1);Check(SanguoshaIntegration.CanFight(npc),"social opponent initially available");float favor=Singleton<RoleMgr>.Ins.GetRole(npc).Favor;var session=new SanguoshaSession(npc);Check(session.Begin(),"first match reserves global round");Check(!SanguoshaIntegration.CanFight(102),"cannot fight another NPC this round");Check(session.Finish(false),"loss settles");Check(SanguoshaIntegration.Read().Stage(npc)==0&&!SanguoshaIntegration.CanFight(npc),"loss stays on same stage but locks this round");Check(Math.Abs(Singleton<RoleMgr>.Ins.GetRole(npc).Favor-favor-10)<.01f,"loss adds exactly 10 affection");Check(!session.Finish(true),"duplicate callback cannot settle again");int r=round.GetRound();round.SetRound(r+1);Check(SanguoshaIntegration.CanFight(npc),"next round unlocks retry");
 Singleton<FuncMgr>.Ins.GetMapData().UpdateNpcMap(npc,4);UIMgr.OpenView<View.Main.MapRoleView>(UILayerType.None,null,new object[]{npc,Cfg.MapCfgMap[4].bg,4,true});float socialEnd=Time.realtimeSinceStartup+15;while(UIMgr.GetOpeningView<View.Main.MapRoleView>()==null&&Time.realtimeSinceStartup<socialEnd)yield return null;yield return new WaitForSecondsRealtime(.4f);var social=UIMgr.GetOpeningView<View.Main.MapRoleView>();Check(social!=null,"native social view opens");var option=social.itemgroup_option.GetCells().OfType<GenUI.Main.Cell_RoleOptionItemUI>().FirstOrDefault(c=>c.data is int id&&id==SanguoshaIntegration.OptionId);Check(option!=null&&option.txt_name.text=="打三国杀"&&option.btn_click.interactable,"native social option uses original cell");ScreenCapture.CaptureScreenshot(Path.Combine(dir,"sanguosha-social.png"));yield return new WaitForSecondsRealtime(.2f); var logo=option.icon_bg.transform.Find("SanguoshaLogo");Check(logo!=null&&logo.GetComponent<Image>().sprite==SanguoshaAssets.Sprite("social"),"social circle has the traditional original logo");Check(((RectTransform)logo).anchorMin.x==0&&((RectTransform)logo).anchoredPosition.x==70,"logo is anchored in left circle, away from option text");
 File.WriteAllText(Path.Combine(dir,"social-geometry.txt"),"circle="+((RectTransform)option.icon_bg.transform).rect+" logo="+((RectTransform)logo).rect);
 int originalId=(int)option.data;option.data=301;social.OnCellRender(option);Check(!logo.gameObject.activeSelf,"pooled ordinary social option hides the Sanguosha logo");option.data=originalId;social.OnCellRender(option);Check(logo.gameObject.activeSelf,"reused Sanguosha option restores its logo");
option.btn_click.btn.onClick.Invoke();yield return new WaitForSecondsRealtime(.4f);Check(SanguoshaView.Current!=null,"native social click opens general selection");float readyDeadline=Time.realtimeSinceStartup+40;while(!SanguoshaView.Current.AudioReady&&Time.realtimeSinceStartup<readyDeadline)yield return null;Check(SanguoshaView.Current.AudioReady,"audio and visual resources ready before battle");Check(SanguoshaView.Current.DecodedAudioCount==Directory.GetFiles(Path.Combine(SanguoshaAssets.Root,"audio"),"*.ogg").Length,"all original audio formats decoded");Check(SanguoshaView.Current.MusicPlaying,"original board BGM playing");ScreenCapture.CaptureScreenshot(Path.Combine(dir,"sanguosha-select.png"));yield return new WaitForSecondsRealtime(.2f);var table=SanguoshaView.Current;
 var metadata=Newtonsoft.Json.Linq.JObject.Parse(File.ReadAllText(Path.Combine(SanguoshaAssets.Root,"official/effects/metadata.json")));foreach(string key in new[]{"first-blood","victory-text","defeat-text","victory-base","defeat-base","general-unlock-start","general-unlock-loop"}){var m=metadata[key];var texture=SanguoshaAssets.Image("official/effects/"+key+".png");Check(texture!=null&&texture.width==((int)m["width"]+2)*(int)m["columns"]&&texture.height==((int)m["height"]+2)*(int)m["rows"],"GPU atlas dimensions match frame metadata: "+key);}
 Check(table.StartBattle("zhaoyun",true),"starts audio duel");Probe(table);yield return Record(table,"deal-motion",75);yield return new WaitForSecondsRealtime(.5f);var initial=table.Engine.Seats[0].Hand.ToArray();foreach(var c in initial.Take(3))yield return MovePointer(table,c.Id);yield return Record(table,"hover-motion",90,f=>{var c=initial[Math.Min(initial.Length-1,f/18)];Pointer(HandPoint(table,c.Id)+new Vector2(Mathf.Sin(f*.2f)*22,50));});Pointer(new Vector2(1150,400));
 Check(table.Engine.Seats.All(s=>s.MaxHp==s.General.Hp+1),"simple max HP bonus preserved");
 var voice=(AudioSource)Field(table,"voice");var sound=AccessTools.Method(typeof(SanguoshaView),"Sound");sound.Invoke(table,new object[]{"longdan",0});yield return new WaitForSecondsRealtime(.2f);Check(voice.isPlaying,"original skill voice plays through Unity audio source");yield return Keys(.1f,Key.Escape);float pausedTime=voice.time;yield return new WaitForSecondsRealtime(.4f);Check(table.Paused&&Mathf.Abs(voice.time-pausedTime)<.05f,"Esc pauses the active voice timeline");yield return Keys(.1f,Key.Escape);yield return new WaitForSecondsRealtime(.2f);Check(!table.Paused&&voice.time>pausedTime,"voice resumes at its previous position");
 foreach(string key in new[]{"armor","weapon","horse","recover-effect","card-place","injure1","injure2","injure3"})sound.Invoke(table,new object[]{key,0});
 // Open a genuine public-card choice prompt, then inspect the original soft-edged window.
 StudentAge.Sanguosha.Match choiceFixture=null;for(int seed=1;seed<300;seed++){var m=new StudentAge.Sanguosha.Match("zhaoyun","liubei",true,seed);if(m.Pending?.Actor==0&&m.Pending.Options.Any(o=>o.UseKind=="amazing_grace")&&!m.Seats.Any(p=>p.Hand.Any(c=>c.Kind=="nullification"))){choiceFixture=m;break;}}
 Check(choiceFixture!=null,"public-card choice fixture found");Probe(null);((IList)Field(table,"visualHand")).Clear();((IDictionary)Field(table,"handPoses")).Clear();AccessTools.Property(typeof(SanguoshaView),"Engine").SetValue(table,choiceFixture,null);Set(table,"eventSeq",0);Set(table,"presentedEventSeq",0);table.ResetTableSelection();table.SelectOption(choiceFixture.Pending.Options.FindIndex(o=>o.UseKind=="amazing_grace"));yield return new WaitForSecondsRealtime(2);Check(choiceFixture.Pending?.Reveal?.Count>0,"public-card selection is visible");ScreenCapture.CaptureScreenshot(Path.Combine(dir,"original-card-choice.png"));yield return new WaitForSecondsRealtime(.2f);
 // Natural lethal slash through the real engine response and rescue prompts.
 StudentAge.Sanguosha.Match fixture=null;for(int seed=1;seed<300;seed++){var m=new StudentAge.Sanguosha.Match("zhaoyun","liubei",true,seed);if(m.Pending?.Actor==0&&m.Pending.Text.EndsWith(" · 出牌阶段")&&m.Pending.Options.Any(o=>o.UseKind=="slash"&&m.Seats[0].Hand.Any(c=>c.Id==o.CardId&&c.Kind=="jink"))){fixture=m;break;}}
 Check(fixture!=null,"natural lethal conversion fixture found");fixture.Seats[1].Hand.Clear();fixture.Seats[1].Hp=1;Probe(null);((IList)Field(table,"visualHand")).Clear();((IDictionary)Field(table,"handPoses")).Clear();AccessTools.Property(typeof(SanguoshaView),"Engine").SetValue(table,fixture,null);Set(table,"eventSeq",0);Set(table,"presentedEventSeq",0);table.ResetTableSelection();yield return new WaitForSecondsRealtime(1);Probe(table);var attack=fixture.Pending.Options.First(o=>o.UseKind=="slash"&&fixture.Seats[0].Hand.Any(c=>c.Id==o.CardId&&c.Kind=="jink"));table.SelectOption(fixture.Pending.Options.IndexOf(attack));
 var stages=new List<string>();var samples=new List<string>();float deadline=Time.realtimeSinceStartup+40;var outcomeFrameTimes=new List<float>();int frame=0;Directory.CreateDirectory(Path.Combine(dir,"outcome-frames"));
 while(Time.realtimeSinceStartup<deadline&&table.OutcomeStage!="Ready"){
  if(fixture.Pending?.Actor==0&&fixture.Pending.Text=="请打出桃")table.SelectOption(fixture.Pending.Options.Count-1);
  string stage=table.OutcomeStage;if(stages.Count==0||stages.Last()!=stage){stages.Add(stage);samples.Add(Time.realtimeSinceStartup.ToString("0.000")+" "+stage+" voice="+(voice.clip==null?"none":voice.clip.name)+" playing="+voice.isPlaying);}
  if(stage=="FirstBlood"||stage=="Victory"||stage=="Reward"){yield return new WaitForEndOfFrame();outcomeFrameTimes.Add(Time.realtimeSinceStartup);ScreenCapture.CaptureScreenshot(Path.Combine(dir,"outcome-frames",(frame++).ToString("D4")+".png"));}
  yield return new WaitForSecondsRealtime(1f/30);
 }
 Check(table.OutcomeStage=="Ready","outcome presentation completes");Check(stages.Contains("FirstBlood")&&stages.IndexOf("FirstBlood")<stages.IndexOf("Victory"),"first blood completes before original victory animation begins");
 Check(stages.Contains("Reward")&&stages.IndexOf("Reward")>stages.IndexOf("Victory"),"new general unlock follows victory without a text result dialog");Check(table.Session.NewReward,"first reward marks a newly unlocked general");yield return Record(table,"reward-hold",35);var played=table.PlayedAudio.ToList();Check(played.Contains("longdan")&&played.Contains("male-slash")&&played.Contains("death-liubei"),"converted slash and exact defeated general voice are all heard");Check(played.IndexOf("death-liubei")<played.IndexOf("first-blood")&&played.IndexOf("first-blood")<played.IndexOf("win"),"death, first blood, victory audio sequence is ordered");Check(played.Count(x=>x=="first-blood")==1&&played.Count(x=>x=="win")==1,"first blood and victory play exactly once");Check(!table.MissingAudio.Any(),"no missing playback keys");Check(!table.MusicPlaying,"battle BGM stays paused through outcome");Check(SanguoshaIntegration.Read().Stage(npc)==1&&SanguoshaIntegration.Has("liubei"),"natural lethal win awards one card and advances one stage");ScreenCapture.CaptureScreenshot(Path.Combine(dir,"sanguosha-win.png"));File.WriteAllText(Path.Combine(dir,"outcome-frames/timing.json"),Newtonsoft.Json.JsonConvert.SerializeObject(outcomeFrameTimes));File.WriteAllLines(Path.Combine(dir,"audio-order.txt"),played);File.WriteAllLines(Path.Combine(dir,"outcome-timing.txt"),samples);Probe(null);table.Close();yield return new WaitForSecondsRealtime(.2f);Check(voice==null&&!Plugin.IsBusy&&Time.timeScale==1,"closing destroys voice and restores world input/time");
 foreach(int surrenderActor in new[]{0,1}){round.SetRound(round.GetRound()+1);Check(SanguoshaView.Open(npc),"open surrender fixture "+surrenderActor);table=SanguoshaView.Current;deadline=Time.realtimeSinceStartup+20;while(!table.AudioReady&&Time.realtimeSinceStartup<deadline)yield return null;Check(table.StartBattle("zhaoyun",true),"start surrender fixture "+surrenderActor);table.Engine.Surrender(surrenderActor);deadline=Time.realtimeSinceStartup+20;yield return Record(table,"surrender-"+surrenderActor,120);while(table.OutcomeStage!="Ready"&&Time.realtimeSinceStartup<deadline)yield return null;Check(table.OutcomeStage=="Ready"&&!table.PlayedAudio.Contains("first-blood"),"surrender skips first blood "+surrenderActor);Check(table.PlayedAudio.Contains(surrenderActor==0?"lose":"win"),"surrender keeps appropriate result sound "+surrenderActor);table.Close();yield return null;}
 // Play additional real prompts in both rule modes, including gods' conversion/selection skills.
 Singleton<RoleMgr>.Ins.GetRelationData().ChangeRelation(102,1);
 foreach(string general in new[]{"shenlvmeng","shenguanyu"}){round.SetRound(round.GetRound()+1);Check(SanguoshaView.Open(102),"open continuous play "+general);table=SanguoshaView.Current;deadline=Time.realtimeSinceStartup+20;while(!table.AudioReady&&Time.realtimeSinceStartup<deadline)yield return null;Check(table.StartBattle(general,general=="shenguanyu"),"start both-mode continuous play "+general);Probe(table);int choices=0;deadline=Time.realtimeSinceStartup+120;var seen=new HashSet<string>();
  while(table.Engine.Winner==-2&&choices<12&&Time.realtimeSinceStartup<deadline){if(table.Engine.Pending?.Actor==0&&table.VoicesIdle&&((ICollection)Field(table,"events")).Count==0){var prompt=table.Engine.Pending;seen.Add(prompt.Text);int n=table.Engine.AiChoice();var o=prompt.Options[n];if(o.CardId>=0&&o.UseKind!=null){table.SelectTableCard(o.CardId);if(o.Target>=0)table.SelectTableTarget(o.Target);if(table.TableCanConfirm)table.ConfirmTableSelection();else table.SelectOption(n);}else table.SelectOption(n);choices++;if(choices%3==0)ScreenCapture.CaptureScreenshot(Path.Combine(dir,"play-"+general+"-"+choices+".png"));}yield return new WaitForSecondsRealtime(.12f);}
  Check(choices>=12||table.Engine.Winner!=-2,"continuous legal decisions complete "+general);File.WriteAllLines(Path.Combine(dir,"prompts-"+general+".txt"),seen);Check(!table.MissingAudio.Any(),"continuous play has no missing sounds "+general);if(table.Engine.Winner==-2)table.Engine.Surrender(0);deadline=Time.realtimeSinceStartup+35;while(table.OutcomeStage!="Ready"&&Time.realtimeSinceStartup<deadline)yield return null;Check(table.OutcomeStage=="Ready","continuous play settles "+general);Probe(null);table.Close();yield return null;
 }
 File.WriteAllLines(Path.Combine(dir,"motion.csv"),motionRows);File.WriteAllText(Path.Combine(dir,"motion-summary.json"),Newtonsoft.Json.JsonConvert.SerializeObject(new{sampleCount,maxHandSpeed,maxTableSpeed,maxExitJump}));
 Check(sampleCount>200,"motion sampled across hundreds of actual frames");Check(maxHandSpeed<4200,"hand motion has no single-frame teleport, max px/sec="+maxHandSpeed);Check(maxTableSpeed<4200,"table motion has no single-frame teleport, max px/sec="+maxTableSpeed);Check(maxExitJump<12,"retiring public cards stay at their previous position, max shift="+maxExitJump);File.WriteAllLines(Path.Combine(dir,"motion.csv"),motionRows);File.WriteAllText(Path.Combine(dir,"motion-summary.json"),Newtonsoft.Json.JsonConvert.SerializeObject(new{sampleCount,maxHandSpeed,maxTableSpeed,maxExitJump}));
 Check(errors.Count==0,"no Unity exceptions: "+string.Join(";",errors.ToArray()));
 }
}
