using System;using System.Linq;using System.Collections;using System.Collections.Generic;using StudentAge.CampusPuzzles;using StudentAge.CampusUno;using UnityEngine;using UnityEngine.UI;using UnityEngine.InputSystem;
namespace StudentAge.CampusMinigames
{
    public sealed class MazeView:PuzzleFrame
    {
        public MazeGame Engine{get;private set;}RectTransform field;Sprite pupil,guardSprite,candy;PacmanGraphic player;Text progress;readonly Dictionary<int,Image> beans=new Dictionary<int,Image>(),powers=new Dictionary<int,Image>();readonly List<Image> guards=new List<Image>();float clock;int oldPlayer;int[] oldGuards;
        protected override string Title=>"吃豆人";
        protected override string[] Rules=>new[]{"WASD 或方向键控制移动。","在校园迷宫收集糖豆，收齐本局目标即可获胜。","转弯可提前按，遇到墙壁会停下。","避开巡逻员，碰到一次扣一颗心，共三颗心。","大糖果会暂时让巡逻员退避，碰到可送回起点。","没有整局倒计时，后续关卡巡逻更紧密。"};
        protected override IEnumerator LoadAssets(){pupil=ArcadeArt.Load(Session.Root,"maze-pupil",Owned);guardSprite=ArcadeArt.Load(Session.Root,"maze-guard",Owned);candy=ArcadeArt.Load(Session.Root,"candy",Owned);Engine=new MazeGame(Level,Environment.TickCount);yield break;}
        protected override void BuildPlay(){Paper(PlayRoot,418,153,724,596);field=R(PlayRoot,"Maze",448,181,665,525);for(int y=0;y<MazeGame.Height;y++)for(int x=0;x<MazeGame.Width;x++){int cell=y*19+x;if(!MazeGame.Open(cell)){var tile=I(field,"Hedge",x*35,y*35,35,35,null,new Color(.48f,.60f,.37f));if(y==0||MazeGame.Open(cell-19))I(tile.transform,"Highlight",0,0,35,3,null,new Color(.77f,.82f,.56f,.8f));if(x==18||MazeGame.Open(cell+1))I(tile.transform,"Edge",32,0,3,35,null,new Color(.35f,.47f,.27f,.7f));}else I(field,"Path",x*35,y*35,35,35,null,new Color(.96f,.91f,.75f));}
            foreach(int cell in Engine.Beans)beans[cell]=I(field,"Bean",cell%19*35+8,cell/19*35+8,19,19,candy,Color.white);foreach(int cell in Engine.Powers)powers[cell]=I(field,"BigCandy",cell%19*35+3,cell/19*35+3,29,29,candy,Color.white);
            player=R(field,"PacMan",0,0,32,32).gameObject.AddComponent<PacmanGraphic>();player.raycastTarget=false;foreach(var g in Engine.Guards)guards.Add(I(field,"Patrol",0,0,33,33,guardSprite,Color.white));progress=T(PlayRoot,"",54,299,315,142,30);oldPlayer=Engine.Player;oldGuards=Engine.Guards.ToArray();Draw(1);}
        protected override void StartGame(){clock=0;}
        public void Turn(int direction){if(Started&&!Ending)Engine.Turn(direction);}
        protected override void Tick(){var k=Keyboard.current;if(k!=null){if(k.upArrowKey.wasPressedThisFrame||k.wKey.wasPressedThisFrame)Turn(0);if(k.rightArrowKey.wasPressedThisFrame||k.dKey.wasPressedThisFrame)Turn(1);if(k.downArrowKey.wasPressedThisFrame||k.sKey.wasPressedThisFrame)Turn(2);if(k.leftArrowKey.wasPressedThisFrame||k.aKey.wasPressedThisFrame)Turn(3);}clock+=Math.Min(StudentAge.CampusUno.PlayClock.Delta,.1f);if(clock>=Engine.Interval){clock-=Engine.Interval;oldPlayer=Engine.Player;oldGuards=Engine.Guards.ToArray();int eaten=Engine.Collected,lives=Engine.Lives;Engine.Step();if(Engine.Collected!=eaten)Sfx("pickup",.13f);if(Engine.Lives!=lives){oldPlayer=Engine.Player;oldGuards=Engine.Guards.ToArray();Sfx("undo",.24f);}if(Engine.Won||Engine.Lost){Ending=true;StartCoroutine(Result());}}Draw(clock/Engine.Interval);}
        void Position(Graphic i,int from,int to,float t){if(Math.Abs(from%19-to%19)+Math.Abs(from/19-to/19)>1)from=to;i.rectTransform.pivot=new Vector2(.5f,.5f);i.rectTransform.anchoredPosition=Vector2.Lerp(new Vector2(from%19*35+17.5f,-from/19*35-17.5f),new Vector2(to%19*35+17.5f,-to/19*35-17.5f),Mathf.Clamp01(t));}
        void Draw(float t){Position(player,oldPlayer,Engine.Player,t);player.color=new Color(1,.87f,.10f,Engine.Grace>0&&Mathf.Sin(StudentAge.CampusUno.PlayClock.Now*15)<0?.5f:1);player.Pose(Engine.Direction,StudentAge.CampusUno.PlayClock.Now*10);foreach(var pair in beans)pair.Value.gameObject.SetActive(Engine.Beans.Contains(pair.Key));foreach(var pair in powers)pair.Value.gameObject.SetActive(Engine.Powers.Contains(pair.Key));for(int n=0;n<guards.Count;n++){Position(guards[n],oldGuards[n],Engine.Guards[n],t);guards[n].color=Engine.PowerSteps>0?new Color(.53f,.74f,1):Color.white;}progress.text="糖豆 "+Engine.Collected+" / "+Engine.Target+"\n\n"+new string('♥',Engine.Lives);}
        IEnumerator Result(){Draw(1);yield return new StudentAge.CampusUno.PlayDelay(.8f);Ending=false;Finish(Engine.Won);}
    }
}
