using System.IO.Compression;using System.Text;using StudentAge.CampusUpdates;
int checks=0;void Check(bool ok,string label){if(!ok)throw new Exception(label);checks++;}void Reject(Action action,string label){try{action();}catch(Exception){checks++;return;}throw new Exception("Accepted "+label);}
string root=Path.Combine(Path.GetTempPath(),"campus-update-tests-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);
try {
foreach(string path in new[]{"../save","CampusMinigames/../../save","CampusMinigames/a/../b","/CampusMinigames/x","CampusMinigames\\x","CampusMinigames/a:b","CampusMinigames/CON.txt","CampusMinigames/a.","CampusMinigames/a ","BepInEx/config/x","CampusMinigames//x","CampusUno/CampusUno.dll","StudentAgeCampusMinigames/Nds/font.json"})Reject(()=>UpdatePackage.ValidatePath(path),path);
foreach(string path in new[]{"CampusMinigames/CampusMinigames.dll","CampusMinigames/Music/音频来源.md","CampusMinigames/Nds/font.json"}){UpdatePackage.ValidatePath(path);checks++;}
Check(UpdatePackage.Newer("0.9.10","0.9.3")&&!UpdatePackage.Newer("0.9.2","0.9.3")&&!UpdatePackage.Newer("0.9.3","0.9.3"),"numeric version ordering");
var feed=new Feed{schema=1,layout=UpdatePackage.Layout,version="0.9.4",size=32,sha256=new string('a',64),url="https://github.com/360478712scy-gif/StudentAge-CampusMinigames/releases/download/v0.9.4/package.zip"};UpdatePackage.ValidateFeed(feed,"360478712scy-gif/StudentAge-CampusMinigames");checks++;
foreach(string url in new[]{"http://github.com/360478712scy-gif/StudentAge-CampusMinigames/releases/download/v1/a","https://github.com/elsewhere/repo/releases/download/v1/a","https://github.com.evil.test/360478712scy-gif/StudentAge-CampusMinigames/releases/download/v1/a","file:///tmp/a"}){var bad=UpdatePackage.Read<Feed>(UpdatePackage.Write(feed));bad.url=url;Reject(()=>UpdatePackage.ValidateFeed(bad,"360478712scy-gif/StudentAge-CampusMinigames"),url);}
string source=Path.Combine(root,"source");Directory.CreateDirectory(source);string[] files={"CampusMinigames/CampusMinigames.dll","CampusMinigames/CustomMinigamecfg.json","CampusMinigames/Nds/new.png"};foreach(string f in files){string path=UpdatePackage.Under(source,f);Directory.CreateDirectory(Path.GetDirectoryName(path)!);File.WriteAllText(path,"new "+f);}
var payload=new Payload{schema=1,version="0.9.4",files=files.Select(f=>new PayloadFile{path=f,size=new FileInfo(UpdatePackage.Under(source,f)).Length,sha256=UpdatePackage.Hash(UpdatePackage.Under(source,f))}).ToList()};
string MakeZip(string name,Action<ZipArchive> extra=null){string path=Path.Combine(root,name);using(var z=ZipFile.Open(path,ZipArchiveMode.Create)){using(var s=z.CreateEntry("package.json").Open()){var b=UpdatePackage.Write(payload);s.Write(b);}foreach(string f in files)z.CreateEntryFromFile(UpdatePackage.Under(source,f),f);extra?.Invoke(z);}return path;}
string zip=MakeZip("valid.zip"),stage=Path.Combine(root,"verified");var parsed=UpdatePackage.Extract(zip,UpdatePackage.Hash(zip),"0.9.4",stage);Check(parsed.files.Count==3,"valid package extracted");Reject(()=>UpdatePackage.Extract(zip,new string('a',64),"0.9.4",Path.Combine(root,"bad-hash")),"wrong zip hash");Reject(()=>UpdatePackage.Extract(zip,UpdatePackage.Hash(zip),"0.9.5",Path.Combine(root,"bad-version")),"wrong package version");
string duplicate=MakeZip("duplicate.zip",z=>z.CreateEntry("campusminigames/CampusMinigames.dll"));Reject(()=>UpdatePackage.Extract(duplicate,UpdatePackage.Hash(duplicate),"0.9.4",Path.Combine(root,"duplicate")),"case-insensitive duplicate");
string extra=MakeZip("extra.zip",z=>z.CreateEntry("../../outside"));Reject(()=>UpdatePackage.Extract(extra,UpdatePackage.Hash(extra),"0.9.4",Path.Combine(root,"extra")),"undeclared traversal");
string target=Path.Combine(root,"plugins");Directory.CreateDirectory(Path.Combine(target,"CampusMinigames"));foreach(string f in files.Take(2))File.WriteAllText(UpdatePackage.Under(target,f),"old "+f);File.WriteAllText(Path.Combine(target,"other-mod.dll"),"keep");
UpdatePackage.Apply(target,stage,parsed,Path.Combine(root,"backup-ok"));Check(files.All(f=>UpdatePackage.Hash(UpdatePackage.Under(target,f))==UpdatePackage.Hash(UpdatePackage.Under(source,f))),"DLL and resources installed");Check(File.ReadAllText(Path.Combine(target,"other-mod.dll"))=="keep","unrelated mod untouched");Check(File.ReadAllText(Path.Combine(root,"backup-ok",files[0]))=="old "+files[0],"backup contains originals");
foreach(string f in files.Take(2))File.WriteAllText(UpdatePackage.Under(target,f),"old "+f);File.Delete(UpdatePackage.Under(target,files[2]));Reject(()=>UpdatePackage.Apply(target,stage,parsed,Path.Combine(root,"backup-fail"),n=>{if(n==3)throw new IOException("simulated interruption");}),"install interruption");Check(files.Take(2).All(f=>File.ReadAllText(UpdatePackage.Under(target,f))=="old "+f)&&!File.Exists(UpdatePackage.Under(target,files[2])),"rollback restores DLL and removes newly created file");Check(File.ReadAllText(Path.Combine(root,"backup-fail/status.txt"))=="rolled-back","rollback recorded");
string linked=Path.Combine(target,"CampusMinigames/Nds");Directory.Delete(linked);Directory.CreateSymbolicLink(linked,source);Reject(()=>UpdatePackage.Apply(target,stage,parsed,Path.Combine(root,"backup-linked")),"symlink target");
Console.WriteLine("UPDATE_TRANSACTION_OK "+checks);
}finally{Directory.Delete(root,true);}
