using System;using System.Linq;using System.Collections.Generic;using StudentAge.CampusPuzzles;using StudentAge.PlayingCards;
class Program
{
 static int checks;static void Check(bool ok,string name){if(!ok)throw new Exception(name);checks++;}
 static PlayingCard[] Cards(params int[] ranks)=>ranks.GroupBy(x=>x).SelectMany(g=>Enumerable.Range(0,g.Count()).Select(i=>g.Key>=16?new PlayingCard(CardSuit.Joker,g.Key-15):new PlayingCard((CardSuit)i,g.Key==14?1:g.Key==15?2:g.Key))).ToArray();
 static void Pattern(LandlordKind kind,params int[] ranks){var c=Cards(ranks);Check(LandlordRules.Classify(c).Kind==kind,"classify "+kind+" "+string.Join(',',ranks));if(kind!=LandlordKind.Invalid)Check(LandlordRules.Moves(c).Any(m=>m.Length==c.Length),"generate "+kind);}
 static void Set(object o,string name,object value)=>o.GetType().GetProperty(name).SetValue(o,value);
 static void Main(){
 Pattern(LandlordKind.Single,14);Pattern(LandlordKind.Pair,15,15);Pattern(LandlordKind.Triple,9,9,9);Pattern(LandlordKind.TripleSingle,8,8,8,17);Pattern(LandlordKind.TriplePair,8,8,8,9,9);Pattern(LandlordKind.Straight,10,11,12,13,14);Pattern(LandlordKind.PairRun,3,3,4,4,5,5);Pattern(LandlordKind.TripleRun,5,5,5,6,6,6);Pattern(LandlordKind.PlaneSingles,3,3,3,4,4,4,5,5);Pattern(LandlordKind.PlanePairs,3,3,3,4,4,4,5,5,6,6);Pattern(LandlordKind.FourSingles,7,7,7,7,8,9);Pattern(LandlordKind.FourSingles,7,7,7,7,8,8);Pattern(LandlordKind.FourPairs,7,7,7,7,8,8,9,9);Pattern(LandlordKind.Bomb,8,8,8,8);Pattern(LandlordKind.Rocket,16,17);
 Pattern(LandlordKind.Invalid,11,12,13,14,15);Pattern(LandlordKind.Invalid,3,3,4,4);Pattern(LandlordKind.Invalid,3,3,3,5,5,5);Pattern(LandlordKind.Invalid,3,3,3,4,4,4,16,17);Pattern(LandlordKind.Invalid,3,3,3,3,16,17);Pattern(LandlordKind.Invalid,3,3,3,3,4,4,4,4);
 var single=LandlordRules.Classify(Cards(17));var bomb=LandlordRules.Classify(Cards(3,3,3,3));var rocket=LandlordRules.Classify(Cards(16,17));Check(bomb.Beats(single)&&rocket.Beats(bomb)&&!bomb.Beats(rocket)&&!single.Beats(bomb),"bomb hierarchy");Check(!rocket.Beats(rocket),"equal rocket cannot beat");Check(!LandlordRules.Classify(Cards(7,8,9,10,11,12)).Beats(LandlordRules.Classify(Cards(3,4,5,6,7))),"same sequence length");Check(!LandlordRules.Classify(new[]{Cards(3)[0],Cards(3)[0]}).Valid,"duplicate physical card");
 var game=new LandlordGame(1,7);Check(game.Hands.Sum(h=>h.Count)==51&&game.Hands.SelectMany(h=>h).Concat(game.Bottom).Select(c=>c.Id).Distinct().Count()==54,"54 shared cards dealt");int deal=game.Deals;for(int i=0;i<3;i++)Check(game.Bid(game.Turn,0),"pass bid");Check(game.Deals==deal+1&&game.Bidding,"all pass redeals");Check(!game.Bid((game.Turn+1)%3,3)&&!game.Bid(game.Turn,4),"reject auction invalid");Check(game.Bid(game.Turn,1)&&!game.Bid(game.Turn,1),"must raise bid");int landlord=game.Turn;Check(game.Bid(landlord,3)&&!game.Bidding&&game.Hands[landlord].Count==20&&game.Turn==landlord,"3 bid takes bottom");Check(!game.Pass(game.Turn),"lead cannot pass");var first=game.Hands[landlord].Last();Check(game.Play(game.Turn,new[]{first}),"real discard");Check(game.Pass(game.Turn)&&game.Pass(game.Turn)&&!game.Previous.Valid&&game.Turn==landlord,"two passes reset lead");Check(!game.Play(game.Turn,new[]{first})&&game.DiscardCount==1,"cannot replay removed card");
 for(int level=1;level<=5;level++)for(int seed=0;seed<12;seed++){game=new LandlordGame(level,seed);int turn=0;while(game.Winner<0&&turn++<600){if(game.Bidding){Check(game.Bid(game.Turn,game.AiBid(game.Turn)),"AI bid legal");continue;}int total=game.Hands.Sum(h=>h.Count);var move=game.Choose(game.Turn);Check(move==null?game.Pass(game.Turn):game.Play(game.Turn,move),"AI action legal");Check(game.Hands.Sum(h=>h.Count)+game.DiscardCount==54,"54 card conservation");}Check(game.Winner>=0,"AI game terminates "+level+"/"+seed);Check(game.HumanWon==(game.Landlord==0?game.Winner==0:game.Winner!=game.Landlord),"team outcome");}
 for(int level=1;level<=5;level++){var snake=new SnakeGame(level,2);Check(!snake.Body.Contains(snake.Food)&&!snake.Walls.Contains(snake.Food),"snake food free");Check(!snake.Turn(3)&&snake.Turn(0)&&!snake.Turn(2)&&snake.Turn(3),"queued turn prevents reversal");snake.Step();Check(snake.Direction==0,"queued first turn");snake.Step();Check(snake.Direction==3,"queued second turn");snake=new SnakeGame(level,1);Set(snake,"Food",snake.Body[0]+1);snake.Step();Check(snake.Eaten==1&&snake.Body.Count==4,"snake growth");for(int i=0;i<40;i++)snake.Step();Check(snake.Lost,"snake boundary loss");int moves=snake.Moves;snake.Step();Check(snake.Moves==moves,"loss terminal");}
 var tail=new SnakeGame(1,1);tail.Body.Clear();tail.Body.AddRange(new[]{100,101,123,122});Set(tail,"Direction",2);Set(tail,"Food",200);tail.Step();Check(!tail.Lost&&tail.Body[0]==122,"can enter departing tail");
 for(int level=1;level<=5;level++){var maze=new MazeGame(level,3);int opens=MazeGame.Map.Sum(row=>row.Count(c=>c!='#'));Check(maze.Distances(MazeGame.Start).Count==opens,"all maze paths reachable");Check(maze.Beans.Count==maze.Target&&maze.Beans.All(MazeGame.Open)&&maze.Powers.All(MazeGame.Open),"maze targets reachable");int max=2000;while(!maze.Won&&!maze.Lost&&max-->0){var d=maze.Distances(maze.Player);int target=maze.Beans.OrderBy(c=>d[c]).First();var back=maze.Distances(target);int best=Enumerable.Range(0,4).OrderBy(dir=>back[MazeGame.Next(maze.Player,dir)]).First();maze.Turn(best);Set(maze,"Grace",100);maze.Step();}Check(maze.Won,"collect all maze beans "+level);int moves=maze.Moves;maze.Step();Check(maze.Moves==moves,"maze win terminal");}
 var hit=new MazeGame(1,2);hit.Turn(3);Set(hit,"Direction",3);Set(hit,"Grace",0);hit.Guards[0]=hit.Player;hit.Step();Check(hit.Lives==2&&hit.Player==MazeGame.Start&&hit.Grace>0,"collision costs one heart resets");hit.Step();Check(hit.Lives==2,"respawn protection");Set(hit,"Grace",0);Set(hit,"PowerSteps",10);hit.Guards[0]=MazeGame.Next(hit.Player,hit.Direction);hit.Step();Check(hit.Lives==2&&hit.Guards[0]!=hit.Player,"power sends guard home");Console.WriteLine("PASS "+checks+" checks; 60 complete AI games, five-stage Snake/Maze mechanics.");}
}
