using System;using System.Collections.Generic;using UnityEngine;using UnityEngine.UI;
namespace StudentAge.CampusUno {
public sealed class IllustratedGuide:MonoBehaviour {
    struct Lesson {public string Text,Kind,Values;public Lesson(string text,string kind,string values=""){Text=text;Kind=kind;Values=values;}}
    readonly List<Lesson> lessons=new List<Lesson>();RectTransform content;Transform native;Action closed;int page;string title;
    public static GameObject Show(Transform parent,int id,Action onClose){var root=R(parent,"IllustratedGuide",0,0,1600,900);var v=root.gameObject.AddComponent<IllustratedGuide>();v.closed=onClose;v.Load(id);v.Build();return root.gameObject;}
    void Load(int id){switch(id){
    case 9101:title="课间UNO";Add("四人各7张牌。轮到你时，点击同颜色、同数字或同功能的牌接着出。","uno","7|7|7");Add("没有合适的牌就摸一张。摸到可出的牌，可以选择出牌或过牌。","uno","摸|→|7");Add("跳过牌让下一位停一回合；反转牌调换出牌方向。","uno","停|↔|→");Add("+2让下一位摸两张并停一回合。加牌效果不能叠加。","uno","+2|+1|+1");Add("换色牌自由选颜色；手里没有当前颜色普通牌时才能打+4。","uno","换|+4|四色");Add("剩一张前后记得按UNO，漏报会补两张。最先出完手牌的人获胜。","uno","2|UNO|1");break;
    case 9102:title="五子棋";Add("你执黑先手，双方轮流点击棋盘交叉点，放下一枚棋子。","gomoku");Add("横、竖或斜着先连成五子获胜。没有禁手，超过五子也算。","five");Add("留意对手的连线，及时堵住端点；也可以创造自己的两路进攻。","block");Add("红点标记最新落子。悔棋会撤回你上一手和电脑的回应。","undo");break;
    case 9103:title="课间泡泡";Add("方向键或WASD移动；空格放泡泡。","keys","W|A|S|D");Add("泡泡向上下左右十字爆开，遇到课桌停止；纸箱可以炸开。","bubble");Add("放下泡泡后及时躲到拐角。爆炸会引爆附近的其他泡泡。","bubble");Add("收集道具提升威力，避开水波；击败对手即可获胜。","bubble");break;
    case 9104:title="换盒寻物";Add("先看清目标文具在哪个盒子里。盒盖关闭前记住它的位置。","boxes","铅笔");Add("盒子沿弧线交换位置，跟住目标所在的盒子，而不是原来的位置。","swap");Add("交换结束后点击一个盒子，只能选一次。会伸手开盖显示答案。","boxes","?");Add("一局三轮，猜对两轮获胜。后面关卡合盖更快、交换更多。","boxes","✓|✓|×");break;
    case 9105:title="算24点";Add("四张牌各用一次，用加减乘除和括号得到24；A按1计算。","calc","10|8|7|1");Add("依次点击第一个数、运算符、第二个数，两张牌合并成一个新数。","calc","8|−|4|=4");Add("合并顺序就是括号；减法和除法按选牌顺序计算，也能得到分数。","calc","(1+3)|(2+4)|×|24");Add("每题两分钟，答对三题获胜。可以无限撤销或重算，等于24才可交卷。","timer","02:00|24|✓");break;
    case 9106:title="俄罗斯方块";Add("方向键或WASD移动与旋转；Z反转，X旋转，空格落到底。","keys","←|↑|→|空格");Add("把一横排全部填满就会消除，积累本关要求的消行数即可获胜。","tetris");Add("虚影提示落点，预览提示下一块；留好空隙，别堆到顶端。","tetris");Add("暂停时方块和下落计时都会停下，可继续、重开或认输。","keys","Esc|暂停");break;
    case 9107:title="斗地主";Add("每人17张、底牌3张。依次叫更高的分，最高叫分者当地主并拿底牌。","cards","17|17|17|+3");Add("地主独自对两名农民。地主出完获胜，任一农民出完则农民方获胜。","cards","地主|农民|农民");Add("点击选牌，再点出牌；连续两家不出，由最后出牌者重新领出。","cards","3|3|出牌");Add("单张、对子、三张，以及三带一、三带一对；接牌要同型且更大。","cards","7|7|7|9");Add("顺子至少5张，连对至少3对；连续牌型不能包含2和大小王。","cards","3|4|5|6|7");Add("飞机至少两组连续三张，可不带牌，也可以带等组数的单牌或对子。","cards","3|3|3|4|4|4");Add("四张同点数是炸弹，能压普通牌；大小王一起是最大的王炸。","cards","8|8|8|8");Add("大小顺序为3到K、A、2、小王、大王；打过的牌会留在桌上。","cards","K|A|2|小王|大王");break;
    case 9108:title="贪吃蛇";Add("用方向键或WASD转弯，吃到食物后变长；不能直接掉头。","snake");Add("避开边界、障碍和自己的身体。可以提前输入下一次转弯。","snake");Add("吃够本关目标即可获胜；最后一关目标10个食物，最多10格障碍。","snake");Add("按Esc可以休息，暂停期间蛇不会继续移动。","keys","Esc|暂停");break;
    case 9109:title="吃豆人";Add("用方向键或WASD移动黄色吃豆人。转弯可提前按，遇墙会停下。","pacman");Add("沿通道吃豆，达到本关目标即可获胜。避开巡逻员，共三颗心。","pacman");Add("吃到大糖果后短暂强化，碰到巡逻员会把他们送回起点。","pacman");Add("按Esc休息，豆子、敌人和效果时间都会停住。","keys","Esc|暂停");break;
    case 9112:title="课间麻将";Add("四人用136张牌。轮到你先摸一张，再选一张打出；双击也能出牌。","tiles","一萬|二萬|三萬");Add("上家打出的牌可以吃成顺子；任何一家打出的牌都能碰成三张相同。","tiles","七条|七条|七条");Add("四张相同可以杠，杠后补摸一张；能吃碰杠时会出现对应按钮。","tiles","五筒|五筒|五筒|五筒");Add("通常四组顺子或刻子，再加一对将牌即可胡。也支持七对与抢补杠胡。","tiles","顺子|刻子|将牌");Add("可以点过放弃响应；没有番数门槛、没有下注，一局结束后结算。","tiles","吃|碰|杠|胡");Add("桌面会保留各家的弃牌；观察已出的牌，决定留下哪些搭子。","tiles","东|南|西|北");break;
    default:title="玩法说明";Add("使用画面中的按钮或对应方向键操作。","keys","←|↑|→");break;
    }}
    void Add(string text,string kind,string values=""){lessons.Add(new Lesson(text,kind,values));}
    void Build(){var dim=Fill(transform,"Mask",0,0,1600,900,new Color(0,0,0,.65f));dim.raycastTarget=true;
        if(NativeSkin.GuidePrefab!=null){var obj=Instantiate(NativeSkin.GuidePrefab,transform,false);obj.SetActive(true);native=obj.transform;var r=obj.GetComponent<RectTransform>();r.anchorMin=r.anchorMax=r.pivot=new Vector2(.5f,.5f);r.anchoredPosition=Vector2.zero;r.sizeDelta=new Vector2(2560,1440);r.localScale=Vector3.one*.625f;foreach(var a in obj.GetComponentsInChildren<Animator>(true))a.enabled=false;foreach(string n in new[]{"group_mask/icon_content","img_talk"}){var t=native.Find(n);if(t!=null)t.gameObject.SetActive(false);}content=R(native,"IllustratedLessons",460,280,1640,870);Wire("btn_close",()=>{closed?.Invoke();Destroy(gameObject);});Wire("btn_prev",()=>{page--;Draw();});Wire("btn_next",()=>{page++;Draw();});}
        else{content=R(transform,"IllustratedLessons",185,120,1640,870);content.localScale=Vector3.one*.75f;var b=Fill(transform,"Close",1350,70,160,65,new Color(.45f,.62f,.5f));var button=b.gameObject.AddComponent<Button>();button.onClick.AddListener(()=>{closed?.Invoke();Destroy(gameObject);});Text(b.transform,"返回",0,0,160,65,26);}
        Draw();
    }
    void Wire(string name,Action action){var t=native.Find(name);if(t==null)return;t.gameObject.SetActive(true);var b=t.GetComponent<Button>()??t.gameObject.AddComponent<Button>();b.onClick.RemoveAllListeners();b.onClick.AddListener(()=>action());b.targetGraphic=t.GetComponent<Graphic>();}
    void Draw(){foreach(Transform c in content){c.gameObject.SetActive(false);Destroy(c.gameObject);}var paper=Fill(content,"Paper",0,0,1640,870,new Color(1,.97f,.9f));paper.sprite=NativeSkin.Paper;paper.type=Image.Type.Sliced;Text(content,title+" · 玩法说明",80,35,1480,100,48);for(int col=0;col<2;col++){int i=page*2+col;if(i>=lessons.Count)break;var lesson=lessons[i];var pane=R(content,"Lesson-"+i,75+col*800,155,690,570);Fill(pane,"DiagramPanel",0,0,690,355,new Color(.92f,.86f,.73f));Diagram(pane,lesson);Text(pane,lesson.Text,12,385,666,210,33,true);}Text(content,(page+1)+" / "+((lessons.Count+1)/2),630,790,380,50,28);if(native!=null){native.Find("btn_prev")?.gameObject.SetActive(page>0);native.Find("btn_next")?.gameObject.SetActive((page+1)*2<lessons.Count);}}
    void Diagram(Transform p,Lesson l){
        if(l.Kind=="gomoku"||l.Kind=="five"||l.Kind=="block"||l.Kind=="undo"){for(int n=0;n<9;n++){Fill(p,"Grid",130+n*54,20,2,310,new Color(.4f,.28f,.13f));Fill(p,"Grid",130,20+n*38,435,2,new Color(.4f,.28f,.13f));}for(int n=0;n<(l.Kind=="five"?5:4);n++)Circle(p,"Stone",164+n*54,130,37,new Color(.12f,.13f,.11f));if(l.Kind=="block")Circle(p,"Block",380,130,37,Color.white);Circle(p,"Latest",164,130,8,new Color(.8f,.15f,.1f));return;}
        if(l.Kind=="cards"||l.Kind=="uno"||l.Kind=="tiles"||l.Kind=="calc"||l.Kind=="timer"){string[] values=l.Values.Split('|');float width=Math.Min(l.Kind=="tiles"?128:122,560f/Math.Max(1,values.Length));float x=(690-values.Length*(width+8))/2;for(int n=0;n<values.Length;n++){var card=Fill(p,"ExampleCard",x+n*(width+8),80,width,190,l.Kind=="uno"?new[]{new Color(.79f,.25f,.2f),new Color(.25f,.48f,.72f),new Color(.3f,.62f,.36f)}[n%3]:new Color(1,.99f,.92f));card.sprite=NativeSkin.Paper;card.type=Image.Type.Sliced;Text(card.transform,values[n],4,40,width-8,110,values[n].Length>3?28:39).color=l.Kind=="uno"?Color.white:new Color(.42f,.15f,.1f);}if(l.Kind=="calc")Text(p,"选数  →  运算  →  合并",60,285,570,50,30);return;}
        if(l.Kind=="boxes"||l.Kind=="swap"){for(int n=0;n<4;n++){Fill(p,"Box",55+n*150,128,130,140,new Color(.64f,.4f,.2f));Fill(p,"Lid",49+n*150,113,142,25,new Color(.8f,.6f,.36f));Text(p,l.Kind=="swap"?"?":n==1?l.Values:"?",55+n*150,160,130,65,32).color=Color.white;}if(l.Kind=="swap")Text(p,"↶     ↷",110,28,480,85,42);else Text(p,"看清目标的位置",90,28,510,65,36);return;}
        if(l.Kind=="snake"){int[,] cells={{1,2},{2,2},{3,2},{4,2},{4,1}};foreach(var c in new[]{0,1,2,3,4})Fill(p,"Snake",130+cells[c,0]*60,50+cells[c,1]*60,54,54,new Color(.3f,.57f,.28f));Circle(p,"Food",495,112,30,new Color(.82f,.25f,.15f));Fill(p,"Wall",445,230,54,54,new Color(.45f,.38f,.28f));Text(p,"↑  →  ↓  ←",125,290,450,60,28);return;}
        if(l.Kind=="pacman"){var o=R(p,"PacMan",115,110,135,135).gameObject.AddComponent<GuideCircle>();o.Mouth=true;o.color=new Color(1,.8f,.05f);for(int n=0;n<5;n++)Circle(p,"Bean",310+n*60,176,18,new Color(.83f,.6f,.2f));return;}
        if(l.Kind=="bubble"){for(int y=0;y<5;y++)for(int x=0;x<7;x++){bool blast=x==3||y==2;Fill(p,"Tile",118+x*65,18+y*65,59,59,blast?new Color(.5f,.82f,.89f):new Color(.62f,.67f,.42f));}Circle(p,"Bubble",345,180,64,new Color(.3f,.62f,.86f));return;}
        if(l.Kind=="tetris"){for(int y=0;y<6;y++)for(int x=0;x<8;x++)Fill(p,"Cell",155+x*45,20+y*45,42,42,y==5?new Color(.37f,.65f,.55f):new Color(.25f,.3f,.31f));foreach(int x in new[]{2,3,4})Fill(p,"Piece",155+x*45,155,42,42,new Color(.88f,.58f,.22f));Fill(p,"Piece",290,110,42,42,new Color(.88f,.58f,.22f));Text(p,"填满一行  →  消除",100,293,490,48,31);return;}
        string[] keys=l.Values.Split('|');for(int i=0;i<keys.Length;i++){var k=Fill(p,"Key",85+i*135,110,120,100,new Color(.97f,.96f,.9f));k.sprite=NativeSkin.Paper;k.type=Image.Type.Sliced;Text(k.transform,keys[i],0,10,120,80,keys[i].Length>2?28:40);}Text(p,"键盘操作",80,250,530,55,34);
    }
    static void Circle(Transform p,string name,float x,float y,float size,Color color){var c=R(p,name,x-size/2,y-size/2,size,size).gameObject.AddComponent<GuideCircle>();c.color=color;c.raycastTarget=false;}
    static Image Fill(Transform p,string n,float x,float y,float w,float h,Color color){var i=R(p,n,x,y,w,h).gameObject.AddComponent<Image>();i.color=color;i.raycastTarget=false;return i;}
    static Text Text(Transform p,string value,float x,float y,float w,float h,int size,bool body=false){var t=R(p,"Caption",x,y,w,h).gameObject.AddComponent<Text>();t.font=body?NativeSkin.BodyFont:NativeSkin.TitleFont;t.fontSize=size;t.text=value;t.color=new Color(.37f,.2f,.11f);t.alignment=TextAnchor.MiddleCenter;t.horizontalOverflow=HorizontalWrapMode.Wrap;t.verticalOverflow=VerticalWrapMode.Truncate;t.raycastTarget=false;return t;}
    static RectTransform R(Transform p,string n,float x,float y,float w,float h){var o=new GameObject(n,typeof(RectTransform));o.transform.SetParent(p,false);var r=(RectTransform)o.transform;r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(x,-y);r.sizeDelta=new Vector2(w,h);return r;}
}
public sealed class GuideCircle:MaskableGraphic {public bool Mouth;protected override void OnPopulateMesh(VertexHelper h){h.Clear();var c=rectTransform.rect.center;float radius=rectTransform.rect.width/2;h.AddVert(c,color,Vector2.zero);for(int n=0;n<=32;n++){float a=Mathf.Lerp(Mouth?30:0,Mouth?330:360,n/32f)*Mathf.Deg2Rad;h.AddVert(c+new Vector2(Mathf.Cos(a),Mathf.Sin(a))*radius,color,Vector2.zero);if(n>0)h.AddTriangle(0,n,n+1);}}}
}
