using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
namespace StudentAge.Sanguosha {
 public sealed class Seat {
  public General General;public int Hp,MaxHp,Nightmare;public bool FaceDown,Luoyi,UsedSlash;public int Slashes,Rende;
  public readonly List<Card> Hand=new List<Card>(),Judgments=new List<Card>(),Buqu=new List<Card>();public readonly Card[] Equipment=new Card[4];public readonly HashSet<string> Used=new HashSet<string>();
  public bool Has(string skill)=>General.Has(skill);public IEnumerable<Card> Cards=>Hand.Concat(Equipment.Where(c=>c!=null));public string Weapon=>Equipment[0]?.Kind;public string Armor=>Equipment[1]?.Kind;
  public int Range=>Catalog.Range(Weapon);public bool Wounded=>Hp<MaxHp;
 }
 public sealed class Option {public string Label;public int CardId=-1,Score;internal IEnumerator Action;public Option(string label,int score=0,int card=-1,IEnumerator action=null){Label=label;Score=score;CardId=card;Action=action;}}
 public sealed class Prompt {public int Actor;public string Text;public List<Option> Options;public List<Card> Reveal;public Prompt(int actor,string text,IEnumerable<Option> options,IEnumerable<Card> reveal=null){Actor=actor;Text=text;Options=options.ToList();Reveal=reveal?.ToList();if(Options.Count==0)throw new InvalidOperationException("Empty decision: "+text);}}
 public sealed class MatchEvent {public int Sequence,Actor,Target;public string Text,Sound;public Card Card;}
 // Rules run as a suspended iterator stack. A response never consumes a frame or re-enters a phase.
 // Unity, the AI and tests all submit the same validated prompt choice.
 public sealed class Match {
  public readonly Seat[] Seats=new Seat[2];public readonly List<Card> DrawPile,Discard=new List<Card>();public readonly List<string> Log=new List<string>();public readonly List<MatchEvent> Events=new List<MatchEvent>();
  public readonly bool Easy;public int Turn{get;private set;}public int TurnNumber{get;private set;}public int Winner{get;private set;}=-2;public Prompt Pending{get;private set;}public string Phase{get;private set;}="准备";
  readonly Random random;readonly Stack<IEnumerator> stack=new Stack<IEnumerator>();int answer,serial;Card selected,judged;bool responded,cancelled;readonly HashSet<int> resolving=new HashSet<int>();
  public Match(string player,string opponent,bool easy,int seed){Easy=easy;random=new Random(seed);for(int i=0;i<2;i++){var g=Catalog.Get(i==0?player:opponent);Seats[i]=new Seat{General=g,Hp=g.Hp+(easy?1:0),MaxHp=g.Hp+(easy?1:0)};}DrawPile=Deck.Create();Shuffle(DrawPile);stack.Push(Run());Pump();}
  public void Choose(int index){if(Pending==null||index<0||index>=Pending.Options.Count)throw new ArgumentOutOfRangeException(nameof(index));answer=index;Pending=null;Pump();}
  public int AiChoice(){if(Pending==null)throw new InvalidOperationException();int best=Pending.Options.Max(o=>o.Score);var choices=Pending.Options.Select((v,i)=>new{v,i}).Where(x=>x.v.Score==best).ToArray();return choices[random.Next(choices.Length)].i;}
  public void Surrender(int actor){if(Winner!=-2)return;Winner=1-actor;Pending=null;stack.Clear();Say(actor,1-actor,"认输","lose");}
  void Pump(){int guard=0;while(stack.Count>0&&Winner==-2){if(++guard>10000)throw new InvalidOperationException("Rules loop did not yield");var top=stack.Peek();if(!top.MoveNext()){stack.Pop();continue;}if(top.Current is Prompt p){Pending=p;return;}if(top.Current is IEnumerator e)stack.Push(e);}if(Winner!=-2){Pending=null;stack.Clear();}}
  void Shuffle(List<Card> cards){for(int i=cards.Count-1;i>0;i--){int j=random.Next(i+1);var c=cards[i];cards[i]=cards[j];cards[j]=c;}}
  public void Say(int actor,int target,string text,string sound=null,Card card=null){Log.Add(text);if(Log.Count>70)Log.RemoveAt(0);Events.Add(new MatchEvent{Sequence=++serial,Actor=actor,Target=target,Text=text,Sound=sound,Card=card});if(Events.Count>120)Events.RemoveAt(0);}
  string Name(int a)=>Seats[a].General.Name;Suit SuitOf(int a,Card c)=>Seats[a].Has("hongyan")&&c.Suit==Suit.Spade?Suit.Heart:c.Suit;bool Red(int a,Card c)=>SuitOf(a,c)==Suit.Heart||SuitOf(a,c)==Suit.Diamond;
  string KindOf(int a,Card c)=>Seats[a].Hand.Contains(c)&&Seats[a].Has("wushen")&&SuitOf(a,c)==Suit.Heart?"slash":c.Kind;
  public int Distance(int a,int b)=>Math.Max(1,1+(Seats[b].Equipment[2]!=null?1:0)-(Seats[a].Equipment[3]!=null?1:0)-(Seats[a].Has("mashu")?1:0));
  Card Top(){if(DrawPile.Count==0){DrawPile.AddRange(Discard.Where(c=>!resolving.Contains(c.Id)));Discard.RemoveAll(c=>!resolving.Contains(c.Id));Shuffle(DrawPile);}if(DrawPile.Count==0)return null;var c=DrawPile[0];DrawPile.RemoveAt(0);return c;}
  void Draw(int a,int n){for(int i=0;i<n;i++){var c=Top();if(c!=null)Seats[a].Hand.Add(c);}Say(a,a,Name(a)+"摸"+n+"张牌","choose-item");}
  int Value(int a,Card c){string k=KindOf(a,c);return k=="peach"?(Seats[a].Wounded?10:7):k=="jink"?7:k=="nullification"?7:k=="ex_nihilo"?10:k=="slash"?5:c.Equip?4:6;}
  IEnumerator Yes(int a,string text,int score=5){yield return new Prompt(a,text,new[]{new Option("发动",score),new Option("取消",0)});if(answer==0){var skill=Seats[a].General.Skills.Split(' ').FirstOrDefault(key=>text.StartsWith(Catalog.SkillName(key)+"："));if(skill!=null)Say(a,a,Name(a)+"发动"+Catalog.SkillName(skill),skill);}}
  IEnumerator Pick(int a,string text,IEnumerable<Card> cards,bool optional=false,bool publicFaces=true,bool wantGood=false){var list=cards.ToList();selected=null;if(list.Count==0)yield break;var choices=list.Select(c=>new Option(c.Text,wantGood?Value(a,c):10-Value(a,c),c.Id)).ToList();if(optional)choices.Add(new Option("取消",-1));yield return new Prompt(a,text,choices,publicFaces?list:null);selected=answer<list.Count?list[answer]:null;}
  IEnumerator Lose(int a,Card c,bool discard=true){if(c==null)yield break;var p=Seats[a];bool hand=p.Hand.Remove(c),equip=false;int slot=Array.IndexOf(p.Equipment,c);if(slot>=0){p.Equipment[slot]=null;equip=true;}p.Judgments.Remove(c);if(discard&&!Discard.Contains(c))Discard.Add(c.Physical);
   if(hand&&p.Hand.Count==0&&p.Has("lianying")){yield return Yes(a,"连营：摸一张牌");if(answer==0)Draw(a,1);}if(equip&&p.Has("xiaoji")){yield return Yes(a,"枭姬：摸两张牌");if(answer==0)Draw(a,2);}}
  IEnumerator Recover(int a,int n){var p=Seats[a];int old=p.Hp;p.Hp=Math.Min(p.MaxHp,p.Hp+n);int removed=Math.Max(0,p.Buqu.Count-Math.Max(0,1-p.Hp));while(removed-->0){yield return Pick(a,"不屈：移去一张不屈牌",p.Buqu);p.Buqu.Remove(selected);Discard.Add(selected.Physical);}if(p.Hp>old)Say(a,a,Name(a)+"回复"+(p.Hp-old)+"点体力","peach");}
  IEnumerator Judge(int a,string reason,Func<Card,bool> good){judged=Top();if(judged==null)yield break;Card current=judged;Say(a,a,Name(a)+"判定："+reason+" · "+current.Text,"choose-item",current);
   for(int k=0;k<2;k++){int b=(Turn+k)%2;var p=Seats[b];bool own=b==a;var eligible=p.Has("guicai")?p.Hand.ToList():p.Has("guidao")?p.Cards.Where(c=>!Red(b,c)).ToList():new List<Card>();if(eligible.Count==0)continue;
    var opts=new List<Option>{new Option("不改判",0)};opts.AddRange(eligible.Select(c=>new Option(c.Text,(good(c)==own?12:-12)-Value(b,c),c.Id)));yield return new Prompt(b,reason+"：当前判定 "+current.Text+"，是否改判？",opts,new[]{current}.Concat(eligible));if(answer>0){Card repl=eligible[answer-1];yield return Lose(b,repl,false);if(p.Has("guidao"))p.Hand.Add(current.Physical);else Discard.Add(current.Physical);current=repl;Say(b,a,Name(b)+"改判为 "+current.Text,p.Has("guidao")?"guidao":"guicai",current);}}
   judged=current;
  }
  IEnumerator DisposeJudge(int a,Card c,bool obtained=false){if(c==null||obtained)yield break;if(Seats[a].Has("tiandu")){yield return Yes(a,"天妒：获得判定牌 "+c.Text);if(answer==0){Seats[a].Hand.Add(c);yield break;}}Discard.Add(c.Physical);}
  IEnumerator Run(){Draw(0,4);Draw(1,4);while(Winner==-2){TurnNumber++;if(TurnNumber>600){Winner=-1;Say(-1,-1,"牌局达到600回合，和局");yield break;}yield return Round(Turn);Turn=1-Turn;}}
  IEnumerator Round(int a){var p=Seats[a];int b=1-a;Phase="准备阶段";Say(a,a,"—— "+Name(a)+"的回合 ——");p.Slashes=0;p.Rende=0;p.Used.Clear();p.Luoyi=p.UsedSlash=false;if(p.FaceDown){p.FaceDown=false;Say(a,a,Name(a)+"翻回正面，跳过本回合");yield break;}
   if(p.Has("guanxing")){yield return Yes(a,"观星：观看牌堆顶两张牌");if(answer==0){var peek=new List<Card>();for(int i=0;i<2;i++){var c=Top();if(c!=null)peek.Add(c);}var top=new List<Card>();while(peek.Count>0){yield return Pick(a,"观星：选择下一张牌（先选的靠近牌堆顶）",peek,false,true,true);var c=selected;peek.Remove(c);yield return new Prompt(a,c.Text+"放到哪里？",new[]{new Option("牌堆顶",Value(a,c)),new Option("牌堆底",5)},new[]{c});if(answer==0)top.Add(c);else DrawPile.Add(c.Physical);}DrawPile.InsertRange(0,top);}}
   if(p.Has("luoshen")){for(int i=0;i<108;i++){yield return Yes(a,"洛神：继续判定，黑色牌收入手牌");if(answer!=0)break;yield return Judge(a,"洛神",c=>!Red(a,c));var c=judged;bool black=c!=null&&!Red(a,c);if(black)p.Hand.Add(c.Physical);yield return DisposeJudge(a,c,black);if(!black)break;}}
   bool fast=false;if(p.Has("shensu")&&Targetable(a,b,"slash")){yield return Yes(a,"神速：跳过判定和摸牌，使用一张杀",p.Judgments.Count>0?12:-2);fast=answer==0;if(fast)yield return Slash(a,b,null,true);}
   bool skip=false;if(!fast){Phase="判定阶段";foreach(var delayed in p.Judgments.ToArray().Reverse()){p.Judgments.Remove(delayed);yield return Nullify(a,delayed.Kind);bool nullified=cancelled;if(!nullified){if(delayed.Kind=="indulgence"){yield return Judge(a,"乐不思蜀",c=>SuitOf(a,c)==Suit.Heart);var c=judged;skip=c!=null&&SuitOf(a,c)!=Suit.Heart;yield return DisposeJudge(a,c);Discard.Add(delayed.Physical);}else{yield return Judge(a,"闪电",c=>!(SuitOf(a,c)==Suit.Spade&&c.Rank>=2&&c.Rank<=9));var c=judged;bool hit=c!=null&&SuitOf(a,c)==Suit.Spade&&c.Rank>=2&&c.Rank<=9;yield return DisposeJudge(a,c);if(hit){Discard.Add(delayed.Physical);yield return Damage(-1,a,3,delayed,"lightning");}else if(!Seats[b].Judgments.Any(x=>x.Kind=="lightning"))Seats[b].Judgments.Add(delayed);else Discard.Add(delayed.Physical);}}else if(delayed.Kind=="lightning"&&!Seats[b].Judgments.Any(x=>x.Kind=="lightning"))Seats[b].Judgments.Add(delayed);else Discard.Add(delayed.Physical);}
    Phase="摸牌阶段";bool replaced=false;if(p.Has("shelie")){yield return Yes(a,"涉猎：改为亮出五张牌，每种花色获得一张",9);if(answer==0){replaced=true;var cards=new List<Card>();for(int i=0;i<5;i++){var c=Top();if(c!=null)cards.Add(c);}while(cards.Count>0){yield return Pick(a,"涉猎：每种花色取一张",cards,false,true,true);Card c=selected;p.Hand.Add(c.Physical);cards.Remove(c);var rest=cards.Where(x=>SuitOf(a,x)==SuitOf(a,c)).ToArray();foreach(var r in rest){cards.Remove(r);Discard.Add(r.Physical);}}}}
    if(p.Has("tuxi")&&Seats[b].Hand.Count>0){yield return Yes(a,"突袭：放弃摸牌，获得对手一张手牌",Seats[b].Hand.Count<=2?10:2);if(answer==0){replaced=true;Card c=Seats[b].Hand[random.Next(Seats[b].Hand.Count)];yield return Lose(b,c,false);p.Hand.Add(c.Physical);}}
    if(!replaced){int n=Easy?3:2;if(p.Has("yingzi")){yield return Yes(a,"英姿：额外摸一张牌");if(answer==0)n++;}if(p.Has("luoyi")){yield return Yes(a,"裸衣：少摸一张，本回合杀与决斗伤害+1",p.Hand.Count(c=>KindOf(a,c)=="slash"||KindOf(a,c)=="duel")>0?8:-2);if(answer==0){n--;p.Luoyi=true;}}Draw(a,n);}}
   if(p.Has("shensu")&&p.Cards.Any(c=>c.Equip)&&Targetable(a,b,"slash")){yield return Yes(a,"神速：弃一张装备牌，跳过出牌阶段并出杀",skip?10:-5);if(answer==0){yield return Pick(a,"神速：弃置装备牌",p.Cards.Where(c=>c.Equip));yield return Lose(a,selected);skip=true;yield return Slash(a,b,null,true);}}
   Phase="出牌阶段";if(!skip){while(Winner==-2){var options=PlayOptions(a);options.Add(new Option("结束出牌",0));var prompt=new Prompt(a,Name(a)+" · 出牌阶段",options);yield return prompt;var chosen=prompt.Options[answer];if(chosen.Action==null)break;yield return chosen.Action;}}
   Phase="弃牌阶段";if(!(p.Has("keji")&&!p.UsedSlash)){int max=Math.Max(0,p.Hp);while(p.Hand.Count>max){yield return Pick(a,"弃牌至"+max+"张（还需弃"+(p.Hand.Count-max)+"张）",p.Hand);yield return Lose(a,selected);}}
   Phase="结束阶段";if(p.Has("biyue")){yield return Yes(a,"闭月：摸一张牌");if(answer==0)Draw(a,1);}if(p.Has("jushou")){yield return Yes(a,"据守：摸三张牌并翻面",p.Hp<=2&&p.Hand.Count<2?6:-3);if(answer==0){Draw(a,3);p.FaceDown=true;}}p.Luoyi=false;
  }
  bool Targetable(int a,int b,string kind){var p=Seats[b];if((kind=="slash"||kind=="duel")&&p.Has("kongcheng")&&p.Hand.Count==0)return false;if((kind=="snatch"||kind=="indulgence")&&p.Has("qianxun"))return false;return true;}
  bool CanSlash(int a)=>Seats[a].Has("paoxiao")||Seats[a].Weapon=="crossbow"||Seats[a].Slashes<(Easy?2:1);
  bool InRange(int a,int b,Card c=null)=>Distance(a,b)+(c!=null&&c==Seats[a].Equipment[3]?1:0)<=(c!=null&&c==Seats[a].Equipment[0]?1:Seats[a].Range)||(c!=null&&Seats[a].Has("wushen")&&SuitOf(a,c)==Suit.Heart);
  bool Legal(int a,string k,Card c){int b=1-a;var p=Seats[a];var q=Seats[b];if(k=="jink"||k=="nullification")return false;if(k=="slash")return CanSlash(a)&&Targetable(a,b,k)&&InRange(a,b,c);if(k=="peach")return p.Wounded;if(Catalog.Slot(k)>=0)return true;if(!Targetable(a,b,k))return false;if(k=="snatch")return q.Cards.Any()||q.Judgments.Count>0?(p.Has("qicai")||Distance(a,b)<=1):false;if(k=="dismantlement")return q.Cards.Any()||q.Judgments.Count>0||p.Judgments.Count>0;if(k=="collateral")return q.Weapon!=null&&Targetable(b,a,"slash")&&InRange(b,a);if(k=="indulgence")return !q.Judgments.Any(x=>x.Kind==k);if(k=="lightning")return !p.Judgments.Any(x=>x.Kind==k);return true;}
  List<Option> PlayOptions(int a){var p=Seats[a];var opts=new List<Option>();foreach(var c in p.Hand.ToArray()){string k=KindOf(a,c);if(Legal(a,k,c))opts.Add(new Option(c.Text,PlayScore(a,k,c),c.Id,Use(a,c,k)));foreach(string v in Converted(a,c,false)){if(v!=k&&Legal(a,v,c))opts.Add(new Option(c.Text+" → "+Catalog.CardName(v),PlayScore(a,v,c)-1,c.Id,Use(a,c,v)));}}
   foreach(var c in p.Equipment.Where(c=>c!=null).ToArray())foreach(string k in Converted(a,c,false))if(Legal(a,k,c))opts.Add(new Option(c.Text+" → "+Catalog.CardName(k),PlayScore(a,k,c)-2,c.Id,Use(a,c,k)));
   foreach(string skill in new[]{"zhiheng","kurou","rende","qingnang","jieyin","fanjian","gongxin"}){bool enabled=p.Has(skill)&&(!p.Used.Contains(skill)||skill=="kurou"||skill=="rende");if(skill=="zhiheng")enabled&=p.Cards.Any();if(skill=="kurou")enabled&=p.Hp>0;if(skill=="rende"||skill=="qingnang"||skill=="fanjian")enabled&=p.Hand.Count>0;if(skill=="qingnang")enabled&=p.Wounded||Seats[1-a].Wounded;if(skill=="jieyin")enabled&=p.Hand.Count>=2&&!Seats[1-a].General.Female&&Seats[1-a].Wounded;if(skill=="gongxin")enabled&=Seats[1-a].Hand.Count>0;if(enabled)opts.Add(new Option(SkillName(skill),SkillScore(a,skill),-1,Active(a,skill)));}
   if(p.Weapon=="spear"&&p.Hand.Count>=2&&CanSlash(a)&&Targetable(a,1-a,"slash")&&InRange(a,1-a))opts.Add(new Option("丈八蛇矛：两张手牌当杀",p.Hand.Any(c=>KindOf(a,c)=="slash")?-2:4,-1,Spear(a)));
   if(p.Has("guhuo")&&p.Hand.Count>0)foreach(string k in new[]{"slash","peach","ex_nihilo","duel","dismantlement","snatch","savage_assault","archery_attack","amazing_grace","god_salvation","collateral"})if(Legal(a,k,null))opts.Add(new Option("蛊惑 · "+Catalog.CardName(k),p.Hand.Any(c=>KindOf(a,c)==k)?3:-2,-1,BluffUse(a,k)));
   return opts;
  }
  int PlayScore(int a,string k,Card c){var p=Seats[a];if(k=="peach")return 20;if(k=="ex_nihilo")return 18;if(k=="slash"||k=="duel")return 8;if(k=="lightning")return -3;if(k=="god_salvation")return p.Wounded&&!Seats[1-a].Wounded?8:-2;if(k=="amazing_grace")return 2;if(c!=null&&c.Equip){var old=p.Equipment[c.Slot];return old==null?11:old.Kind==c.Kind?-3:Catalog.Range(c.Kind)>Catalog.Range(old.Kind)?6:-1;}return 7;}
  int SkillScore(int a,string k){var p=Seats[a];if(k=="kurou")return p.Hp>=3&&p.Hand.Count<4?5:-4;if(k=="rende")return p.Wounded&&p.Rende<2&&p.Hand.Count>=2-p.Rende?3:-6;if(k=="qingnang")return p.Wounded?9:-6;if(k=="jieyin")return p.Wounded?4:-5;if(k=="zhiheng")return 1;return 7;}
  static string SkillName(string k){string[] keys={"zhiheng","kurou","rende","qingnang","jieyin","fanjian","gongxin"},v={"制衡","苦肉","仁德","青囊","结姻","反间","攻心"};return v[Array.IndexOf(keys,k)];}
  IEnumerable<string> Converted(int a,Card c,bool response){var p=Seats[a];if(p.Has("wushen")&&p.Hand.Contains(c)&&SuitOf(a,c)==Suit.Heart)yield break;if(p.Has("longdan")&&p.Hand.Contains(c)){if(c.Kind=="slash")yield return "jink";if(c.Kind=="jink")yield return "slash";}if(p.Has("wusheng")&&Red(a,c))yield return "slash";if(p.Has("qingguo")&&p.Hand.Contains(c)&&!Red(a,c))yield return "jink";if(p.Has("jijiu")&&Turn!=a&&Red(a,c))yield return "peach";if(!response){if(p.Has("qixi")&&!Red(a,c))yield return "dismantlement";if(p.Has("guose")&&SuitOf(a,c)==Suit.Diamond)yield return "indulgence";}}
  IEnumerator Nullify(int target,string trick,bool beneficial=false){bool negated=false;int passes=0,a=target;while(passes<2){var p=Seats[a];var cards=p.Hand.Where(c=>KindOf(a,c)=="nullification").ToList();bool bluff=p.Has("guhuo")&&p.Hand.Count>0;if(cards.Count>0||bluff){bool wants=((a==target)!=negated)!=beneficial;var opts=new List<Option>{new Option("不使用",0)};opts.AddRange(cards.Select(c=>new Option(c.Text,wants?7:-8,c.Id)));if(bluff)opts.Add(new Option("蛊惑 · 无懈可击",wants&&p.Hand.Any(c=>c.Kind=="nullification")?5:-3,-3));yield return new Prompt(a,Catalog.CardName(trick)+(negated?"已被无懈，是否反无懈？":"：是否使用无懈可击？"),opts);if(answer>0){bool success=true;if(opts[answer].CardId==-3){yield return Bluff(a,"nullification");success=responded;}else{var c=cards[answer-1];yield return Lose(a,c);Say(a,target,Name(a)+"使用无懈可击","nullification",c);if(p.Has("jizhi")){yield return Yes(a,"集智：摸一张牌");if(answer==0)Draw(a,1);}}if(success){negated=!negated;passes=0;}else passes++;}else passes++;}else passes++;a=1-a;}cancelled=negated;}
  IEnumerator Use(int a,Card c,string kind,bool alreadyLost=false){int b=1-a;var p=Seats[a];if(kind=="slash"){p.Slashes++;p.UsedSlash=true;}if(c!=null&&!alreadyLost){resolving.Add(c.Id);yield return Lose(a,c);}Say(a,b,Name(a)+"使用"+Catalog.CardName(kind),kind,c);
   if(Catalog.Slot(kind)>=0){int slot=Catalog.Slot(kind);if(p.Equipment[slot]!=null)yield return Lose(a,p.Equipment[slot]);Discard.Remove(c);p.Equipment[slot]=c;}
   else if(kind=="slash")yield return Slash(a,b,c);
   else if(kind=="peach")yield return Recover(a,1);
   else{if(kind!="indulgence"&&kind!="lightning"&&p.Has("jizhi")){yield return Yes(a,"集智：摸一张牌");if(answer==0)Draw(a,1);}
    int target=kind=="ex_nihilo"||kind=="lightning"?a:b;
    if(kind=="amazing_grace"||kind=="god_salvation"){var pool=new List<Card>();if(kind=="amazing_grace")for(int i=0;i<2;i++){var card=Top();if(card!=null)pool.Add(card);}for(int i=0;i<2;i++){int who=(a+i)%2;yield return Nullify(who,kind,true);if(cancelled)continue;if(kind=="god_salvation")yield return Recover(who,1);else if(pool.Count>0){yield return Pick(who,"五谷丰登：选择一张牌",pool,false,true,true);Seats[who].Hand.Add(selected);pool.Remove(selected);}}Discard.AddRange(pool);}
    else{if(kind=="indulgence"||kind=="lightning")cancelled=false;else yield return Nullify(target,kind,kind=="ex_nihilo");if(!cancelled){switch(kind){case "ex_nihilo":Draw(a,2);break;case "duel":yield return Duel(a,b,c);break;case "savage_assault":case "archery_attack":yield return Respond(b,kind=="savage_assault"?"slash":"jink",a,false);if(!responded)yield return Damage(a,b,1,c,kind);break;
     case "snatch":case "dismantlement":yield return Steal(a,b,kind=="dismantlement",true);break;
     case "indulgence":case "lightning":if(c!=null){Discard.Remove(c);Seats[target].Judgments.Add(c.Kind==kind?c:new Card(c.Id,kind,c.Suit,c.Rank,c.PrintedKind));}break;
     case "collateral":yield return Respond(b,"slash",a,false);if(responded)yield return Slash(b,a,null);else if(Seats[b].Equipment[0]!=null){var w=Seats[b].Equipment[0];yield return Lose(b,w,false);p.Hand.Add(w.Physical);}break;
    }}}}
   if(c!=null)resolving.Remove(c.Id);
  }
  IEnumerator Steal(int a,int b,bool destroy,bool includeJudgments){var q=Seats[b];var visible=q.Equipment.Where(c=>c!=null).Concat(includeJudgments?q.Judgments:Enumerable.Empty<Card>()).ToList();var options=new List<Option>();if(q.Hand.Count>0)options.Add(new Option("对手随机手牌",5));options.AddRange(visible.Select(c=>new Option(c.Text,c.Delayed?-4:8,c.Id)));var own=destroy?Seats[a].Judgments.ToList():new List<Card>();options.AddRange(own.Select(c=>new Option("自己的 "+c.Text,12,c.Id)));if(options.Count==0)yield break;yield return new Prompt(a,destroy?"过河拆桥：弃置一张牌":"获得对手一张牌",options,visible.Concat(own));var opt=options[answer];Card take;int from=b;if(opt.CardId<0)take=q.Hand[random.Next(q.Hand.Count)];else{take=visible.Concat(own).First(x=>x.Id==opt.CardId);if(own.Contains(take))from=a;}yield return Lose(from,take,destroy);if(!destroy)Seats[a].Hand.Add(take.Physical);}
  IEnumerator Respond(int a,string kind,int source,bool armor){var p=Seats[a];responded=false;
   if(kind=="jink"&&armor&&p.Armor=="eight_diagram"){yield return Yes(a,"八卦阵：判定，红色视为使用闪");if(answer==0){yield return Judge(a,"八卦阵",c=>Red(a,c));var j=judged;bool ok=j!=null&&Red(a,j);yield return DisposeJudge(a,j);if(ok){yield return JinkTrigger(a);responded=true;yield break;}}}
   var cards=p.Cards.Where(c=>(p.Hand.Contains(c)&&KindOf(a,c)==kind)||Converted(a,c,true).Contains(kind)).ToList();var options=cards.Select(c=>new Option(c.Text+(c.Kind!=kind?" → "+Catalog.CardName(kind):""),(kind=="peach"&&source!=a?-20:20)-Value(a,c),c.Id)).ToList();if(kind=="slash"&&p.Weapon=="spear"&&p.Hand.Count>=2)options.Add(new Option("丈八蛇矛",5,-2));if(p.Has("guhuo")&&p.Hand.Count>0)options.Add(new Option("蛊惑 · "+Catalog.CardName(kind),kind=="peach"&&source!=a?-20:2,-3));options.Add(new Option("放弃响应",-4));yield return new Prompt(a,"请打出"+Catalog.CardName(kind),options);
   var chosen=options[answer];if(chosen.CardId>=0){var c=cards.First(x=>x.Id==chosen.CardId);yield return Lose(a,c);Say(a,source,Name(a)+"打出"+Catalog.CardName(kind),kind,c);if(kind=="slash"&&Turn==a&&Phase=="出牌阶段")p.UsedSlash=true;if(kind=="jink")yield return JinkTrigger(a);responded=true;}
   else if(chosen.CardId==-2){for(int i=0;i<2;i++){yield return Pick(a,"丈八蛇矛：弃置手牌 "+(i+1)+"/2",p.Hand);yield return Lose(a,selected);}if(Turn==a&&Phase=="出牌阶段")p.UsedSlash=true;responded=true;}
   else if(chosen.CardId==-3){yield return Bluff(a,kind);bool ok=responded;if(ok&&kind=="jink")yield return JinkTrigger(a);responded=ok;}
  }
  IEnumerator JinkTrigger(int a){if(!Seats[a].Has("leiji"))yield break;yield return Yes(a,"雷击：令对手判定，黑桃造成2点雷电伤害");if(answer!=0)yield break;int b=1-a;yield return Judge(b,"雷击",c=>SuitOf(b,c)!=Suit.Spade);var j=judged;bool hit=j!=null&&SuitOf(b,j)==Suit.Spade;yield return DisposeJudge(b,j);if(hit)yield return Damage(a,b,2,null,"leiji");}
  IEnumerator Slash(int a,int b,Card c,bool ignoreRange=false){var p=Seats[a];var q=Seats[b];if(!Targetable(a,b,"slash"))yield break;bool ignoreArmor=p.Weapon=="qinggang_sword";bool hit=false;
   if(p.Weapon=="double_sword"&&p.General.Female!=q.General.Female){yield return Yes(a,"雌雄双股剑：令对手弃一张手牌，否则你摸一张");if(answer==0){yield return Pick(b,"弃一张手牌，或取消让对手摸一张",q.Hand,true);if(selected==null)Draw(a,1);else yield return Lose(b,selected);}}
   if(p.Has("tieji")){yield return Yes(a,"铁骑：判定为红色则此杀不可闪避");if(answer==0){yield return Judge(a,"铁骑",j=>Red(a,j));var j=judged;hit=j!=null&&Red(a,j);yield return DisposeJudge(a,j);}}
   if(p.Has("liegong")&&Turn==a&&Phase=="出牌阶段"&&(q.Hand.Count>=p.Hp||q.Hand.Count<=p.Range)){yield return Yes(a,"烈弓：此杀不可闪避");if(answer==0)hit=true;}
   if(!ignoreArmor&&q.Armor=="renwang_shield"&&c!=null&&!Red(a,c)){Say(b,a,"仁王盾抵消黑色杀");yield break;}
   bool dodged=false;if(!hit){int need=p.Has("wushuang")?2:1;dodged=true;for(int i=0;i<need;i++){yield return Respond(b,"jink",a,!ignoreArmor);if(!responded){dodged=false;break;}}}
   if(dodged&&p.Weapon=="axe"&&p.Cards.Count(x=>x!=p.Equipment[0])>=2){yield return Yes(a,"贯石斧：弃两张牌使杀命中",q.Hp<=1?12:3);if(answer==0){for(int i=0;i<2;i++){yield return Pick(a,"贯石斧：弃置牌 "+(i+1)+"/2",p.Cards.Where(x=>x!=p.Equipment[0]));yield return Lose(a,selected);}dodged=false;}}
   if(dodged){if(p.Weapon=="blade"){yield return Yes(a,"青龙偃月刀：继续出杀",7);if(answer==0){yield return Respond(a,"slash",b,false);if(responded)yield return Slash(a,b,null);}}yield break;}
   if(p.Weapon=="ice_sword"&&q.Cards.Any()){yield return Yes(a,"寒冰剑：不造成伤害，改为弃对手两张牌",q.Cards.Count()>=2&&q.Hp>1?7:-4);if(answer==0){for(int i=0;i<2&&q.Cards.Any();i++)yield return Steal(a,b,true,false);yield break;}}
   if(p.Weapon=="kylin_bow"&&(q.Equipment[2]!=null||q.Equipment[3]!=null)){yield return Yes(a,"麒麟弓：弃置对手一匹马");if(answer==0){yield return Pick(a,"麒麟弓：选择马",q.Equipment.Skip(2).Where(x=>x!=null));yield return Lose(b,selected);}}
   yield return Damage(a,b,1+(p.Luoyi?1:0),c,"slash");
  }
  IEnumerator Duel(int a,int b,Card c){int who=b,other=a;for(int count=0;count<216;count++){int need=Seats[other].Has("wushuang")?2:1;for(int i=0;i<need;i++){yield return Respond(who,"slash",other,false);if(!responded){yield return Damage(other,who,1+(Seats[other].Luoyi?1:0),c,"duel");yield break;}}int swap=who;who=other;other=swap;}}
  IEnumerator Damage(int a,int b,int amount,Card card,string reason,int depth=0){if(amount<=0||depth>100)yield break;var q=Seats[b];bool transfer=false;if(q.Has("tianxiang")&&q.Hand.Any(c=>SuitOf(b,c)==Suit.Heart)){yield return Yes(b,"天香：弃一张红桃手牌，将"+amount+"点伤害转给对手",9);if(answer==0){yield return Pick(b,"天香：弃置红桃手牌",q.Hand.Where(c=>SuitOf(b,c)==Suit.Heart));yield return Lose(b,selected);transfer=true;yield return Damage(a,1-b,amount,card,reason,depth+1);if(Winner==-2)Draw(1-b,Math.Max(0,Seats[1-b].MaxHp-Seats[1-b].Hp));}}if(transfer)yield break;
   int distance=a<0?99:Distance(a,b);if(q.Has("wuhun")&&a>=0)Seats[a].Nightmare+=amount;q.Hp-=amount;Say(a,b,Name(b)+"受到"+amount+"点伤害","injure1",card);yield return Dying(b,a);
   if(Winner!=-2)yield break;if(a>=0&&Seats[a].Has("kuanggu")&&distance<=1)yield return Recover(a,amount);
   if(q.Has("jianxiong")&&card!=null&&Discard.Any(x=>x.Id==card.Id)){yield return Yes(b,"奸雄：获得伤害牌 "+card.Name);if(answer==0){var take=Discard.First(x=>x.Id==card.Id);Discard.Remove(take);q.Hand.Add(take.Physical);}}
   if(q.Has("fankui")&&a>=0&&Seats[a].Cards.Any()){yield return Yes(b,"反馈：获得伤害来源一张牌");if(answer==0)yield return Steal(b,a,false,false);}
   for(int i=0;i<amount;i++){if(i==0&&q.Has("ganglie")&&a>=0){yield return Yes(b,"刚烈：判定为非红桃，令伤害来源弃两张手牌或受到1点伤害");if(answer==0){yield return Judge(b,"刚烈",j=>SuitOf(b,j)!=Suit.Heart);var j=judged;bool hit=j!=null&&SuitOf(b,j)!=Suit.Heart;yield return DisposeJudge(b,j);if(hit){bool discard=false;if(Seats[a].Hand.Count>=2){yield return new Prompt(a,"刚烈：选择",new[]{new Option("弃置两张手牌",Seats[a].Hp<=2?8:0),new Option("受到1点伤害",3)});discard=answer==0;}if(discard)for(int n=0;n<2;n++){yield return Pick(a,"刚烈：弃手牌 "+(n+1)+"/2",Seats[a].Hand);yield return Lose(a,selected);}else yield return Damage(b,a,1,null,"ganglie",depth+1);}}}
    if(q.Has("yiji")){yield return Yes(b,"遗计：摸两张牌，可将牌交给对手");if(answer==0){var old=new HashSet<int>(q.Hand.Select(c=>c.Id));Draw(b,2);var gains=q.Hand.Where(c=>!old.Contains(c.Id)).ToArray();foreach(var c in gains){yield return new Prompt(b,"遗计："+c.Text,new[]{new Option("自己保留",8),new Option("交给对手",-4)},new[]{c});if(answer==1){yield return Lose(b,c,false);Seats[1-b].Hand.Add(c);}}}}
   }
  }
  IEnumerator Dying(int a,int source){var p=Seats[a];if(p.Hp>0)yield break;if(p.Has("buqu")){yield return Yes(a,"不屈：展开不屈牌，点数不重复则继续存活",20);if(answer==0){while(p.Buqu.Count<1-p.Hp){var c=Top();if(c==null)break;p.Buqu.Add(c);}if(p.Buqu.Count==1-p.Hp&&p.Buqu.Select(c=>c.Rank).Distinct().Count()==p.Buqu.Count){Say(a,a,"不屈生效，仍然存活");yield break;}}}
   for(int k=0;k<2&&p.Hp<=0;k++){int who=(a+k)%2;while(p.Hp<=0){yield return Respond(who,"peach",a,false);if(!responded)break;yield return Recover(a,1);}}
   if(p.Hp>0)yield break;Say(a,1-a,Name(a)+"阵亡","lose");bool revenge=false;if(p.Has("wuhun")&&Seats[1-a].Nightmare>0){Say(a,1-a,"武魂 · 索命","wuhun");yield return Judge(1-a,"武魂",c=>c.Kind=="peach"||c.Kind=="god_salvation");var j=judged;revenge=j!=null&&j.Kind!="peach"&&j.Kind!="god_salvation";yield return DisposeJudge(1-a,j);}Winner=revenge?-1:1-a;
  }
  IEnumerator HpLoss(int a,int n){Seats[a].Hp-=n;Say(a,a,Name(a)+"失去"+n+"点体力","hplost");yield return Dying(a,-1);}
  IEnumerator Spear(int a){for(int i=0;i<2;i++){yield return Pick(a,"丈八蛇矛：选择手牌 "+(i+1)+"/2",Seats[a].Hand);yield return Lose(a,selected);}yield return Use(a,null,"slash",true);}
  IEnumerator Bluff(int a,string kind){var p=Seats[a];yield return Pick(a,"蛊惑：暗置一张手牌，声明"+Catalog.CardName(kind),p.Hand);var c=selected;bool truthful=KindOf(a,c)==kind;yield return Lose(a,c);yield return new Prompt(1-a,Name(a)+"蛊惑声明："+Catalog.CardName(kind),new[]{new Option("不质疑",3),new Option("质疑",Seats[1-a].Hp>2?3:-2)});bool question=answer==1;Say(a,1-a,"蛊惑揭示 "+c.Text,"guhuo",c);if(question){if(truthful)yield return HpLoss(1-a,1);else Draw(1-a,1);}selected=c;responded=!question||(truthful&&SuitOf(a,c)==Suit.Heart);}
  IEnumerator BluffUse(int a,string kind){yield return Bluff(a,kind);var c=selected;if(responded)yield return Use(a,c,kind,true);}
  IEnumerator Active(int a,string skill){var p=Seats[a];int b=1-a;var q=Seats[b];p.Used.Add(skill);Say(a,b,Name(a)+"发动"+SkillName(skill),skill);
   switch(skill){case "kurou":yield return HpLoss(a,1);if(Winner==-2)Draw(a,2);break;
    case "zhiheng":{var chosen=new List<Card>();while(true){var available=p.Cards.Except(chosen).ToArray();if(available.Length==0)break;var options=available.Select(c=>new Option(c.Text,6-Value(a,c),c.Id)).ToList();options.Add(new Option(chosen.Count==0?"取消":"确定，换"+chosen.Count+"张",0));yield return new Prompt(a,"制衡：选择任意张牌",options,available);if(answer==available.Length)break;chosen.Add(available[answer]);}foreach(var c in chosen)yield return Lose(a,c);Draw(a,chosen.Count);break;}
    case "rende":yield return Pick(a,"仁德：交给对手一张手牌",p.Hand);var given=selected;yield return Lose(a,given,false);q.Hand.Add(given.Physical);p.Rende++;if(p.Rende==2)yield return Recover(a,1);break;
    case "qingnang":yield return Pick(a,"青囊：弃一张手牌",p.Hand);yield return Lose(a,selected);var targets=new List<int>();if(p.Wounded)targets.Add(a);if(q.Wounded)targets.Add(b);yield return new Prompt(a,"青囊：选择回复体力的角色",targets.Select(t=>new Option(Name(t),t==a?10:-5)));yield return Recover(targets[answer],1);break;
    case "jieyin":for(int i=0;i<2;i++){yield return Pick(a,"结姻：弃手牌 "+(i+1)+"/2",p.Hand);yield return Lose(a,selected);}yield return Recover(a,1);yield return Recover(b,1);break;
    case "fanjian":yield return new Prompt(b,"反间：猜测将获得的牌的花色",new[]{new Option("黑桃",1),new Option("梅花",1),new Option("红桃",1),new Option("方块",1)});Suit guessed=(Suit)answer;var card=p.Hand[random.Next(p.Hand.Count)];yield return Lose(a,card,false);q.Hand.Add(card.Physical);Say(a,b,"反间揭示 "+card.Text,"fanjian",card);if(SuitOf(b,card)!=guessed)yield return Damage(a,b,1,null,"fanjian");break;
    case "gongxin":var hearts=q.Hand.Where(c=>SuitOf(b,c)==Suit.Heart).ToArray();var choices=hearts.Select(c=>new Option(c.Text,7,c.Id)).ToList();choices.Add(new Option("不处理",0));yield return new Prompt(a,"攻心：查看对手手牌，选择一张红桃",choices,q.Hand);if(answer>=hearts.Length)break;var heart=hearts[answer];yield return new Prompt(a,heart.Text+"：如何处理？",new[]{new Option("弃置",8),new Option("放回牌堆顶",Turn==a?-2:4)});bool toTop=answer==1;yield return Lose(b,heart,!toTop);if(toTop)DrawPile.Insert(0,heart.Physical);break;
   }
  }
 }
}
