using System;using System.Diagnostics;using System.IO;using System.Net;using System.Threading;using System.Threading.Tasks;using BepInEx;using BepInEx.Configuration;using BepInEx.Logging;using StudentAge.CampusUpdates;
namespace StudentAge.CampusUno {
public static class CampusVersion {public const string Value="0.9.4";public const string Repository="360478712scy-gif/StudentAge-CampusMinigames";}
internal sealed class CampusAutoUpdate {
 readonly CancellationTokenSource cancel=new CancellationTokenSource();readonly ManualLogSource log;readonly string root,cache;readonly int interval;readonly bool enabled;
 internal CampusAutoUpdate(ConfigFile config,ManualLogSource logger){log=logger;enabled=config.Bind("Updates","Enabled",true,"后台自动检查并下载本插件更新，退出游戏后安装；不会修改存档与cfg。关闭后不联网。").Value;interval=config.Bind("Updates","CheckIntervalHours",6,new ConfigDescription("两次检查之间的小时数；断网不影响游戏。",new AcceptableValueRange<int>(1,168))).Value;root=Paths.PluginPath;cache=Path.Combine(Paths.BepInExRootPath,"cache","CampusMinigamesUpdates");}
 internal void Start(){if(enabled&&Plugin.UpPresent)Task.Run(async()=>{try{await Task.Delay(5000,cancel.Token).ConfigureAwait(false);Run();}catch(OperationCanceledException){}catch(Exception e){log.LogWarning("小游戏自动更新暂未完成，游戏可继续使用："+e.Message);}},cancel.Token);}
 internal void Stop(){cancel.Cancel();}
 void Run(){
  string baseDll=Path.Combine(root,"CampusUno","CampusUno.dll"),extraDll=Path.Combine(root,"StudentAgeCampusMinigames","CampusMinigames.UP.dll");if(!File.Exists(baseDll)||!File.Exists(extraDll)||!string.Equals(Path.GetFullPath(typeof(Plugin).Assembly.Location),Path.GetFullPath(baseDll),StringComparison.OrdinalIgnoreCase))return;
  Directory.CreateDirectory(cache);string attempt=Path.Combine(cache,"last-check.txt");DateTime previous;if(File.Exists(attempt)&&DateTime.TryParse(File.ReadAllText(attempt),null,System.Globalization.DateTimeStyles.RoundtripKind,out previous)&&DateTime.UtcNow-previous.ToUniversalTime()<TimeSpan.FromHours(interval))return;
  string feedUrl="https://github.com/"+CampusVersion.Repository+"/releases/latest/download/update.json";byte[] bytes=Download(feedUrl,256*1024);var feed=UpdatePackage.Read<Feed>(bytes);UpdatePackage.ValidateFeed(feed,CampusVersion.Repository);File.WriteAllText(attempt,DateTime.UtcNow.ToString("O"));if(!UpdatePackage.Newer(feed.version,CampusVersion.Value))return;
  string folder=Path.Combine(cache,feed.version);Directory.CreateDirectory(folder);if(File.Exists(Path.Combine(folder,"install.lock"))){try{using(var test=new FileStream(Path.Combine(folder,"install.lock"),FileMode.Open,FileAccess.ReadWrite,FileShare.None)){} }catch(IOException){return;}}
  string zip=Path.Combine(folder,"download.zip"),partial=zip+".part";try{DownloadFile(feed.url,partial,feed.size);if(new FileInfo(partial).Length!=feed.size||UpdatePackage.Hash(partial)!=feed.sha256)throw new InvalidDataException("更新包校验失败");if(File.Exists(zip))File.Delete(zip);File.Move(partial,zip);}finally{if(File.Exists(partial))File.Delete(partial);}
  cancel.Token.ThrowIfCancellationRequested();string verify=Path.Combine(folder,"check-"+Guid.NewGuid().ToString("N"));try{UpdatePackage.Extract(zip,feed.sha256,feed.version,verify);}finally{if(Directory.Exists(verify))Directory.Delete(verify,true);}
  string helper=Path.Combine(folder,"CampusMinigames.Updater.exe");using(var resource=typeof(Plugin).Assembly.GetManifestResourceStream("CampusMinigames.Updater"))using(var output=File.Create(helper)){if(resource==null)throw new InvalidOperationException("Updater helper missing");resource.CopyTo(output);}
  InstallPlan plan;using(var game=Process.GetCurrentProcess())plan=new InstallPlan{pid=game.Id,processStarted=game.StartTime.ToUniversalTime().Ticks,root=root,package=zip,sha256=feed.sha256,version=feed.version,backup=Path.Combine(cache,"backups",DateTime.UtcNow.ToString("yyyyMMdd-HHmmss")+"-"+feed.version)};
  string planPath=Path.Combine(folder,"plan.json");File.WriteAllBytes(planPath,UpdatePackage.Write(plan));cancel.Token.ThrowIfCancellationRequested();var start=new ProcessStartInfo(helper,"\""+planPath+"\""){UseShellExecute=false,CreateNoWindow=true,WindowStyle=ProcessWindowStyle.Hidden,WorkingDirectory=folder};using(var process=Process.Start(start)){if(process==null)throw new IOException("更新助手未启动");}log.LogInfo("小游戏更新已下载，将在游戏退出后安装："+feed.version);
 }
 byte[] Download(string url,long limit){using(var memory=new MemoryStream()){DownloadTo(url,memory,limit);return memory.ToArray();}}
 void DownloadFile(string url,string file,long limit){using(var output=File.Create(file))DownloadTo(url,output,limit);}
 void DownloadTo(string url,Stream output,long limit){cancel.Token.ThrowIfCancellationRequested();ServicePointManager.SecurityProtocol|=SecurityProtocolType.Tls12;var request=(HttpWebRequest)WebRequest.Create(url);request.UserAgent="StudentAge-CampusMinigames/"+CampusVersion.Value;request.Timeout=15000;request.ReadWriteTimeout=15000;
  using(cancel.Token.Register(request.Abort))using(var response=(HttpWebResponse)request.GetResponse()){if(response.ResponseUri.Scheme!="https"||response.ContentLength>limit)throw new InvalidDataException("Invalid update response");using(var input=response.GetResponseStream()){byte[] b=new byte[65536];int n;long total=0;while((n=input.Read(b,0,b.Length))>0){cancel.Token.ThrowIfCancellationRequested();total+=n;if(total>limit)throw new InvalidDataException("Update download too large");output.Write(b,0,n);}}}
 }
}
}
