using System;using System.Runtime.InteropServices;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;
using BepInEx;using Config;using Sdk;using HarmonyLib;using UnityEngine;using UnityEngine.InputSystem;using StudentAge.CampusMinigames;using StudentAge.Sanguosha;
[BepInPlugin("studentage.sanguosha.deckqa","Sanguosha deck QA","1.0.0")][BepInDependency("studio.studentage.nds")]
public sealed class SanguoshaDeckQAPlugin:BaseUnityPlugin {void Awake(){var go=new GameObject("Sanguosha_Drag_QA"){hideFlags=HideFlags.HideAndDontSave};DontDestroyOnLoad(go);go.AddComponent<SanguoshaDeckQA>();}}
public sealed class SanguoshaDeckQA:MonoBehaviour {
 string dir;readonly List<string> checks=new List<string>();bool failed;SanguoshaView table;static Vector2 pointer=new Vector2(1150,300);float start;
 static object Field(object o,string key)=>AccessTools.Field(o.GetType(),key).GetValue(o);
 static void Set(object o,string key,object v)=>AccessTools.Field(o.GetType(),key).SetValue(o,v);
 void Awake(){dir=Path.Combine(Paths.GameRootPath,"SanguoshaDeckQA");Directory.CreateDirectory(dir);PathDefine.SAVE_PATH=Path.Combine(dir,"Saves");PathDefine.TEST_SAVE_PATH=PathDefine.SAVE_PATH;PathDefine.IMG_PATH=Path.Combine(dir,"Images");PathDefine.MUSIC_PATH=Path.Combine(dir,"Music");Application.runInBackground=true;Application.targetFrameRate=60;QualitySettings.vSyncCount=0;InputSystem.settings.backgroundBehavior=InputSettings.BackgroundBehavior.IgnoreFocus;

  Application.logMessageReceived+=(m,s,t)=>{if(t==LogType.Exception){failed=true;File.WriteAllText(Path.Combine(dir,"failed.txt"),m+"\n"+s);}};start=Time.realtimeSinceStartup;
 }
 void Update(){if(failed||Time.realtimeSinceStartup-start>240){if(!failed)File.WriteAllText(Path.Combine(dir,"failed.txt"),"QA timeout");File.WriteAllLines(Path.Combine(dir,"checks.txt"),checks);Application.Quit();}}
 void Check(bool b,string message){if(!b)throw new Exception(message);checks.Add(message);File.WriteAllLines(Path.Combine(dir,"checks.txt"),checks);Debug.Log("DECK QA PASS "+message);}
 IEnumerator Shot(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(dir,name+".png"));yield return null;}
 [StructLayout(LayoutKind.Sequential)]struct POINT{public int x,y;}
 [StructLayout(LayoutKind.Sequential)]struct RECT{public int left,top,right,bottom;}
 delegate bool EnumProc(IntPtr hwnd,IntPtr param);
 [DllImport("user32.dll")]static extern bool EnumWindows(EnumProc callback,IntPtr param);
 [DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr hwnd,out uint pid);
 [DllImport("user32.dll")]static extern bool IsWindowVisible(IntPtr hwnd);
 [DllImport("user32.dll")]static extern bool GetClientRect(IntPtr hwnd,out RECT rect);
 [DllImport("user32.dll")]static extern bool ClientToScreen(IntPtr hwnd,ref POINT point);
 [DllImport("user32.dll")]static extern bool SetForegroundWindow(IntPtr hwnd);
 [DllImport("user32.dll")]static extern bool SetCursorPos(int x,int y);
 [DllImport("user32.dll")]static extern void mouse_event(uint flags,uint dx,uint dy,uint data,UIntPtr extra);
 IntPtr window;
 void Move(Vector2 p){if(window==IntPtr.Zero){uint id=(uint)System.Diagnostics.Process.GetCurrentProcess().Id;EnumWindows((h,t)=>{uint pid;GetWindowThreadProcessId(h,out pid);if(pid==id&&IsWindowVisible(h)){window=h;return false;}return true;},IntPtr.Zero);}Check(window!=IntPtr.Zero,"QA process has its own window");RECT r;GetClientRect(window,out r);float scale=Mathf.Min(Screen.width/1600f,Screen.height/900f);var pt=new POINT{x=Mathf.RoundToInt(((Screen.width-1600*scale)/2+p.x*scale)*(r.right-r.left)/Screen.width),y=Mathf.RoundToInt(((Screen.height-900*scale)/2+p.y*scale)*(r.bottom-r.top)/Screen.height)};ClientToScreen(window,ref pt);SetForegroundWindow(window);SetCursorPos(pt.x,pt.y);}
 IEnumerator Input(EventType type,Vector2 p,int button=0){pointer=p;Move(p);yield return new WaitForSecondsRealtime(.08f);if(type==EventType.MouseDown)mouse_event(button==0?2u:8u,0,0,0,UIntPtr.Zero);if(type==EventType.MouseUp)mouse_event(button==0?4u:16u,0,0,0,UIntPtr.Zero);yield return new WaitForSecondsRealtime(.07f);}
 IEnumerator Click(Vector2 p){yield return Input(EventType.MouseDown,p);yield return Input(EventType.MouseUp,p);}
 Vector2 Hand(int id)=>(Vector2)((IDictionary)Field(table,"handPositions"))[id];
 IEnumerator Drag(int id,Vector2 target,bool screenshot=false){var from=Hand(id);pointer=from;Move(from);yield return new WaitForSecondsRealtime(.25f);from=Hand(id);yield return Input(EventType.MouseDown,from);Check(table.DragActive,"long press begins on actual hand card");yield return new WaitForSecondsRealtime(.24f);yield return Input(EventType.MouseDrag,target);if(screenshot)yield return Shot("target-arrow");yield return Input(EventType.MouseUp,target);Check(!table.DragActive,"release clears pointer capture");}
 Match Blank(){var m=new Match("zhangfei","liubei",false,18);m.DrawPile.Clear();m.Discard.Clear();foreach(var s in m.Seats){s.Hand.Clear();s.Judgments.Clear();Array.Clear(s.Equipment,0,4);}return m;}
 Card Card(string kind,int ordinal=0)=>Deck.Create().Where(c=>c.Kind==kind).Skip(ordinal).First();
 void RunRule(Match m,string method,params object[] args){var stack=(Stack<IEnumerator>)Field(m,"stack");stack.Clear();AccessTools.Property(typeof(Match),"Pending").SetValue(m,null,null);stack.Push((IEnumerator)AccessTools.Method(typeof(Match),method).Invoke(m,args));AccessTools.Method(typeof(Match),"Pump").Invoke(m,null);}
 IEnumerator Fixture(Match m){AccessTools.Property(typeof(SanguoshaView),"Engine").SetValue(table,m,null);((IList)Field(table,"visualHand")).Clear();((IDictionary)Field(table,"handPoses")).Clear();((IList)Field(table,"tableCards")).Clear();((Queue<MatchEvent>)Field(table,"events")).Clear();Set(table,"eventSeq",0);Set(table,"presentedEventSeq",0);Set(table,"aiAt",Time.unscaledTime+999);table.ResetTableSelection();pointer=new Vector2(1150,300);yield return new WaitForSecondsRealtime(2.5f);}
 IEnumerator Ready(){float end=Time.realtimeSinceStartup+20;while(!(bool)AccessTools.Property(typeof(SanguoshaView),"DecisionReady").GetValue(table,null)&&Time.realtimeSinceStartup<end)yield return null;Check((bool)AccessTools.Property(typeof(SanguoshaView),"DecisionReady").GetValue(table,null),"decision waits for public card presentation");}
 IEnumerator Start(){
  float end=Time.realtimeSinceStartup+120;while(Time.realtimeSinceStartup<end){bool ready=false;try{ready=NdsIntegration.IsTitleScreen;}catch{}if(ready)break;yield return null;}yield return new WaitForSecondsRealtime(3);Check(NdsIntegration.IsTitleScreen,"official 1.94 title ready");SanguoshaView.OpenTestDirectory();table=SanguoshaView.Current;Check(table!=null,"title test table opens");end=Time.realtimeSinceStartup+45;while(!table.AudioReady&&Time.realtimeSinceStartup<end)yield return null;Check(table.AudioReady,"all art and audio preloaded");Set(table,"testDirectory",false);AccessTools.Property(typeof(SanguoshaView),"Session").SetValue(table,new SanguoshaSession(101,0,"拖动检查"),null);Check(table.StartBattle("zhangfei",false),"test session starts without a save");
  Check(Deck.CreateDuel().Count==52&&!Deck.CreateDuel().Any(c=>c.Kind=="wine"),"loaded runtime uses strict 52-card duel deck");Check(table.Engine.DrawPile.Count+table.Engine.Seats.Sum(s=>s.Hand.Count)==52,"fresh game conserves all 52 cards");
  var m=Blank();StudentAge.Sanguosha.Card slash=Card("slash"),peach=Card("peach"),weapon=Card("crossbow"),aoe=Card("savage_assault"),wine=Card("ex_nihilo");m.Seats[0].Hp=3;m.Seats[0].Hand.AddRange(new[]{slash,peach,weapon,aoe,wine,Card("jink"),Card("nullification")});RunRule(m,"Round",0);yield return Fixture(m);yield return Ready();yield return Shot("hand-hd");
  var texture=SanguoshaAssets.Image("hd/faces/slash-spade-7.png");Check(texture!=null&&texture.width>=400&&texture.height>=555,"chosen caise card uses native 400x555 art");
  var before=m.Pending;yield return Click(Hand(slash.Id));Check(ReferenceEquals(m.Pending,before)&&m.Seats[0].Hand.Contains(slash),"quick tap never selects or plays card");
  yield return Drag(slash.Id,new Vector2(1120,230));Check(m.Seats[0].Hand.Contains(slash),"blank-space drop cancels");yield return Drag(slash.Id,new Vector2(800,817));Check(m.Seats[0].Hand.Contains(slash),"drag back to hand cancels");
  yield return Drag(slash.Id,new Vector2(1470,710));Check(m.Seats[0].Hand.Contains(slash),"attack cannot target self");
  yield return Drag(slash.Id,new Vector2(795,170),true);Check(m.Seats[1].Hp==3&&!m.Seats[0].Hand.Contains(slash),"attack drag damages enemy without extra confirm");yield return Ready();
  yield return Drag(peach.Id,new Vector2(1470,710));Check(m.Seats[0].Hp==4,"peach drag heals self");yield return Ready();yield return Drag(weapon.Id,new Vector2(1470,710));Check(m.Seats[0].Equipment[0]?.Id==weapon.Id,"equipment drag equips self");yield return Ready();
  yield return Drag(aoe.Id,new Vector2(920,460));Check(m.Seats[1].Hp==2,"global trick drag resolves in table center");yield return Ready();yield return Drag(wine.Id,new Vector2(1470,710));Check(!m.Seats[0].Hand.Contains(wine)&&m.Seats[0].Hand.Count==4,"ex nihilo drag draws two existing cards");yield return Ready();yield return Shot("equipped-and-draw");
  m=Blank();slash=Card("slash");var jink=Card("jink");m.Seats[1].Hand.Add(slash);m.Seats[0].Hand.Add(jink);RunRule(m,"Use",1,slash,"slash",false);yield return Fixture(m);yield return Ready();Check(m.Pending.Kind==DecisionKind.Response,"incoming slash opens real response");yield return Drag(jink.Id,new Vector2(795,170));Check(m.Seats[0].Hand.Contains(jink),"jink cannot be dropped on attacker portrait");yield return Drag(jink.Id,new Vector2(800,455));Check(m.Seats[0].Hp==4&&!m.Seats[0].Hand.Contains(jink),"jink dragged onto slash prevents damage");yield return Shot("jink-response");
  m=Blank();StudentAge.Sanguosha.Card trick=Card("duel"),n1=Card("nullification"),n2=Card("nullification",1),n3=Card("nullification",2);m.Seats[1].Hand.AddRange(new[]{trick,n2});m.Seats[0].Hand.AddRange(new[]{n1,n3});RunRule(m,"Use",1,trick,"duel",false);yield return Fixture(m);yield return Ready();yield return Drag(n1.Id,new Vector2(800,455));Check(m.Pending.Actor==1&&m.Pending.Subject.Id==n1.Id,"first nullification points to response card");m.Choose(m.Pending.Options.FindIndex(o=>o.CardId==n2.Id));Set(table,"aiAt",Time.unscaledTime+999);yield return Ready();yield return new WaitForSecondsRealtime(.6f);var rr=(Rect)AccessTools.Method(typeof(SanguoshaView),"ResponseRect").Invoke(table,null);yield return Drag(n3.Id,rr.center);Check(m.Pending==null&&m.Seats[0].Hp==4,"dragging counter-nullification onto latest counter cancels duel");
  m=Blank();m.Seats[0].Hp=0;wine=Card("peach");m.Seats[0].Hand.Add(wine);RunRule(m,"Dying",0,1);yield return Fixture(m);yield return Ready();yield return Shot("peach-rescue");yield return Drag(wine.Id,new Vector2(1470,710));Check(m.Winner==-2&&m.Seats[0].Hp==1,"dying self peach drag rescues before defeat");
  m=Blank();trick=Card("indulgence");m.Seats[0].Hand.Add(trick);RunRule(m,"Round",0);yield return Fixture(m);yield return Ready();yield return Drag(trick.Id,new Vector2(795,170));yield return Ready();yield return Shot("indulgence-mark");Check(m.Seats[1].Judgments.Any(c=>c.Id==trick.Id),"indulgence remains on enemy portrait");
  m=Blank();m.Seats[0].Hand.AddRange(new[]{Card("slash"),Card("peach")});RunRule(m,"Pick",0,"选择一张手牌",m.Seats[0].Hand,false,true,false);yield return Fixture(m);yield return Ready();int selectedId=m.Seats[0].Hand[0].Id;yield return Click(Hand(selectedId));Check(m.Pending==null&&((StudentAge.Sanguosha.Card)Field(m,"selected")).Id==selectedId,"actual hand selection commits with one click, no confirm bar");
  m=Blank();var offered=new[]{Card("slash"),Card("peach")};RunRule(m,"Pick",0,"选择一张明置牌",offered,false,true,false);yield return Fixture(m);yield return Ready();yield return Shot("public-choice");yield return Click(new Vector2(665,415));Check(m.Pending==null&&((StudentAge.Sanguosha.Card)Field(m,"selected")).Id==offered[0].Id,"public-card choice remains clickable over board");
  m=Blank();slash=Card("slash");m.Seats[1].Hp=1;m.Seats[0].Hand.AddRange(new[]{slash,Card("ex_nihilo"),Card("peach"),Card("jink"),Card("nullification")});RunRule(m,"Round",0);yield return Fixture(m);yield return Ready();yield return Drag(slash.Id,new Vector2(795,170));Check(m.Winner==0&&m.Pending==null,"lethal drag ends game before end-turn click");end=Time.realtimeSinceStartup+40;bool firstShot=false,victoryShot=false;while(table.OutcomeStage!="Ready"&&Time.realtimeSinceStartup<end){if(table.OutcomeStage=="FirstBlood"&&!firstShot){yield return new WaitForSecondsRealtime(1.7f);yield return Shot("first-blood-clean");firstShot=true;}if(table.OutcomeStage=="Victory"&&!victoryShot){yield return new WaitForSecondsRealtime(.7f);yield return Shot("victory-layer");victoryShot=true;}yield return null;}Check(table.OutcomeStage=="Ready"&&table.Session.NewReward,"general unlock waits for first blood and victory");yield return Shot("reward-layer");
  Check(!(bool)AccessTools.Property(typeof(SanguoshaView),"BoardInputAllowed").GetValue(table,null),"outcome blocks every underlying board interaction");int remain=m.Seats[0].Hand.Count;yield return Click(new Vector2(800,770));Check(table.Closed&&m.Seats[0].Hand.Count==remain,"unlock confirm closes without clicking cards beneath");
  Check(!table.MissingAudio.Any(),"no missing audio in exercised flows");Check(!failed,"no Unity exceptions");File.WriteAllText(Path.Combine(dir,"success.txt"),"SANGUOSHA_DRAG_RUNTIME_OK");yield return new WaitForSecondsRealtime(.3f);Application.Quit();
 }
}
