using System;using System.Runtime.InteropServices;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;
using BepInEx;using Config;using Sdk;using HarmonyLib;using UnityEngine;using UnityEngine.InputSystem;using StudentAge.CampusMinigames;using StudentAge.Sanguosha;
[BepInPlugin("studentage.sanguosha.storyqa","Sanguosha story QA","1.0.0")][BepInDependency("studio.studentage.nds")]
public sealed class SanguoshaStoryQAPlugin:BaseUnityPlugin {void Awake(){var go=new GameObject("Sanguosha_Drag_QA"){hideFlags=HideFlags.HideAndDontSave};DontDestroyOnLoad(go);go.AddComponent<SanguoshaStoryQA>();}}
public sealed class SanguoshaStoryQA:MonoBehaviour {
 string dir;readonly List<string> checks=new List<string>();bool failed;SanguoshaView table;static Vector2 pointer=new Vector2(1150,300);float start;
 static object Field(object o,string key)=>AccessTools.Field(o.GetType(),key).GetValue(o);
 static void Set(object o,string key,object v)=>AccessTools.Field(o.GetType(),key).SetValue(o,v);
 void Awake(){dir=Path.Combine(Paths.GameRootPath,"SanguoshaStoryQA");Directory.CreateDirectory(dir);PathDefine.SAVE_PATH=Path.Combine(dir,"Saves");PathDefine.TEST_SAVE_PATH=PathDefine.SAVE_PATH;PathDefine.IMG_PATH=Path.Combine(dir,"Images");PathDefine.MUSIC_PATH=Path.Combine(dir,"Music");Application.runInBackground=true;Application.targetFrameRate=60;QualitySettings.vSyncCount=0;InputSystem.settings.backgroundBehavior=InputSettings.BackgroundBehavior.IgnoreFocus;

  Application.logMessageReceived+=(m,s,t)=>{if(t==LogType.Exception){failed=true;File.WriteAllText(Path.Combine(dir,"failed.txt"),m+"\n"+s);}};start=Time.realtimeSinceStartup;
 }
 void Update(){if(failed||Time.realtimeSinceStartup-start>600){if(!failed)File.WriteAllText(Path.Combine(dir,"failed.txt"),"QA timeout");File.WriteAllLines(Path.Combine(dir,"checks.txt"),checks);Application.Quit();}}
 void Check(bool b,string message){if(!b)throw new Exception(message);checks.Add(message);File.WriteAllLines(Path.Combine(dir,"checks.txt"),checks);Debug.Log("JUDGMENT QA PASS "+message);}
 IEnumerator Shot(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(dir,name+".png"));yield return null;}
 [StructLayout(LayoutKind.Sequential)]struct POINT{public int x,y;}
 [StructLayout(LayoutKind.Sequential)]struct RECT{public int left,top,right,bottom;}
 delegate bool EnumProc(IntPtr hwnd,IntPtr param);
 [DllImport("user32.dll")]static extern bool EnumWindows(EnumProc callback,IntPtr param);
 [DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr hwnd,out uint pid);
 [DllImport("user32.dll")]static extern bool IsWindowVisible(IntPtr hwnd);
 [DllImport("user32.dll")]static extern bool GetClientRect(IntPtr hwnd,out RECT rect);
 [DllImport("user32.dll")]static extern bool ClientToScreen(IntPtr hwnd,ref POINT point);
 [DllImport("user32.dll")]static extern bool SetForegroundWindow(IntPtr hwnd);
 [DllImport("user32.dll")]static extern bool SetCursorPos(int x,int y);
 [DllImport("user32.dll")]static extern void mouse_event(uint flags,uint dx,uint dy,uint data,UIntPtr extra);
 IntPtr window;
 void Move(Vector2 p){if(window==IntPtr.Zero){uint id=(uint)System.Diagnostics.Process.GetCurrentProcess().Id;EnumWindows((h,t)=>{uint pid;GetWindowThreadProcessId(h,out pid);if(pid==id&&IsWindowVisible(h)){window=h;return false;}return true;},IntPtr.Zero);}Check(window!=IntPtr.Zero,"QA process has its own window");RECT r;GetClientRect(window,out r);float scale=Mathf.Min(Screen.width/1600f,Screen.height/900f);var pt=new POINT{x=Mathf.RoundToInt(((Screen.width-1600*scale)/2+p.x*scale)*(r.right-r.left)/Screen.width),y=Mathf.RoundToInt(((Screen.height-900*scale)/2+p.y*scale)*(r.bottom-r.top)/Screen.height)};ClientToScreen(window,ref pt);SetForegroundWindow(window);SetCursorPos(pt.x,pt.y);}
 IEnumerator Input(EventType type,Vector2 p,int button=0){pointer=p;Move(p);yield return new WaitForSecondsRealtime(.08f);if(type==EventType.MouseDown)mouse_event(button==0?2u:8u,0,0,0,UIntPtr.Zero);if(type==EventType.MouseUp)mouse_event(button==0?4u:16u,0,0,0,UIntPtr.Zero);yield return new WaitForSecondsRealtime(.07f);}
 IEnumerator Click(Vector2 p){yield return Input(EventType.MouseDown,p);yield return Input(EventType.MouseUp,p);}
 Vector2 Hand(int id)=>(Vector2)((IDictionary)Field(table,"handPositions"))[id];
 IEnumerator Drag(int id,Vector2 target,bool screenshot=false){var from=Hand(id);pointer=from;Move(from);yield return new WaitForSecondsRealtime(.25f);from=Hand(id);yield return Input(EventType.MouseDown,from);Check(table.DragActive,"long press begins on actual hand card");yield return new WaitForSecondsRealtime(.24f);yield return Input(EventType.MouseDrag,target);if(screenshot)yield return Shot("target-arrow");yield return Input(EventType.MouseUp,target);Check(!table.DragActive,"release clears pointer capture");}

 static bool Same(Newtonsoft.Json.Linq.JToken a,Newtonsoft.Json.Linq.JToken b){if(a==null||b==null)return a==b;var numeric=new[]{Newtonsoft.Json.Linq.JTokenType.Integer,Newtonsoft.Json.Linq.JTokenType.Float};if(numeric.Contains(a.Type)&&numeric.Contains(b.Type))return (double)a==(double)b;if(a is Newtonsoft.Json.Linq.JArray aa&&b is Newtonsoft.Json.Linq.JArray bb)return aa.Count==bb.Count&&aa.Zip(bb,(x,y)=>Same(x,y)).All(v=>v);return Newtonsoft.Json.Linq.JToken.DeepEquals(a,b);}
 IEnumerator ReadStory(int npc,bool alreadyOpen=false,bool won=true){
  if(!alreadyOpen)Check(SanguoshaVictoryStory.Play(npc,won),"native "+(won?"victory":"defeat")+" story opens for NPC "+npc);
  float end=Time.realtimeSinceStartup+20;while(UIMgr.GetOpeningView<View.Evt.NewTalkView>()==null&&Time.realtimeSinceStartup<end)yield return null;var view=UIMgr.GetOpeningView<View.Evt.NewTalkView>();Check(view!=null,"native NewTalkView is visible");yield return new WaitForSecondsRealtime(2.5f);yield return Shot("story-"+npc+(won?"-win":"-loss")+"-entry");int lines=0;
  while((view=UIMgr.GetOpeningView<View.Evt.NewTalkView>())!=null&&lines++<20){var cfg=(TalkCfg)Field(view,"cfg");Check(cfg.id>=1922100001&&cfg.id<=1922119999,"story uses private runtime IDs");
   float readyBy=Time.realtimeSinceStartup+8;string expectedText=RecordMgr.Replace(cfg.content);while(Time.realtimeSinceStartup<readyBy){var text=(TMPro.TextMeshProUGUI)AccessTools.Method(typeof(View.Evt.NewTalkView),"GetTalkTxt").Invoke(view,null);if(text.text==expectedText)break;if((string)Field(view,"talk")==expectedText&&Field(view,"talkState").ToString()=="Anim")view.OnClickNext();yield return new WaitForSecondsRealtime(.1f);}Check(((TMPro.TextMeshProUGUI)AccessTools.Method(typeof(View.Evt.NewTalkView),"GetTalkTxt").Invoke(view,null)).text==expectedText,"visible dialogue matches authored line "+cfg.id);yield return new WaitForSecondsRealtime(.2f);var roles=(IDictionary)Field(view,"roles");foreach(var command in cfg.roles.Where(r=>r.Count>=3&&r[1]==3000)){Check(roles.Contains((int)command[0]),"expression target exists");Check((int)Field(roles[(int)command[0]],"targetPose")== (int)command[2],"authored expression applied at "+cfg.id);}
   if(cfg.roles.Any(r=>r.Count>=3&&r[1]==3000))yield return Shot("pose-"+cfg.id);
   if(cfg.option.Count>0){var opts=Singleton<CommonEvtMgr>.Ins.GetTalkOptions(cfg.id,1,null,true);Check(opts.Count>0,"native confirmation option resolves");Singleton<CommonEvtMgr>.Ins.SelectOption(opts[0]);}else view.OnClickNext();yield return new WaitForSecondsRealtime(.4f);
  }
  Check(lines<20&&!UIMgr.IsViewOpened<View.Evt.NewTalkView>(),"story terminates normally "+npc);Check(!SanguoshaVictoryStory.Active,"completion releases story guard");
 }
 IEnumerator Start(){float end=Time.realtimeSinceStartup+120;while(Time.realtimeSinceStartup<end){bool ready=false;try{ready=NdsIntegration.IsTitleScreen;}catch{}if(ready)break;yield return null;}Check(NdsIntegration.IsTitleScreen,"official title ready");
  bool done=false,loaded=false;SaveMgrEx.LoadAynsc(PathDefine.SAVE_PATH,"fixture.save",16,ok=>{loaded=ok;done=true;});end=Time.realtimeSinceStartup+40;while(!done&&Time.realtimeSinceStartup<end)yield return null;Check(loaded,"isolated fixture loaded");yield return new WaitForSecondsRealtime(3);
  for(int n=0;n<3;n++){var warning=Resources.FindObjectsOfTypeAll<UnityEngine.UI.Button>().FirstOrDefault(b=>b.gameObject.activeInHierarchy&&b.GetComponentsInChildren<UnityEngine.UI.Text>().Any(t=>t.text=="好的"));if(warning==null)break;warning.onClick.Invoke();yield return new WaitForSecondsRealtime(1);}
  var mgr=Singleton<CommonEvtMgr>.Ins;SanguoshaVictoryStory.Register();Check(Encounters.Npcs.Count(n=>SanguoshaVictoryStory.EventFor(n,true)>0)==10,"ten first-stage victory stories registered");Check(Encounters.Npcs.Count(n=>SanguoshaVictoryStory.EventFor(n,false)>0)==10,"ten first-stage defeat stories registered");Check(SanguoshaVictoryStory.EventFor(202,true)==1922107&&SanguoshaVictoryStory.EventFor(202,false)==1922117,"Lin Jiayu stories now registered");
  foreach(var path in new[]{"Talk","Option","Evt"}){var source=Newtonsoft.Json.Linq.JObject.Parse(File.ReadAllText(Path.Combine(SanguoshaAssets.Root,"Stories/FirstWin/"+path+"Cfg.json")));foreach(var pair in source){int old=int.Parse(pair.Key),id=old+(path=="Talk"?700000000:path=="Option"?70000000:700000);var expected=(Newtonsoft.Json.Linq.JObject)pair.Value;var actual=Newtonsoft.Json.Linq.JObject.FromObject(path=="Talk"?(object)Cfg.TalkCfgMap[id]:path=="Option"?(object)Cfg.OptionCfgMap[id]:Cfg.EvtCfgMap[id]);
    foreach(string key in new[]{"content","roles","roleIds","effect","effect2","screenEffect","audio","vocals","bg"})if(expected[key]!=null)Check(Same(expected[key],actual[key]),"source field preserved "+path+" "+old+" "+key);
   }}
  var evtIndex=(IDictionary)Field(mgr,"evtDict");AccessTools.Method(typeof(CommonEvtMgr),"InitEvtCfg").Invoke(mgr,null);foreach(int npc in Encounters.Npcs)foreach(bool won in new[]{true,false}){int id=SanguoshaVictoryStory.EventFor(npc,won);if(id==0)continue;Check(Cfg.EvtCfgMap[id].type==SanguoshaVictoryStory.StoryEventType,"story not registered as random/social event");}
  Check(Cfg.TalkCfgMap[1922115006].check.Count==0&&Cfg.TalkCfgMap[1922115006].nextTalk.SequenceEqual(new[]{1922115008})&&!Cfg.TalkCfgMap.ContainsKey(1922115007),"Meng defeat keeps only the never-won branch");Check(Cfg.TalkCfgMap[1922101003].check.Any(c=>c.Count>=3&&(int)c[2]==320907),"native event condition keeps its value");Check(Cfg.TalkCfgMap[1922117003].effect.Any(e=>e.Count>=3&&(int)e[0]==60&&(int)e[1]==1&&(int)e[2]==SanguoshaIntegration.CardId("guojia")),"Lin Jiayu defeat line grants the Guo Jia card item");
  Singleton<RoundMgr>.Ins.SetTime(2006,1);SanguoshaIntegration.Register();Singleton<BagMgr>.Ins.AddItem(SanguoshaIntegration.BoxId,1);SanguoshaIntegration.Write(new Progress());Singleton<RoleMgr>.Ins.GetRelationData().ChangeRelation(101,1);
  Check(SanguoshaView.Open(101),"real NPC duel opens");table=SanguoshaView.Current;end=Time.realtimeSinceStartup+45;while(!table.AudioReady&&Time.realtimeSinceStartup<end)yield return null;Check(table.StartBattle("zhaoyun",false),"first stage starts");var session=table.Session;table.Engine.Surrender(1);end=Time.realtimeSinceStartup+40;while(table.OutcomeStage!="Ready"&&Time.realtimeSinceStartup<end)yield return null;Check(table.OutcomeStage=="Ready"&&!SanguoshaVictoryStory.Active,"victory and reward finish before story");float favor=Singleton<RoleMgr>.Ins.GetRole(101).Favor;Check(SanguoshaIntegration.Read().Stage(101)==1,"win advances exactly one stage");yield return Click(new Vector2(800,775));Check(table.Closed,"reward confirm releases minigame overlay");yield return ReadStory(101,true);Check(!session.PlayStory(),"same victory cannot start story twice");Check(Singleton<RoleMgr>.Ins.GetRole(101).Favor==favor&&SanguoshaIntegration.Read().Stage(101)==1,"story does not duplicate favor or stage rewards");
  foreach(int npc in new[]{3,102,103,104,105,201,202,203,204})yield return ReadStory(npc);
  foreach(int npc in new[]{3,101,102,103,104,105,201,203,204})yield return ReadStory(npc,false,false);
  Check(!SanguoshaIntegration.Has("guojia"),"Guo Jia not owned before Lin Jiayu defeat story");yield return ReadStory(202,false,false);Check(SanguoshaIntegration.Has("guojia"),"Lin Jiayu defeat story hands over the Guo Jia card");
  mgr.AddEvtToHistory(320907);Check(CommonEvtMgr.IsMatchCondition(Cfg.TalkCfgMap[1922101003].check,true),"Chen Xinci branch uses original event-history condition");yield return ReadStory(103);
  var round=Singleton<RoundMgr>.Ins;round.SetRound(round.GetRound()+1);var second=new SanguoshaSession(101);Check(second.Stage==1&&second.Begin()&&second.Finish(true),"second stage completes");Check(!second.PlayStory(),"second-stage victory has no first-stage story");round.SetRound(round.GetRound()+1);var loss=new SanguoshaSession(101);Check(loss.Begin()&&loss.Finish(false,true)&&!loss.PlayStory(),"second-stage defeat has no first-stage story");
  SanguoshaIntegration.Write(new Progress());round.SetRound(round.GetRound()+1);var surrender=new SanguoshaSession(101);Check(surrender.Begin()&&surrender.Finish(false,false)&&!surrender.PlayStory(),"standoff at first stage has no defeat story");round.SetRound(round.GetRound()+1);var defeat=new SanguoshaSession(101);Check(defeat.Begin()&&defeat.Finish(false,true),"first-stage defeat settles");Check(defeat.PlayStory(),"first-stage defeat starts the defeat story");yield return ReadStory(101,true,false);Check(SanguoshaIntegration.Read().StoryTold(1222114),"defeat story recorded once");round.SetRound(round.GetRound()+1);var again=new SanguoshaSession(101);Check(again.Begin()&&again.Finish(false,true)&&!again.PlayStory(),"repeated first-stage defeat does not replay the story");
  var test=new SanguoshaSession(101,0,"test");Check(!test.PlayStory(),"title debug does not touch native story state");Check(!failed,"no Unity exceptions");File.WriteAllText(Path.Combine(dir,"success.txt"),"SANGUOSHA_STORY_RUNTIME_OK");yield return new WaitForSecondsRealtime(.3f);Application.Quit();
 }
}
