using System;using System.Runtime.InteropServices;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;
using BepInEx;using Config;using Sdk;using HarmonyLib;using UnityEngine;using UnityEngine.InputSystem;using StudentAge.CampusMinigames;using StudentAge.Sanguosha;
[BepInPlugin("studentage.sanguosha.participantsqa","Sanguosha participants QA","1.0.0")][BepInDependency("studio.studentage.nds")]
public sealed class SanguoshaParticipantsQAPlugin:BaseUnityPlugin {void Awake(){var go=new GameObject("Sanguosha_Drag_QA"){hideFlags=HideFlags.HideAndDontSave};DontDestroyOnLoad(go);go.AddComponent<SanguoshaParticipantsQA>();}}
public sealed class SanguoshaParticipantsQA:MonoBehaviour {
 string dir;readonly List<string> checks=new List<string>();bool failed;SanguoshaView table;static Vector2 pointer=new Vector2(1150,300);float start;
 static object Field(object o,string key)=>AccessTools.Field(o.GetType(),key).GetValue(o);
 static void Set(object o,string key,object v)=>AccessTools.Field(o.GetType(),key).SetValue(o,v);
 void Awake(){dir=Path.Combine(Paths.GameRootPath,"SanguoshaParticipantsQA");Directory.CreateDirectory(dir);PathDefine.SAVE_PATH=Path.Combine(dir,"Saves");PathDefine.TEST_SAVE_PATH=PathDefine.SAVE_PATH;PathDefine.IMG_PATH=Path.Combine(dir,"Images");PathDefine.MUSIC_PATH=Path.Combine(dir,"Music");Application.runInBackground=true;Application.targetFrameRate=60;QualitySettings.vSyncCount=0;InputSystem.settings.backgroundBehavior=InputSettings.BackgroundBehavior.IgnoreFocus;

  Application.logMessageReceived+=(m,s,t)=>{if(t==LogType.Exception){failed=true;File.WriteAllText(Path.Combine(dir,"failed.txt"),m+"\n"+s);}};start=Time.realtimeSinceStartup;
 }
 void Update(){if(failed||Time.realtimeSinceStartup-start>360){if(!failed)File.WriteAllText(Path.Combine(dir,"failed.txt"),"QA timeout");File.WriteAllLines(Path.Combine(dir,"checks.txt"),checks);Application.Quit();}}
 void Check(bool b,string message){if(!b)throw new Exception(message);checks.Add(message);File.WriteAllLines(Path.Combine(dir,"checks.txt"),checks);Debug.Log("JUDGMENT QA PASS "+message);}
 IEnumerator Shot(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(dir,name+".png"));yield return null;}
 [StructLayout(LayoutKind.Sequential)]struct POINT{public int x,y;}
 [StructLayout(LayoutKind.Sequential)]struct RECT{public int left,top,right,bottom;}
 delegate bool EnumProc(IntPtr hwnd,IntPtr param);
 [DllImport("user32.dll")]static extern bool EnumWindows(EnumProc callback,IntPtr param);
 [DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr hwnd,out uint pid);
 [DllImport("user32.dll")]static extern bool IsWindowVisible(IntPtr hwnd);
 [DllImport("user32.dll")]static extern bool GetClientRect(IntPtr hwnd,out RECT rect);
 [DllImport("user32.dll")]static extern bool ClientToScreen(IntPtr hwnd,ref POINT point);
 [DllImport("user32.dll")]static extern bool SetForegroundWindow(IntPtr hwnd);
 [DllImport("user32.dll")]static extern bool SetCursorPos(int x,int y);
 [DllImport("user32.dll")]static extern void mouse_event(uint flags,uint dx,uint dy,uint data,UIntPtr extra);
 IntPtr window;
 void Move(Vector2 p){if(window==IntPtr.Zero){uint id=(uint)System.Diagnostics.Process.GetCurrentProcess().Id;EnumWindows((h,t)=>{uint pid;GetWindowThreadProcessId(h,out pid);if(pid==id&&IsWindowVisible(h)){window=h;return false;}return true;},IntPtr.Zero);}Check(window!=IntPtr.Zero,"QA process has its own window");RECT r;GetClientRect(window,out r);float scale=Mathf.Min(Screen.width/1600f,Screen.height/900f);var pt=new POINT{x=Mathf.RoundToInt(((Screen.width-1600*scale)/2+p.x*scale)*(r.right-r.left)/Screen.width),y=Mathf.RoundToInt(((Screen.height-900*scale)/2+p.y*scale)*(r.bottom-r.top)/Screen.height)};ClientToScreen(window,ref pt);SetForegroundWindow(window);SetCursorPos(pt.x,pt.y);}
 IEnumerator Input(EventType type,Vector2 p,int button=0){pointer=p;Move(p);yield return new WaitForSecondsRealtime(.08f);if(type==EventType.MouseDown)mouse_event(button==0?2u:8u,0,0,0,UIntPtr.Zero);if(type==EventType.MouseUp)mouse_event(button==0?4u:16u,0,0,0,UIntPtr.Zero);yield return new WaitForSecondsRealtime(.07f);}
 IEnumerator Click(Vector2 p){yield return Input(EventType.MouseDown,p);yield return Input(EventType.MouseUp,p);}
 Vector2 Hand(int id)=>(Vector2)((IDictionary)Field(table,"handPositions"))[id];
 IEnumerator Drag(int id,Vector2 target,bool screenshot=false){var from=Hand(id);pointer=from;Move(from);yield return new WaitForSecondsRealtime(.25f);from=Hand(id);yield return Input(EventType.MouseDown,from);Check(table.DragActive,"long press begins on actual hand card");yield return new WaitForSecondsRealtime(.24f);yield return Input(EventType.MouseDrag,target);if(screenshot)yield return Shot("target-arrow");yield return Input(EventType.MouseUp,target);Check(!table.DragActive,"release clears pointer capture");}
 Match Blank(string general="zhangfei"){var m=new Match(general,table.Session.Opponent,false,18);m.DrawPile.Clear();m.Discard.Clear();m.Events.Clear();foreach(var s in m.Seats){s.Hand.Clear();s.Judgments.Clear();Array.Clear(s.Equipment,0,4);}return m;}
 Card Card(string kind,int ordinal=0)=>Deck.Create().Where(c=>c.Kind==kind).Skip(ordinal).First();
 void RunRule(Match m,string method,params object[] args){var stack=(Stack<IEnumerator>)Field(m,"stack");stack.Clear();AccessTools.Property(typeof(Match),"Pending").SetValue(m,null,null);stack.Push((IEnumerator)AccessTools.Method(typeof(Match),method).Invoke(m,args));AccessTools.Method(typeof(Match),"Pump").Invoke(m,null);}
 IEnumerator Fixture(Match m){Set(table,"judgmentVisual",null);Set(table,"judgmentHoldUntil",0f);AccessTools.Property(typeof(SanguoshaView),"Engine").SetValue(table,m,null);((IList)Field(table,"visualHand")).Clear();((IDictionary)Field(table,"handPoses")).Clear();((IList)Field(table,"tableCards")).Clear();((Queue<MatchEvent>)Field(table,"events")).Clear();Set(table,"eventSeq",0);Set(table,"presentedEventSeq",0);Set(table,"aiAt",Time.unscaledTime+999);table.ResetTableSelection();pointer=new Vector2(1150,300);yield return new WaitForSecondsRealtime(2.5f);}
 IEnumerator Ready(){float end=Time.realtimeSinceStartup+20;while(!(bool)AccessTools.Property(typeof(SanguoshaView),"DecisionReady").GetValue(table,null)&&Time.realtimeSinceStartup<end)yield return null;Check((bool)AccessTools.Property(typeof(SanguoshaView),"DecisionReady").GetValue(table,null),"decision waits for public card presentation");}
 IEnumerator JudgmentResult(string shot){float end=Time.realtimeSinceStartup+12;while(table.JudgmentStage!="result"&&Time.realtimeSinceStartup<end)yield return null;Check(table.JudgmentStage=="result","final judgment result is presented");yield return new WaitForSecondsRealtime(.5f);yield return Shot(shot);}
 IEnumerator Start(){
  float end=Time.realtimeSinceStartup+120;while(Time.realtimeSinceStartup<end){bool ready=false;try{ready=NdsIntegration.IsTitleScreen;}catch{}if(ready)break;yield return null;}yield return new WaitForSecondsRealtime(3);Check(NdsIntegration.IsTitleScreen,"official 1.94 title ready");
  Check(!SanguoshaIntegration.IsSaleYear(2005)&&SanguoshaIntegration.IsSaleYear(2006)&&SanguoshaIntegration.IsSaleYear(2007),"sale starts at the beginning of 2006");Check(SanguoshaIntegration.Register()&&Enumerable.Range(SanguoshaIntegration.BoxId,36).All(id=>Cfg.ShopCfgMap[id].time==2006),"native shop metadata agrees with 2006 release gate");
  // Authoritative shipped NPC routes, not a hand-maintained gender list.
  foreach(bool male in new[]{true,false})foreach(bool dlc in new[]{true,false}){
   var available=Cfg.PersonCfgMap.Values.Where(p=>p.init!=null&&p.init.Count>0&&Encounters.OnRoute(p.init[0],male)&&(dlc||p.id!=103&&p.id!=204)).Select(p=>p.id).ToArray();
   Check(available.Length==(dlc?8:7),"actual config has expected route population");
   var rewards=available.SelectMany(Encounters.For);var shop=Catalog.Generals.Where(g=>Encounters.ShopEligible(g.Id,available,Array.Empty<int>(),new Progress())).Select(g=>g.Id);
   Check(rewards.Concat(shop).Append("zhaoyun").Distinct().Count()==35,"actual native routes can obtain all 35 generals");Check(!rewards.Intersect(shop).Any(),"native available NPC rewards are exclusive to battle");
   foreach(int absent in Encounters.Npcs.Except(available))Check(Encounters.For(absent).All(shop.Contains),"absent character rewards appear in shop");
  }
  Check(Encounters.RewardPool.Length==30&&Encounters.RewardPool.Distinct().Count()==30,"30 unique NPC rewards");Check(Encounters.For(201)[2]=="sunquan","Meng Huaian third stage is Sun Quan");
  foreach(var gender in new[]{GenderDefine.Female,GenderDefine.Male}){
   SanguoshaView.OpenTestDirectory();table=SanguoshaView.Current;Check(table!=null,"test table opens");end=Time.realtimeSinceStartup+45;while(!table.AudioReady&&Time.realtimeSinceStartup<end)yield return null;Check(table.AudioReady,"art and audio preloaded");Set(table,"testDirectory",false);AccessTools.Property(typeof(SanguoshaView),"Session").SetValue(table,new SanguoshaSession(201,2,"孟怀安",gender),null);Check(table.StartBattle("zhaoyun",false),"test battle starts without save");Set(table,"aiAt",Time.unscaledTime+999);
   end=Time.realtimeSinceStartup+25;while(!table.ParticipantPortraitsReady&&Time.realtimeSinceStartup<end)yield return null;Debug.Log("PARTICIPANT HEADS: "+table.ParticipantHead(0)+" / "+table.ParticipantHead(1));yield return Shot("heads-diagnostic");Check(table.ParticipantPortraitsReady,"both real StudentAge head images loaded");Check(table.ParticipantHead(0).Contains(gender==GenderDefine.Female?"role_female2":"role_male2"),"protagonist head follows sex and school stage");Check(table.ParticipantHead(1)==Cfg.PersonCfgMap[201].GetHeadIcon(GenderDefine.Unknown,0,1),"opponent portrait matches actual NPC");
   yield return new WaitForSecondsRealtime(.25f);yield return Shot(gender+"-native-match");var m=Blank("zhaoyun");var slash=Card("slash");var jink=Card("jink");m.Seats[0].Hand.AddRange(new[]{slash,Card("peach"),jink,Card("nullification")});RunRule(m,"Round",0);yield return Fixture(m);yield return Ready();Check(table.ParticipantSpeech(0)==""&&table.ParticipantSpeech(1)=="","silent participants have no bubble");yield return Shot(gender+"-idle");
   if(gender==GenderDefine.Female){
    yield return Drag(slash.Id,new Vector2(795,170));end=Time.realtimeSinceStartup+4;while(table.ParticipantSpeech(0)!="杀！"&&Time.realtimeSinceStartup<end)yield return null;Check(table.ParticipantSpeech(0)=="杀！","actual drag slash triggers timed player speech");yield return new WaitForSecondsRealtime(.2f);yield return Shot("female-slash");var shortSize=table.ParticipantBubble(0).size;
    foreach(int actor in new[]{0,1}){table.SpeakParticipant(actor,"slash");yield return new WaitForSecondsRealtime(.15f);var part=((Array)Field(table,"participants")).GetValue(actor);float anchor=(float)Field(part,"BubbleAnchor");Check(Mathf.Abs(table.ParticipantBubble(actor).x+anchor-(actor==0?172:1356))<.1f,"speech tail points to actual portrait center");Check(Field(part,"BubbleTexture")!=null,"bubble and tail share one rendered surface");}
    float clock=(float)Field(table,"tableClock");Set(table,"help",true);yield return new WaitForSecondsRealtime(1);Check(Mathf.Abs((float)Field(table,"tableClock")-clock)<.05f&&table.ParticipantSpeech(0)=="杀！","dialogue timer pauses with rules overlay");Set(table,"help",false);yield return new WaitForSecondsRealtime(2.5f);Check(table.ParticipantSpeech(0)=="","bubble expires without idle placeholder");
    m=Blank("zhaoyun");m.Seats[1].Hand.Add(slash);m.Seats[0].Hand.AddRange(new[]{jink,Card("peach"),Card("nullification")});RunRule(m,"Use",1,slash,"slash",false);yield return Fixture(m);yield return Ready();table.SpeakParticipant(1,"slash");yield return new WaitForSecondsRealtime(.15f);yield return Shot("opponent-slash");yield return Drag(jink.Id,new Vector2(800,455));end=Time.realtimeSinceStartup+4;while(table.ParticipantSpeech(0)!="闪！"&&Time.realtimeSinceStartup<end)yield return null;Check(table.ParticipantSpeech(0)=="闪！"&&m.Seats[0].Hp==4,"one drag jink both cancels damage and speaks");yield return new WaitForSecondsRealtime(.2f);yield return Shot("female-jink");yield return new WaitForSecondsRealtime(2.5f);
    var cfg=(SanguoshaDialogueConfig)Field(table,"dialogue");cfg.Lines["future"]=new SanguoshaDialogueLine{Text="这一局先让我想一想。等你下次出牌，我可不会这么轻易让你过关了！",Seconds=3};table.SpeakParticipant(0,"future");yield return new WaitForSecondsRealtime(.2f);Check(table.ParticipantBubble(0).width>shortSize.x&&table.ParticipantBubble(0).height>shortSize.y,"bubble grows and wraps for edited dialogue");yield return Shot("adaptive-dialogue");yield return new WaitForSecondsRealtime(3.1f);table.SpeakParticipant(0,"peach");Check(table.ParticipantSpeech(0)=="","other cards do not create default dialogue");
    cfg.Lines["long"]=new SanguoshaDialogueLine{Text=new string('杀',240)};table.SpeakParticipant(1,"long");Check(table.ParticipantBubble(1).yMax<500,"long configured dialogue stays inside designated area");
    cfg.Speakers["player_female"].Expressions["slash"].Image="native:role_head/role_female2_xiaofu";File.WriteAllText(SanguoshaDialogueConfig.ConfigPath,Newtonsoft.Json.JsonConvert.SerializeObject(cfg,Newtonsoft.Json.Formatting.Indented));AccessTools.Method(typeof(SanguoshaView),"BuildParticipants").Invoke(table,null);end=Time.realtimeSinceStartup+20;while(!table.ParticipantPortraitsReady&&Time.realtimeSinceStartup<end)yield return null;yield return new WaitForSecondsRealtime(1);table.SpeakParticipant(0,"slash");yield return new WaitForSecondsRealtime(.2f);yield return Shot("configured-expression");
    var ps=(Array)Field(table,"participants");var images=(IDictionary)Field(ps.GetValue(0),"Images");Check(images.Contains("slash")&&images["slash"]!=null,"configured native expression loads separately");File.Delete(SanguoshaDialogueConfig.ConfigPath);
   }
   table.Close();Check(table.Closed&&!table.ParticipantPortraitsReady,"closing releases portraits and dialogue state");yield return new WaitForSecondsRealtime(.5f);
  }
  Check(!failed,"no Unity exceptions");File.WriteAllText(Path.Combine(dir,"success.txt"),"SANGUOSHA_PARTICIPANTS_RUNTIME_OK");yield return new WaitForSecondsRealtime(.3f);Application.Quit();
 }
}
